// Aptitude metadata: categories (43 topics) + subtopics per topic
const CATEGORIES = {
  quantitative: ['Percentages','Profit, Loss & Discount','Ratio & Proportion','Averages','Time, Speed & Distance','Time & Work','Simple & Compound Interest','Number System','LCM & HCF','Probability','Permutation & Combination','Algebra','Data Interpretation','Simplification','Mensuration'],
  logical: ['Number Series','Coding-Decoding','Blood Relations','Direction Sense','Syllogism','Seating Arrangement','Puzzles','Statement & Conclusions','Statement & Assumptions','Data Sufficiency','Analogy','Odd One Out','Venn Diagrams','Clocks & Calendars','Ranking & Order'],
  verbal: ['Reading Comprehension','Sentence Correction','Error Detection','Fill in the Blanks','Para Jumbles','Synonyms & Antonyms','Vocabulary','Sentence Completion','Grammar','Active & Passive Voice','Direct & Indirect Speech','One Word Substitution','Idioms & Phrases'],
};
const SUBTOPICS = {
  Percentages:['Simple Percentages','Percentage Change'],'Profit, Loss & Discount':['Profit','Loss','Discount'],'Ratio & Proportion':['Simple Ratio','Compound Ratio'],Averages:['Mean','Weighted Average'],'Time, Speed & Distance':['TSD Basics','Relative Speed'],'Time & Work':['Work Rate','Pipes & Cisterns'],'Simple & Compound Interest':['Simple Interest','Compound Interest'],'Number System':['Divisibility','Remainders'],'LCM & HCF':['LCM','HCF'],Probability:['Basic Probability','Conditional'],'Permutation & Combination':['Permutation','Combination'],Algebra:['Linear Equations','Quadratic'],'Data Interpretation':['Tables','Pie Charts','Bar Graphs','Line Graphs'],Simplification:['BODMAS','Approximation'],Mensuration:['Area','Volume','Surface Area'],
  'Number Series':['Arithmetic Series','Geometric Series','Mixed Series'],'Coding-Decoding':['Letter Coding','Number Coding','Symbol Coding'],'Blood Relations':['Family Trees'],'Direction Sense':['Cardinal Directions'],Syllogism:['Categorical','Logical Deduction'],'Seating Arrangement':['Linear','Circular'],Puzzles:['Floor','Box','Scheduling'],'Statement & Conclusions':['Inference'],'Statement & Assumptions':['Assumption'],'Data Sufficiency':['Quant DS'],Analogy:['Word Analogy','Number Analogy'],'Odd One Out':['Classification'],'Venn Diagrams':['Sets'],'Clocks & Calendars':['Clock Angle','Calendar'],'Ranking & Order':['Ranking'],
  'Reading Comprehension':['Short Passages','Long Passages'],'Sentence Correction':['Grammar','Idioms'],'Error Detection':['Grammar Errors'],'Fill in the Blanks':['Single Blank','Double Blank'],'Para Jumbles':['Rearrangement'],'Synonyms & Antonyms':['Synonyms','Antonyms'],Vocabulary:['Word Meanings'],'Sentence Completion':['Reasoning'],Grammar:['Tenses','Articles','Prepositions','SVA','Pronouns','Conjunctions'],'Active & Passive Voice':['Voice Transform'],'Direct & Indirect Speech':['Speech Transform'],'One Word Substitution':['Precise Vocabulary'],'Idioms & Phrases':['Figurative Language'],
};
module.exports = { CATEGORIES, SUBTOPICS };