// Verbal generators (8 / 13). gen(r, i, c) -> c.buildMCQ(opts)
const G = {};
G['Synonyms & Antonyms']=(r,i,c)=>{const vw=[['Ubiquitous','Common','Rare'],['Meticulous','Careful','Careless'],['Candid','Frank','Deceitful'],['Reluctant','Willing','Eager'],['Ambiguous','Unclear','Clear'],['Obstinate','Stubborn','Compliant'],['Benevolent','Kind','Malevolent']],e=c.pk(r,vw);return c.buildMCQ({r,stem:'Choose the ANTONYM of: '+e[0],right:e[2],wrong:[e[1],'Brave','Quick'],explanation:'Antonym of "'+e[0]+'" is "'+e[2]+'"; synonym is "'+e[1]+'".',steps:[e[0]+' <-> '+e[2]]});};
G['Vocabulary']=(r,i,c)=>{const vw=[['Ubiquitous','Common','Rare'],['Meticulous','Careful','Careless'],['Candid','Frank','Deceitful'],['Reluctant','Willing','Eager'],['Ambiguous','Unclear','Clear'],['Obstinate','Stubborn','Compliant'],['Benevolent','Kind','Malevolent']],e=c.pk(r,vw);return c.buildMCQ({r,stem:'What is the SYNONYM of: '+e[0]+'?',right:e[1],wrong:[e[2],'Brave','Quick'],explanation:'Synonym of "'+e[0]+'" is "'+e[1]+'".',steps:[e[0]+' ~= '+e[1]]});};
G['Sentence Completion']=(r,i,c)=>c.buildMCQ({r,stem:'Despite the heavy rain, she decided to go out; _______, she carried an umbrella.',right:'However',wrong:['Therefore','Moreover','Nevertheless'],explanation:'"Despite" signals contrast; "However" is the correct connector.',steps:['Despite -> contrast','However = contrast']});
G['Grammar']=(r,i,c)=>{const R=[['Tense','Identify the tense: "She had completed her homework."','Past Perfect',['Present Perfect','Future Perfect','Simple Past']],['Articles','Choose the correct article: "He is ___ honest person."','an',['a','the','no article']],['Prepositions','Choose the correct preposition: "She is good ___ mathematics."','at',['in','on','with']],['Subject-Verb Agreement','"Neither the teachers nor the principal ___ with the decision."','agree',['agrees','agreeing','agreed']],['Pronouns','Choose: "The students forgot ___ books at home."','their',['there','they','theirs']],['Conjunctions','Complete: "___ it was raining, we went for a walk."','Although',['Because','Since','Unless']]],g=c.pk(r,R);return c.buildMCQ({r,stem:g[1],right:g[2],wrong:g[3],explanation:'Grammar rule ('+g[0]+'): answer is "'+g[2]+'".',steps:['Apply '+g[0]+' rule','Answer: '+g[2]]});};
G['Active & Passive Voice']=(r,i,c)=>c.buildMCQ({r,stem:'Identify the voice: "The book was read by the student."',right:'Passive',wrong:['Active','Impersonal','Reflexive'],explanation:'The subject receives the action, so the sentence is passive.',steps:['Subject is acted upon','Passive voice']});
G['Direct & Indirect Speech']=(r,i,c)=>c.buildMCQ({r,stem:'Convert to indirect speech: He said, "I will go tomorrow."',right:'He said that he would go the next day.',wrong:['He said that he will go tomorrow.','He told that he would go the next day.','He said that he goes the next day.'],explanation:'Future "will" -> "would"; "I" -> "he"; "tomorrow" -> "the next day".',steps:['"will" -> "would"','"I" -> "he"','"tomorrow" -> "next day"']});
G['One Word Substitution']=(r,i,c)=>{const E=[['One who studies insects','Entomologist'],['One who runs away to avoid arrest','Fugitive'],['One who does not believe in the existence of God','Atheist'],['A book written by an unknown author','Anonymous'],['One who loves books','Bibliophile']],e=c.pk(r,E);return c.buildMCQ({r,stem:e[0],right:e[1],wrong:E.filter(x=>x!==e).map(x=>x[1]).slice(0,3),explanation:e[1]+' = '+e[0].toLowerCase()+'.',steps:[e[0]]});};
G['Idioms & Phrases']=(r,i,c)=>{const E=[['Bite the bullet','Face a difficult situation with courage'],['Break the ice','Start a conversation in a social setting'],['Hit the sack','Go to bed'],['Costs an arm and a leg','Is very expensive'],['Piece of cake','Something very easy']],e=c.pk(r,E);return c.buildMCQ({r,stem:'What does the idiom "'+e[0]+'" mean?',right:e[1],wrong:E.filter(x=>x!==e).map(x=>x[1]).slice(0,3),explanation:'Idiom "'+e[0]+'" = "'+e[1]+'".',steps:[e[0]]});};
module.exports = { G };