// Logical generators (8 / 15). gen(r, i, c) -> c.buildMCQ(opts)
const G = {};
G['Statement & Conclusions']=(r,i,c)=>c.buildMCQ({r,stem:'Statement: "All that glitters is not gold." Conclusion: Some things that glitter are not gold.',right:'The conclusion follows',wrong:['Does not follow','Contradicts','Always true'],explanation:'The statement implies some glittering things are not gold; conclusion follows.',steps:['Statement = some glitter != gold','Conclusion follows']});
G['Statement & Assumptions']=(r,i,c)=>c.buildMCQ({r,stem:'Statement: "Brush your teeth twice daily to keep them healthy." Assumption: Brushing helps prevent tooth problems.',right:'The assumption is implicit',wrong:['Not implicit','Contradicts','Cannot say'],explanation:'The statement links brushing to dental health; the assumption is implicit.',steps:['Statement links brushing to health','Assumption implicit']});
G['Data Sufficiency']=(r,i,c)=>c.buildMCQ({r,stem:'What is the value of X? (1) X^2 = 25 (2) X is positive.',right:'Both statements together are sufficient',wrong:['Statement (1) alone is sufficient','Statement (2) alone is sufficient','Neither statement alone is sufficient'],explanation:'(1) gives X=5 or -5; (2) narrows to positive, so X=5. Together sufficient.',steps:['(1): X = 5 or -5','(2): X > 0','Together: X = 5']});
G['Analogy']=(r,i,c)=>c.buildMCQ({r,stem:'Finger : Hand :: Toe : ?',right:'Foot',wrong:['Hand','Leg','Palm'],explanation:'Finger is a part of Hand; Toe is a part of Foot.',steps:['Finger -> Hand','Toe -> Foot']});
G['Odd One Out']=(r,i,c)=>c.buildMCQ({r,stem:'Find the odd one out: Rose, Lily, Jasmine, Sugarcane',right:'Sugarcane',wrong:['Rose','Lily','Jasmine'],explanation:'Rose, Lily and Jasmine are flowering plants; Sugarcane is a grass.',steps:['Rose = flower','Lily = flower','Jasmine = flower','Sugarcane = grass']});
G['Venn Diagrams']=(r,i,c)=>{const tot=100,ch=c.ri(r,40,60),ca=c.ri(r,30,50),bth=c.ri(r,10,25),oc=ch-bth;return c.buildMCQ({r,stem:'In a group of '+tot+', '+ch+' play chess, '+ca+' play carrom, '+bth+' play both. How many play ONLY chess?',right:String(oc),wrong:[String(ch+bth),String(ch),String(bth)],explanation:'Only chess = chess - both = '+ch+' - '+bth+' = '+oc+'.',steps:['Only chess = '+ch+'-'+bth,'= '+oc]});};
G['Clocks & Calendars']=(r,i,c)=>{const hour=c.ri(r,1,12),min=30,ha=(hour%12)*30+min/2,ma=min*6,diff=Math.abs(ha-ma),ang=diff>180?360-diff:diff;return c.buildMCQ({r,stem:'What is the angle between the hands of a clock at '+hour+':30?',right:Math.round(ang)+' degrees',wrong:[Math.round(360-diff)+' degrees',Math.round(Math.abs(ha-ma))+' degrees',Math.abs(hour-6)*30+' degrees'],explanation:'Hour hand = '+ha+' deg, minute = '+ma+' deg, angle = '+Math.round(ang)+' deg.',steps:['Hour = '+ha+'deg','Minute = '+ma+'deg','Angle = '+Math.round(ang)+'deg']});};
G['Ranking & Order']=(r,i,c)=>{const pos=c.ri(r,5,20),tot=c.ri(r,pos+10,pos+30),fl=tot-pos+1;return c.buildMCQ({r,stem:'In a row of '+tot+' students, A is '+pos+'th from the left. What is A\'s position from the right?',right:fl+'th',wrong:[(tot-pos)+'th',pos+'th',(tot-pos+2)+'th'],explanation:'From right = total - left + 1 = '+fl+'th.',steps:['('+tot+'-'+pos+')+1','= '+fl+'th']});};
module.exports = { G };