// Quantitative generators (8 / 15). gen(r, i, c) -> c.buildMCQ(opts); c = {ri, pk, buildMCQ}
const G = {};
G['Percentages']=(r,i,c)=>{const n=c.ri(r,120,980),p=c.ri(r,5,95),v=Math.round(p/100*n);return c.buildMCQ({r,stem:'If '+p+'% of a number is '+v+', what is the number?',right:String(n),wrong:[String(n+100),String(n-50),String(v)],explanation:p+'% of '+n+' = '+v+'.',steps:['x = 100*'+v+'/'+p,'x = '+n]});};
G['Profit, Loss & Discount']=(r,i,c)=>{const cp=c.ri(r,200,2000),pr=c.ri(r,10,60),sp=Math.round(cp*(1+pr/100));return c.buildMCQ({r,stem:'A man buys an article for Rs.'+cp+' and sells it for Rs.'+sp+'. What is his profit percentage?',right:pr+'%',wrong:[(pr+5)+'%',(pr-3)+'%',(pr+10)+'%'],explanation:'Profit% = '+(sp-cp)+'/'+cp+'*100 = '+pr+'%.',steps:['Profit = '+(sp-cp),'Profit% = '+pr+'%']});};
G['Ratio & Proportion']=(r,i,c)=>{const a=c.ri(r,2,12),b=c.ri(r,2,12),tot=c.ri(r,40,200),sa=Math.round(a/(a+b)*tot);return c.buildMCQ({r,stem:'Rs.'+tot+' is divided between A and B in the ratio '+a+':'+b+'. How much does A get?',right:'Rs.'+sa,wrong:['Rs.'+(tot-sa),'Rs.'+(sa+50),'Rs.'+Math.round(tot/2)],explanation:"A's share = "+a+'/'+(a+b)+'*'+tot+' = Rs.'+sa+'.',steps:['Total parts = '+(a+b),"A's share = Rs."+sa]});};
G['Averages']=(r,i,c)=>{const base=c.ri(r,20,80),n=c.ri(r,3,8),ex=c.ri(r,base-15,base+10),na=Math.round((base*n-ex)/(n-1));return c.buildMCQ({r,stem:'The average of '+n+' numbers is '+base+'. If one number ('+ex+') is excluded, what is the new average?',right:String(na),wrong:[String(na+3),String(na-2),String(base)],explanation:'New average = '+na+'.',steps:['Sum='+(base*n),'New sum='+(base*n-ex),'New avg='+na]});};
G['Time, Speed & Distance']=(r,i,c)=>{const d=c.ri(r,120,600),sp=c.ri(r,30,90),tm=Math.round(d/sp*60);return c.buildMCQ({r,stem:'A train covers '+d+' km at '+sp+' km/h. How much time does it take (in minutes)?',right:tm+' min',wrong:[(tm+15)+' min',(tm-10)+' min',(tm+30)+' min'],explanation:'Time = '+d+'/'+sp+' h = ~'+tm+' min.',steps:['Time = '+d+'/'+sp+' h','= ~'+tm+' min']});};
G['Time & Work']=(r,i,c)=>{const ad=c.ri(r,3,12),bd=c.ri(r,3,12),rt=1/ad+1/bd,tg=Math.round(1/rt*10)/10;return c.buildMCQ({r,stem:'A can do a piece of work in '+ad+' days and B in '+bd+' days. In how many days can they finish it together?',right:tg+' days',wrong:[(tg+1)+' days',Math.round(tg)+' days',(tg+2)+' days'],explanation:'Combined rate = 1/'+ad+'+1/'+bd+' = '+rt.toFixed(3)+'; time = '+tg+' days.',steps:['1/'+ad+'+1/'+bd+'='+rt.toFixed(4),'Time='+tg+' days']});};
G['Simple & Compound Interest']=(r,i,c)=>{const pr=c.ri(r,5000,50000),rate=c.ri(r,4,15),yr=c.ri(r,2,4),si=Math.round(pr*rate*yr/100);return c.buildMCQ({r,stem:'What is the simple interest on Rs.'+pr+' at '+rate+'% per annum for '+yr+' years?',right:'Rs.'+si,wrong:['Rs.'+(si+500),'Rs.'+(si-300),'Rs.'+Math.round(pr*rate*yr/1000)],explanation:'SI = P*R*T/100 = Rs.'+si+'.',steps:['SI = P*R*T/100','= Rs.'+si]});};
G['Number System']=(r,i,c)=>{const len=c.ri(r,3,6),d=[];for(let k=0;k<len;k++)d.push(c.ri(r,0,9));if(d[0]===0)d[0]=c.ri(r,1,9);const nm=d.join('');return c.buildMCQ({r,stem:'The digits of a '+len+'-digit number are reversed and subtracted from the original. The result is always divisible by?',right:'9',wrong:['7','11','13'],explanation:'For any number abc, (abc-cba) is divisible by 9 and 11.',steps:['Number = '+nm,'Reversed digits','Difference divisible by 9']});};
module.exports = { G };