// Quantitative generators (7 / 15). gen(r, i, c) -> c.buildMCQ(opts)
const G = {};
G['LCM & HCF']=(r,i,c)=>{const a=c.ri(r,12,60),b=c.ri(r,8,50),gcd=(x,y)=>y?gcd(y,x%y):x,h=gcd(a,b),l=a*b/h;return c.buildMCQ({r,stem:'What is the LCM of '+a+' and '+b+'?',right:String(l),wrong:[String(l+h),String(h),String(a+b)],explanation:'HCF('+a+','+b+') = '+h+'; LCM = '+a+'*'+b+'/'+h+' = '+l+'.',steps:['HCF = '+h,'LCM = '+l]});};
G['Probability']=(r,i,c)=>{const tot=c.ri(r,8,16),red=c.ri(r,2,tot-2);return c.buildMCQ({r,stem:'A bag contains '+tot+' balls, '+red+' of which are red. If one ball is drawn at random, what is the probability it is red?',right:red+'/'+tot,wrong:[(tot-red)+'/'+tot,Math.round(red/tot*100)+'%',red+'/'+(tot-red)],explanation:'P(red) = '+red+'/'+tot+'.',steps:['P(red) = '+red+'/'+tot]});};
G['Permutation & Combination']=(r,i,c)=>{const n=c.ri(r,4,9),k=c.ri(r,2,n-1),fact=x=>x<=1?1:x*fact(x-1),perm=fact(n)/fact(n-k);return c.buildMCQ({r,stem:'In how many ways can '+k+' letters be selected and arranged from '+n+' different letters?',right:String(perm),wrong:[String(fact(n)/(fact(k)*fact(n-k))),String(fact(n)),String(n**k)],explanation:'P('+n+','+k+') = '+n+'!/'+(n-k)+'! = '+perm+'.',steps:['P('+n+','+k+') = '+perm]});};
G['Algebra']=(r,i,c)=>{const a=c.ri(r,2,12),b=c.ri(r,5,30),x=Math.round(b/a);return c.buildMCQ({r,stem:'If '+a+'x + '+(a*2)+' = '+(b+a*2)+', what is x?',right:String(x),wrong:[String(x+1),String(x-1),(b/a).toFixed(2)],explanation:a+'x = '+b+'; x = '+x+'.',steps:[a+'x = '+b,'x = '+x]});};
G['Data Interpretation']=(r,i,c)=>{const v=[c.ri(r,20,90),c.ri(r,20,90),c.ri(r,20,90),c.ri(r,20,90)],tg=c.ri(r,0,3);return c.buildMCQ({r,timeLimit:120,stem:'For stream '+(tg+1)+' (row '+(tg+1)+'), the 2020 value is?\n| S | 2018 | 2019 | 2020 | 2021 |\n| A | '+(v[0]-5)+' | '+v[0]+' | '+v[0]+' | '+(v[0]+5)+' |\n| B | '+v[1]+' | '+v[1]+' | '+v[1]+' | '+v[1]+' |\n| C | '+v[2]+' | '+v[2]+' | '+v[2]+' | '+v[2]+' |\n| D | '+v[3]+' | '+v[3]+' | '+v[3]+' | '+v[3]+' |',right:String(v[tg]),wrong:[String(v[tg]+5),String(v[tg]-5),String(v[0])],explanation:'2020 stream '+(tg+1)+' = '+v[tg]+'.',steps:['Read row '+(tg+1),'Value = '+v[tg]]});};
G['Simplification']=(r,i,c)=>{const a=c.ri(r,5,25),b=c.ri(r,5,25),cc=c.ri(r,3,12),val=Math.round(a*b/cc);return c.buildMCQ({r,stem:'Simplify: ('+a+' * '+b+') / '+cc+' = ?',right:String(val),wrong:[String(val+5),String(val-3),String(Math.round(a*b/(cc+1)))],explanation:'= '+a+'*'+b+'/'+cc+' = '+val+'.',steps:[a+'*'+b+'='+(a*b),'='+val]});};
G['Mensuration']=(r,i,c)=>{const s=c.ri(r,4,25),area=s*s;return c.buildMCQ({r,stem:'What is the area of a square with side '+s+' cm?',right:area+' sq cm',wrong:[(area+s)+' sq cm',(2*s)+' sq cm',(s*4)+' sq cm'],explanation:'Area = side^2 = '+s+'^2 = '+area+' sq cm.',steps:['Area = '+s+'^2','= '+area+' sq cm']});};
module.exports = { G };