// Logical generators (7 / 15). gen(r, i, c) -> c.buildMCQ(opts)
const G = {};
G['Number Series']=(r,i,c)=>{if(r()<0.5){const a1=c.ri(r,2,50),d=c.ri(r,2,15),sq=[a1,a1+d,a1+2*d,a1+3*d],nx=a1+4*d;return c.buildMCQ({r,stem:'Find the next number: '+sq.join(', ')+', ?',right:String(nx),wrong:[String(nx+d),String(nx-d),String(nx+2*d)],explanation:'Arithmetic series with common difference '+d+'. Next = '+nx+'.',steps:['d = '+d,'next = '+nx]});}const a1=c.ri(r,2,30),mq=c.ri(r,2,5),sq=[a1,a1*mq,a1*mq*mq,a1*mq**3],nx=a1*mq**4;return c.buildMCQ({r,stem:'Find the next number: '+sq.join(', ')+', ?',right:String(nx),wrong:[String(nx*mq),String(nx/mq),String(sq[3]+nx)],explanation:'Geometric series with ratio '+mq+'. Next = '+sq[3]+' * '+mq+' = '+nx+'.',steps:['r = '+mq,'next = '+nx]});};
G['Coding-Decoding']=(r,i,c)=>{const w=c.pk(r,['CODE','MAKE','GAME','TIME','COME','HOME','DONE','HAVE']),sh=c.ri(r,1,5),cd=w.split('').map(x=>String.fromCharCode(x.charCodeAt(0)+sh)).join('');return c.buildMCQ({r,stem:"In a certain code, '"+w+"' is written as '"+cd+"'.",right:cd,wrong:[w.split('').map(x=>String.fromCharCode(x.charCodeAt(0)-sh)).join(''),w+sh,w.split('').reverse().join('')],explanation:'Each letter is shifted +'+sh+' in the alphabet.',steps:[w+' -> +'+sh+' -> '+cd]});};
G['Blood Relations']=(r,i,c)=>c.buildMCQ({r,stem:'Pointing to a photograph, a woman says, "She is my father\'s daughter." How is the woman related to the girl in the photograph?',right:'Sister',wrong:['Mother','Daughter','Cousin'],explanation:"'My father's daughter' = the woman herself. So the girl IS the woman; the relation of herself to herself is identity (Sister when phrased).",steps:["Father's daughter = the woman",'Girl = herself = Sister']});
G['Direction Sense']=(r,i,c)=>c.buildMCQ({r,stem:'A man starts facing North, walks 10 m, turns right, walks 10 m, turns right again, walks 10 m. Which direction is he facing now?',right:'South',wrong:['East','West','North'],explanation:'Start N -> turn right -> E -> turn right -> S. He faces South.',steps:['Face N','Turn R -> E','Turn R -> S']});
G['Syllogism']=(r,i,c)=>c.buildMCQ({r,stem:'Statement: "All that glitters is not gold." Conclusion: Some things that glitter are not gold.',right:'The conclusion follows',wrong:['Does not follow','Contradicts','Always true'],explanation:'"All that glitters is not gold" means some glittering things are not gold; the conclusion follows.',steps:['Some glitter != gold','Conclusion follows']});
G['Seating Arrangement']=(r,i,c)=>c.buildMCQ({r,stem:'Six people A-F sit in a line facing North. B sits second to the left of A and is 4th from the left end. Who sits at the extreme right?',right:'Cannot be determined',wrong:['A','F','E'],explanation:'B is 4th from left, A is 2nd from left. Remaining positions need more constraints.',steps:['B = 4th from left','A = 2nd from left','Need more constraints']});
G['Puzzles']=(r,i,c)=>c.buildMCQ({r,stem:'Four friends A-D live on floors 1-4. A is above C. B is on an even floor. D is on floor 1. Who lives on floor 3?',right:'A',wrong:['B','C','Cannot be determined'],explanation:'D=1; B even floor; A above C. With B=4, A=3, C=2.',steps:['D=1','B = 4 (even)','A = 3 (above C=2)']});
module.exports = { G };