// Quantitative generators v2 - multi-template scenarios + notebook-style worked steps
// gen(r, i, c) -> c.buildMCQ(opts); c = {ri, pk, buildMCQ, difficulty}
const G = {};

const TPCT = [
    (r, i, c) => { const P = c.pk(r, [5, 10, 20, 25, 40, 50, 60, 75, 80]); const N = c.ri(r, 12, 90) * 10; const V = Math.round(P * N / 100);
      return c.buildMCQ({ r, stem: 'If ' + P + '% of a number is ' + V + ', what is the number?', right: String(N), wrong: [String(N + 20), String(2 * V), String(Math.round(N / 2))], explanation: 'Whole = 100 x ' + V + ' / ' + P + ' = ' + N + '.', steps: ['Given: ' + P + '% of N = ' + V, 'N = 100 x ' + V + ' / ' + P, '   = ' + (100 * V) + ' / ' + P + ' = ' + N] }); },
    (r, i, c) => { const P = c.pk(r, [5, 10, 15, 20, 25, 30, 40, 60, 75]); const N = c.ri(r, 4, 40) * 20; const V = Math.round(P * N / 100);
      return c.buildMCQ({ r, stem: 'What is ' + P + '% of ' + N + '?', right: String(V), wrong: [String(V + 20), String(2 * V), String(Math.round(N / 2))], explanation: P + '% of ' + N + ' = ' + V + '.', steps: [P + '% of ' + N + ' = ' + P + ' / 100 x ' + N, '   = ' + (P * N) + ' / 100 = ' + V] }); },
    (r, i, c) => { const P = c.pk(r, [10, 20, 25, 40, 50]); const V = c.ri(r, 4, 40) * 100; const NV = Math.round(V * (100 + P) / 100);
      return c.buildMCQ({ r, stem: 'The price of a scooter increases from Rs.' + V + ' to Rs.' + NV + '. What is the percentage increase?', right: P + '%', wrong: [(P + 5) + '%', (P - 5) + '%', (P + 10) + '%'], explanation: 'Increase % = ' + (NV - V) + ' / ' + V + ' x 100 = ' + P + '%.', steps: ['Increase = ' + NV + ' - ' + V + ' = ' + (NV - V), 'Increase % = ' + (NV - V) + ' / ' + V + ' x 100 = ' + P + '%'] }); },
    (r, i, c) => { const P = c.pk(r, [10, 20, 25, 50]); const V = c.ri(r, 4, 30) * 100; const NV = Math.round(V * (100 - P) / 100);
      return c.buildMCQ({ r, stem: 'A shirt priced at Rs.' + V + ' is available at a discount of ' + P + '%. What is its new price?', right: 'Rs.' + NV, wrong: ['Rs.' + (NV + 50), 'Rs.' + (V - 10), 'Rs.' + (NV - 20)], explanation: 'New price = ' + NV + '.', steps: ['Discount = ' + P + '% of ' + V + ' = ' + (V - NV), 'New price = ' + V + ' - ' + (V - NV) + ' = Rs.' + NV] }); },
    (r, i, c) => { const x = c.pk(r, [10, 20, 25, 40, 50]), y = c.pk(r, [5, 15, 30, 60, 75]);
      return c.buildMCQ({ r, stem: 'If ' + x + '% of A = ' + y + '% of B, then A : B is equal to:', right: y + ' : ' + x, wrong: [x + ' : ' + y, (x + y) + ' : ' + x, y + ' : ' + (x + y)], explanation: 'A/B = ' + y + '/' + x + '.', steps: [x + '% of A = ' + y + '% of B', 'A / B = ' + y + ' / ' + x, 'A : B = ' + y + ' : ' + x] }); },
    (r, i, c) => { const P = c.ri(r, 4, 20) * 1000, a = c.pk(r, [5, 10, 20]), b = c.pk(r, [5, 10, 20]); const F = Math.round(P * (100 + a) / 100 * (100 + b) / 100);
      return c.buildMCQ({ r, stem: 'The population of a town is ' + P + '. It increases by ' + a + '% in the first year and by ' + b + '% in the second year. What is the population at the end of 2 years?', right: String(F), wrong: [String(F + 1000), String(Math.round(P * (100 + a + b) / 100)), String(F - 500)], explanation: 'Final = ' + F + '.', steps: ['After year 1: ' + P + ' x ' + (100 + a) + ' / 100 = ' + Math.round(P * (100 + a) / 100), 'After year 2: ' + Math.round(P * (100 + a) / 100) + ' x ' + (100 + b) + ' / 100 = ' + F] }); },
    (r, i, c) => { const p = c.pk(r, [50, 60, 70, 75, 80]), S = c.ri(r, 4, 30) * 100; const I = Math.round(100 * S / (100 - p));
      return c.buildMCQ({ r, stem: 'Ravi spends ' + p + '% of his monthly income and saves the remaining Rs.' + S + '. What is his monthly income?', right: 'Rs.' + I, wrong: ['Rs.' + (I + 500), 'Rs.' + Math.round(S * (100 - p) / 100), 'Rs.' + (I - 200)], explanation: 'Income = Rs.' + I + '.', steps: ['Savings % = 100 - ' + p + ' = ' + (100 - p) + '%', 'Income x ' + (100 - p) + ' / 100 = ' + S, 'Income = ' + S + ' x 100 / ' + (100 - p) + ' = Rs.' + I] }); },
];
TPCT.push(...[
    (r, i, c) => { const pr = c.pk(r, [[25, 20], [100, 50], [300, 75]]);
      return c.buildMCQ({ r, stem: 'If A\'s salary is ' + pr[0] + '% more than B\'s salary, then B\'s salary is how much percent less than A\'s?', right: pr[1] + '%', wrong: [pr[0] + '%', (100 - pr[1]) + '%', (pr[1] + 5) + '%'], explanation: 'Less % = ' + pr[1] + '%.', steps: ['Let B = 100, then A = 100 + ' + pr[0] + ' = ' + (100 + pr[0]), 'B is less than A by ' + (100 + pr[0] - 100) + ' = ' + pr[0], 'Less % = ' + pr[0] + ' / ' + (100 + pr[0]) + ' x 100 = ' + pr[1] + '%'] }); },
    (r, i, c) => { const A = c.ri(r, 4, 40) * 50, q = c.pk(r, [10, 20, 25, 40, 50, 75]); const B = Math.round(A * q / 100);
      return c.buildMCQ({ r, stem: 'What percent of ' + A + ' is ' + B + '?', right: q + '%', wrong: [(q + 10) + '%', (q - 5) + '%', (2 * q) + '%'], explanation: q + '%.', steps: ['Required % = ' + B + ' / ' + A + ' x 100', '   = ' + (100 * B / A) + '% = ' + q + '%'] }); },
    (r, i, c) => { const rr = c.pk(r, [10, 20, 30, 40, 50]); const net = rr * rr / 100;
      return c.buildMCQ({ r, stem: 'The price of an article first decreases by ' + rr + '% and then increases by ' + rr + '%. What is the net percentage change?', right: net + '% decrease', wrong: ['No change', net + '% increase', (net + 1) + '% decrease'], explanation: net + '% decrease.', steps: ['Let price = 100', 'After decrease: 100 x ' + (100 - rr) + ' / 100 = ' + (100 - rr), 'After increase: ' + (100 - rr) + ' x ' + (100 + rr) + ' / 100 = ' + ((10000 - rr * rr) / 100), 'Net change = 100 - ' + ((10000 - rr * rr) / 100) + ' = ' + net + '% decrease'] }); },
    (r, i, c) => { const x = c.pk(r, [25, 30, 33, 40]), p = c.pk(r, [40, 45, 50, 60]); const m = c.ri(r, 2, 10) * 5; const T = Math.round(100 * m / (p - x));
      return c.buildMCQ({ r, stem: 'In an exam, a student scoring ' + x + '% marks fails by ' + m + ' marks, while the passing marks are ' + p + '%. What are the total marks of the exam?', right: String(T), wrong: [String(T + 100), String(2 * T), String(T - 50)], explanation: 'Total marks = ' + T + '.', steps: ['Passing marks = ' + x + '% of T + ' + m + '  ...(1)', 'Passing marks = ' + p + '% of T  ...(2)', 'From (1) and (2): ' + (p - x) + 'T / 100 = ' + m, 'T = ' + m + ' x 100 / ' + (p - x) + ' = ' + T] }); },
    (r, i, c) => { const pr = c.pk(r, [[25, 20], [100, 50], [150, 60]]);
      return c.buildMCQ({ r, stem: 'The price of sugar rises by ' + pr[0] + '%. By what percent must a family reduce its consumption so that the expenditure remains the same?', right: pr[1] + '%', wrong: [pr[0] + '%', (100 - pr[1]) + '%', (pr[1] + 5) + '%'], explanation: pr[1] + '%.', steps: ['Let old price = 100, quantity = 100', 'New price = ' + (100 + pr[0]), 'New quantity = 100 x 100 / ' + (100 + pr[0]) + ' = ' + (10000 / (100 + pr[0])), 'Reduction = 100 - ' + (10000 / (100 + pr[0])) + ' = ' + pr[1] + ' i.e. ' + pr[1] + '%'] }); },
    (r, i, c) => { const a = c.pk(r, [10, 20, 25, 30]), b = c.pk(r, [5, 10, 15, 20]); const eq = a + b - a * b / 100;
      return c.buildMCQ({ r, stem: 'Two successive discounts of ' + a + '% and ' + b + '% are equivalent to a single discount of:', right: eq + '%', wrong: [(a + b) + '%', (eq + 2) + '%', (eq - 3) + '%'], explanation: eq + '%.', steps: ['Let MP = 100', 'After 1st discount: 100 - ' + a + ' = ' + (100 - a), 'After 2nd: ' + (100 - a) + ' x ' + (100 - b) + ' / 100 = ' + ((100 - a) * (100 - b) / 100), 'Equivalent discount = 100 - ' + ((100 - a) * (100 - b) / 100) + ' = ' + eq + '%'] }); },
    (r, i, c) => { const x = c.pk(r, [10, 20, 25, 40, 50]), y = c.pk(r, [10, 20, 25, 40, 60]); const z = x * y / 100;
      return c.buildMCQ({ r, stem: 'If A is ' + x + '% of B and B is ' + y + '% of C, then A is what percent of C?', right: z + '%', wrong: [(x + y) + '%', (z + 5) + '%', (z * 2) + '%'], explanation: z + '% of C.', steps: ['A = ' + x + '% of B = ' + x + '/100 x B', 'B = ' + y + '% of C = ' + y + '/100 x C', 'A = ' + x + ' x ' + y + ' / 10000 x C', '   = ' + z + '% of C'] }); },
]);
G['Percentages'] = (r, i, c) => { return TPCT[i % TPCT.length](r, i, c); };

const TPLD = [
    (r, i, c) => { const CP = c.ri(r, 3, 25) * 100, p = c.pk(r, [10, 15, 20, 25, 30, 40, 50]); const SP = Math.round(CP * (100 + p) / 100);
      return c.buildMCQ({ r, stem: 'A man buys an article for Rs.' + CP + ' and sells it for Rs.' + SP + '. Find his profit percentage.', right: p + '%', wrong: [(p + 5) + '%', (p - 5) + '%', (p + 10) + '%'], explanation: 'Profit% = ' + p + '%.', steps: ['Profit = SP - CP = ' + SP + ' - ' + CP + ' = ' + (SP - CP), 'Profit% = ' + (SP - CP) + ' / ' + CP + ' x 100', '   = ' + p + '%'] }); },
    (r, i, c) => { const CP = c.ri(r, 3, 25) * 100, p = c.pk(r, [10, 20, 25, 30, 50]); const SP = Math.round(CP * (100 + p) / 100);
      return c.buildMCQ({ r, stem: 'A trader buys a cycle for Rs.' + CP + ' and wants a profit of ' + p + '%. At what price should he sell it?', right: 'Rs.' + SP, wrong: ['Rs.' + (SP + 100), 'Rs.' + (SP - 50), 'Rs.' + (CP + 2 * (SP - CP))], explanation: 'SP = Rs.' + SP + '.', steps: ['Profit = ' + p + '% of ' + CP + ' = ' + (SP - CP), 'SP = CP + Profit = ' + CP + ' + ' + (SP - CP), '   = Rs.' + SP] }); },
    (r, i, c) => { const CP = c.ri(r, 4, 20) * 100, l = c.pk(r, [10, 20, 25, 40, 50]); const SP = Math.round(CP * (100 - l) / 100);
      return c.buildMCQ({ r, stem: 'A mobile is sold for Rs.' + SP + ' at a loss of ' + l + '%. What was its cost price?', right: 'Rs.' + CP, wrong: ['Rs.' + (SP + l), 'Rs.' + Math.round(SP * 2), 'Rs.' + (CP + 100)], explanation: 'CP = Rs.' + CP + '.', steps: ['SP = ' + (100 - l) + '% of CP', SP + ' = ' + (100 - l) + ' / 100 x CP', 'CP = ' + SP + ' x 100 / ' + (100 - l), '   = Rs.' + CP] }); },
    (r, i, c) => { const x = c.pk(r, [10, 20, 30, 40, 50]); const loss = x * x / 100;
      return c.buildMCQ({ r, stem: 'A man sells two watches at the same price, one at a profit of ' + x + '% and the other at a loss of ' + x + '%. Find his overall profit or loss percentage.', right: loss + '% loss', wrong: ['No profit no loss', loss + '% profit', (loss + 1) + '% loss'], explanation: 'Net loss = ' + x + '^2 / 100 = ' + loss + '%.', steps: ['Let SP of each = 100', 'CP1 = 100 x 100 / ' + (100 + x) + ' = ' + (10000 / (100 + x)), 'CP2 = 100 x 100 / ' + (100 - x) + ' = ' + (10000 / (100 - x)), 'Total CP = ' + (10000 / (100 + x) + 10000 / (100 - x)) + ', SP = 200', 'Loss% = ' + loss + '% loss'] }); },
    (r, i, c) => { const CP = c.ri(r, 4, 15) * 100, mp = Math.round(CP * 1.5), d = c.pk(r, [10, 20, 25]); const SP = Math.round(mp * (100 - d) / 100); const p = Math.round((SP - CP) * 100 / CP);
      return c.buildMCQ({ r, stem: 'A shopkeeper marks an item at Rs.' + mp + ' and gives a discount of ' + d + '%. If the cost price is Rs.' + CP + ', find his profit percentage.', right: p + '%', wrong: [(p + 3) + '%', (p - 2) + '%', '50%'], explanation: 'Profit% = ' + p + '%.', steps: ['Discount = ' + d + '% of ' + mp + ' = ' + (mp - SP), 'SP = ' + mp + ' - ' + (mp - SP) + ' = ' + SP, 'Profit = ' + SP + ' - ' + CP + ' = ' + (SP - CP), 'Profit% = ' + (SP - CP) + ' / ' + CP + ' x 100 = ' + p + '%'] }); },
    (r, i, c) => { const w = c.pk(r, [800, 500, 900, 750, 600, 950]); const g = Math.round((1000 - w) * 100 / w);
      return c.buildMCQ({ r, stem: 'A dishonest shopkeeper sells goods at cost price but uses a false weight of ' + w + ' g instead of 1 kg. Find his gain percentage.', right: g + '%', wrong: [(1000 - w) + '%', (g + 5) + '%', '20%'], explanation: 'Gain% = ' + g + '%.', steps: ['He gives ' + w + ' g but charges for 1000 g', 'Gain = 1000 - ' + w + ' = ' + (1000 - w) + ' g', 'Gain% = ' + (1000 - w) + ' / ' + w + ' x 100 = ' + g + '%'] }); },
    (r, i, c) => { const x = c.pk(r, [20, 25, 30, 40, 50]), y = c.pk(r, [10, 20, 30]); const net = (x - y) / 2;
      return c.buildMCQ({ r, stem: 'A dealer sells two cars at the same cost price, one at a profit of ' + x + '% and the other at a loss of ' + y + '%. What is his overall profit or loss percent?', right: net + '% profit', wrong: [net + '% loss', 'No profit no loss', ((x + y) / 2) + '% profit'], explanation: 'Overall = (' + x + ' - ' + y + ') / 2 = ' + net + '% profit.', steps: ['Let each CP = 100', 'SP1 = ' + (100 + x) + ', SP2 = ' + (100 - y), 'Total SP = ' + (200 + x - y) + ', Total CP = 200', 'Profit% = ' + (x - y) + ' / 200 x 100 = ' + net + '% profit'] }); },
];
TPLD.push(...[
    (r, i, c) => { const ab = c.pk(r, [[15, 12], [12, 10], [25, 20], [18, 15], [9, 6]]); const p = Math.round((ab[0] - ab[1]) * 100 / ab[1]);
      return c.buildMCQ({ r, stem: 'If the cost price of ' + ab[0] + ' articles equals the selling price of ' + ab[1] + ' articles, find the profit percentage.', right: p + '%', wrong: [(p + 5) + '%', (p - 5) + '%', '25%'], explanation: 'Profit% = ' + p + '%.', steps: ['CP of ' + ab[0] + ' = SP of ' + ab[1], 'Let CP of 1 = Rs.1', 'SP of ' + ab[1] + ' = ' + ab[0] + '  =>  SP of 1 = ' + ab[0] + ' / ' + ab[1], 'Profit% = (' + ab[0] + ' - ' + ab[1] + ') / ' + ab[1] + ' x 100 = ' + p + '%'] }); },
    (r, i, c) => { const d1 = c.pk(r, [10, 20, 25]), d2 = c.pk(r, [5, 10, 20]); const eq = d1 + d2 - d1 * d2 / 100;
      return c.buildMCQ({ r, stem: 'A shop offers successive discounts of ' + d1 + '% and ' + d2 + '%. What is the single equivalent discount?', right: eq + '%', wrong: [(d1 + d2) + '%', (eq + 3) + '%', (eq - 2) + '%'], explanation: eq + '%.', steps: ['Let MP = 100', 'After 1st: 100 - ' + d1 + ' = ' + (100 - d1), 'After 2nd: ' + (100 - d1) + ' x ' + (100 - d2) + ' / 100 = ' + ((100 - d1) * (100 - d2) / 100), 'Single discount = 100 - ' + ((100 - d1) * (100 - d2) / 100) + ' = ' + eq + '%'] }); },
    (r, i, c) => { const MP = c.ri(r, 6, 20) * 100, d = 20, p = c.pk(r, [25, 50, 60]); const CP = Math.round(MP * (100 - d) / 100 * 100 / (100 + p));
      return c.buildMCQ({ r, stem: 'The marked price of a fan is Rs.' + MP + '. A discount of ' + d + '% is given, yet the shopkeeper makes a profit of ' + p + '%. Find the cost price.', right: 'Rs.' + CP, wrong: ['Rs.' + (CP + 100), 'Rs.' + Math.round(CP * 1.2), 'Rs.' + (CP - 50)], explanation: 'CP = Rs.' + CP + '.', steps: ['SP = ' + MP + ' x ' + (100 - d) + ' / 100 = ' + Math.round(MP * (100 - d) / 100), 'SP = ' + (100 + p) + '% of CP', CP + ' = ' + Math.round(MP * (100 - d) / 100) + ' x 100 / ' + (100 + p), '   = Rs.' + CP] }); },
    (r, i, c) => { const pd = c.pk(r, [[40, 25, 5], [50, 20, 20], [60, 25, 20], [25, 20, 0]]); const p = Math.round(pd[0] - pd[1] - pd[0] * pd[1] / 100);
      return c.buildMCQ({ r, stem: 'A trader marks his goods ' + pd[0] + '% above cost price and allows a discount of ' + pd[1] + '%. Find his profit or loss percentage.', right: p === 0 ? 'No profit no loss' : p + '% profit', wrong: [(p + 5) + '% profit', '10% loss', p === 0 ? '5% profit' : 'No profit no loss'], explanation: 'Profit% = ' + p + '%.', steps: ['Let CP = 100', 'MP = 100 + ' + pd[0] + '% = ' + (100 + pd[0]), 'SP = ' + (100 + pd[0]) + ' x ' + (100 - pd[1]) + ' / 100 = ' + ((100 + pd[0]) * (100 - pd[1]) / 100), 'Profit% = ' + (((100 + pd[0]) * (100 - pd[1]) / 100) - 100) + '% = ' + p + '%'] }); },
    (r, i, c) => { const xy = c.pk(r, [[3, 1, 25], [4, 1, 20], [3, 2, 40]]);
      return c.buildMCQ({ r, stem: 'In a "buy ' + xy[0] + ' get ' + xy[1] + ' free" offer, what is the effective discount percentage?', right: xy[2] + '%', wrong: [(xy[2] + 5) + '%', (xy[2] - 5) + '%', (100 - xy[2]) + '%'], explanation: 'Discount = ' + xy[2] + '%.', steps: ['Pay for ' + xy[0] + ', get ' + (xy[0] + xy[1]), 'Discount = ' + xy[1] + ' / ' + (xy[0] + xy[1]) + ' x 100', '   = ' + xy[2] + '%'] }); },
]);
G['Profit, Loss & Discount'] = (r, i, c) => { return TPLD[i % TPLD.length](r, i, c); };

const TRP = [
    (r, i, c) => { const a = c.ri(r, 2, 9), b = c.ri(r, 2, 9), k = c.ri(r, 5, 40); const T = (a + b) * k; const sa = a * k;
      return c.buildMCQ({ r, stem: 'Rs.' + T + ' is divided between Amit and Bina in the ratio ' + a + ' : ' + b + '. How much does Amit get?', right: 'Rs.' + sa, wrong: ['Rs.' + (b * k), 'Rs.' + (T - sa + 10), 'Rs.' + Math.round(T / 2)], explanation: "Amit's share = Rs." + sa + '.', steps: ['Total parts = ' + a + ' + ' + b + ' = ' + (a + b), '1 part = ' + T + ' / ' + (a + b) + ' = ' + k, "Amit's share = " + a + ' x ' + k + ' = Rs.' + sa] }); },
    (r, i, c) => { const p = c.ri(r, 2, 6), q = c.ri(r, 2, 6), rr2 = c.ri(r, 2, 6), k = c.ri(r, 3, 20); const T = (p + q + rr2) * k; const sc = rr2 * k;
      return c.buildMCQ({ r, stem: 'If a : b = ' + p + ' : ' + q + ' and b : c = ' + q + ' : ' + rr2 + ', then out of Rs.' + T + ', what does c get?', right: 'Rs.' + sc, wrong: ['Rs.' + (p * k), 'Rs.' + (q * k), 'Rs.' + (sc + k)], explanation: 'c gets Rs.' + sc + '.', steps: ['a : b : c = ' + p + ' : ' + q + ' : ' + rr2, 'Total parts = ' + (p + q + rr2), '1 part = ' + T + ' / ' + (p + q + rr2) + ' = ' + k, 'c = ' + rr2 + ' x ' + k + ' = Rs.' + sc] }); },
    (r, i, c) => { const a = c.pk(r, [3, 4, 5]), b = c.pk(r, [6, 7, 9]); const x = c.ri(r, 4, 12), k = c.ri(r, 4, 10); const gcd2 = (u, v) => v ? gcd2(v, u % v) : u; const nA = a * x + k, nB = b * x + k; const g2 = gcd2(nA, nB); const nc = nA / g2, nd = nB / g2;
      return c.buildMCQ({ r, stem: 'The ages of two persons are in the ratio ' + a + ' : ' + b + '. After ' + k + ' years, their ages will be in the ratio ' + nc + ' : ' + nd + '. What is the present age of the elder person?', right: (b * x) + ' years', wrong: [(a * x) + ' years', (b * x + k) + ' years', (b * x + 5) + ' years'], explanation: 'Elder is ' + (b * x) + ' years old now.', steps: ['Let ages = ' + a + 'x and ' + b + 'x', 'After ' + k + ' years: (' + a + 'x + ' + k + ') / (' + b + 'x + ' + k + ') = ' + nc + ' / ' + nd, 'Solving: x = ' + x, 'Elder = ' + b + ' x ' + x + ' = ' + (b * x) + ' years'] }); },
    (r, i, c) => { const x = c.ri(r, 2, 6), y = c.ri(r, 2, 6), z = c.ri(r, 2, 6), m = c.ri(r, 2, 6); const total = Math.round(m * (25 * x + 50 * y + 100 * z) / 100);
      return c.buildMCQ({ r, stem: 'A piggy bank has 25 paise, 50 paise and Re.1 coins in the ratio ' + x + ' : ' + y + ' : ' + z + '. If the number of 25 paise coins is ' + (m * x) + ', what is the total amount (in Rs.)?', right: 'Rs.' + total, wrong: ['Rs.' + (total + 2), 'Rs.' + (total + 1), 'Rs.' + (total - 1)], explanation: 'Total = Rs.' + total + '.', steps: ['25p coins = ' + (m * x) + ', so multiplier = ' + m, 'Counts: 25p = ' + (m * x) + ', 50p = ' + (m * y) + ', Re.1 = ' + (m * z), 'Value = ' + (m * x) + ' x 0.25 + ' + (m * y) + ' x 0.5 + ' + (m * z) + ' x 1', '   = ' + (m * x * 0.25) + ' + ' + (m * y * 0.5) + ' + ' + (m * z) + ' = Rs.' + total] }); },
    (r, i, c) => { const a = c.pk(r, [2, 3, 4, 5]), b = c.pk(r, [1, 2, 3, 4]); const k = c.ri(r, 4, 12); const M = a * k, W = b * k, add = c.ri(r, 2, 8); const g2 = (u, v) => v ? g2(v, u % v) : u; const Wn = W + add; const g3 = g2(M, Wn);
      return c.buildMCQ({ r, stem: 'A vessel contains milk and water in the ratio ' + a + ' : ' + b + ' (' + (a + b) * k + ' litres mixture). If ' + add + ' litres of water is added, what is the new ratio of milk to water?', right: (M / g3) + ' : ' + (Wn / g3), wrong: [a + ' : ' + (b + add), a + ' : ' + b, (M / g3 + 1) + ' : ' + (Wn / g3)], explanation: 'New ratio = ' + (M / g3) + ' : ' + (Wn / g3) + '.', steps: ['Milk = ' + a + ' x ' + k + ' = ' + M + ' L, Water = ' + b + ' x ' + k + ' = ' + W + ' L', 'After adding ' + add + ' L water: Water = ' + W + ' + ' + add + ' = ' + Wn, 'New ratio = ' + M + ' : ' + Wn + ' = ' + (M / g3) + ' : ' + (Wn / g3)] }); },
    (r, i, c) => { const a = c.ri(r, 2, 7), b = c.ri(r, a + 1, 10); const D = c.ri(r, 3, 15) * (b - a); const sm = a * D / (b - a);
      return c.buildMCQ({ r, stem: 'Two numbers are in the ratio ' + a + ' : ' + b + ' and their difference is ' + D + '. Find the smaller number.', right: String(sm), wrong: [String(sm + D), String(D), String(Math.round(D / 2))], explanation: 'Smaller = ' + sm + '.', steps: ['Let numbers = ' + a + 'x and ' + b + 'x', 'Difference: ' + b + 'x - ' + a + 'x = ' + (b - a) + 'x = ' + D, 'x = ' + D + ' / ' + (b - a) + ' = ' + (D / (b - a)), 'Smaller = ' + a + 'x = ' + sm] }); },
];
TRP.push(...[
    (r, i, c) => { const s1 = c.ri(r, 2, 5); let s2 = c.ri(r, 2, 5); if (s1 === s2) { s2 = s1 + 2; } const D = c.ri(r, 20, 60); const k = D / Math.abs(s1 - s2);
      return c.buildMCQ({ r, stem: 'The speeds of a bus and a car are in the ratio ' + s1 + ' : ' + s2 + '. If the car travels ' + D + ' km/h faster than the bus, find the speed of the bus (km/h).', right: String(Math.round(s1 * k)), wrong: [String(Math.round(s2 * k)), String(Math.round(D / (s1 + s2))), String(Math.round(s1 * k + 10))], explanation: 'Bus speed = ' + Math.round(s1 * k) + ' km/h.', steps: ['Let speeds = ' + s1 + 'x and ' + s2 + 'x km/h', 'Difference: ' + s2 + 'x - ' + s1 + 'x = ' + (s2 - s1) + 'x = ' + D, 'x = ' + k, 'Bus speed = ' + s1 + ' x ' + k + ' = ' + Math.round(s1 * k) + ' km/h'] }); },
    (r, i, c) => { const a = c.ri(r, 2, 5), b = c.ri(r, 2, 5), d = c.ri(r, 2, 5); const k = c.ri(r, 5, 15); const T = (a + b + d) * k;
      return c.buildMCQ({ r, stem: 'Divide Rs.' + T + ' among X, Y and Z in the ratio ' + a + ' : ' + b + ' : ' + d + '. What is the difference between the shares of Y and Z?', right: 'Rs.' + Math.abs(b - d) * k, wrong: ['Rs.' + Math.abs(a - b) * k, 'Rs.' + k, 'Rs.' + (Math.abs(b - d) * k + k)], explanation: 'Difference = Rs.' + (Math.abs(b - d) * k) + '.', steps: ['Total parts = ' + (a + b + d), '1 part = ' + T + ' / ' + (a + b + d) + ' = ' + k, 'Y = ' + b * k + ', Z = ' + d * k, 'Difference = |' + (b * k) + ' - ' + (d * k) + '| = Rs.' + (Math.abs(b - d) * k)] }); },
    (r, i, c) => { const m = c.ri(r, 3, 7), w = c.ri(r, 2, 6); const M = m * c.ri(r, 5, 12), W = w * c.ri(r, 5, 12);
      return c.buildMCQ({ r, stem: 'The ratio of boys to girls in a school is ' + m + ' : ' + w + '. If there are ' + M + ' boys, how many girls are there?', right: String(W), wrong: [String(M + w), String(m * w), String(W + 10)], explanation: 'Girls = ' + W + '.', steps: ['Boys / Girls = ' + m + ' / ' + w, M + ' / G = ' + m + ' / ' + w, 'G = ' + M + ' x ' + w + ' / ' + m, '   = ' + W] }); },
    (r, i, c) => { const a = c.ri(r, 2, 6), b = c.ri(r, 2, 6); const mean = c.ri(r, 10, 40); const g = (u, v) => v ? g(v, u % v) : u; const A = mean * 2 * a / (a + b), B = mean * 2 * b / (a + b); const g4 = g(Math.round(A), Math.round(B));
      return c.buildMCQ({ r, stem: 'Two numbers are in the ratio ' + a + ' : ' + b + ' and their average is ' + mean + '. Find the larger number.', right: String(Math.round(mean * 2 * Math.max(a, b) / (a + b))), wrong: [String(Math.round(mean * 2 * Math.min(a, b) / (a + b))), String(mean), String(Math.round(mean * 2 * Math.max(a, b) / (a + b)) + 5)], explanation: 'Larger = ' + Math.round(mean * 2 * Math.max(a, b) / (a + b)) + '.', steps: ['Sum = ' + mean + ' x 2 = ' + (2 * mean), 'Numbers = ' + a + 'x and ' + b + 'x  =>  ' + (a + b) + 'x = ' + (2 * mean), 'x = ' + (2 * mean / (a + b)), 'Larger = ' + Math.max(a, b) + ' x ' + (2 * mean / (a + b)) + ' = ' + Math.round(mean * 2 * Math.max(a, b) / (a + b))] }); },
    (r, i, c) => { const a = c.ri(r, 2, 8), b = c.ri(r, 2, 8); const k = c.ri(r, 3, 12); const W1 = a * k, W2 = b * k; const rem = c.ri(r, 1, Math.min(W1, W2) - 1); const g2 = (u, v) => v ? g2(v, u % v) : u; const nA = W1 - rem, nB = W2 - rem; const g3 = g2(nA, nB);
      return c.buildMCQ({ r, stem: 'Two friends bought shares in the ratio ' + a + ' : ' + b + ' (' + (W1 + W2) + ' shares total). If ' + rem + ' shares are taken away from each, what is the new ratio of their shares?', right: (nA / g3) + ' : ' + (nB / g3), wrong: [a + ' : ' + b, (nA / g3) + ' : ' + (nB / g3 + 1), ((nA / g3) - 1) + ' : ' + (nB / g3)], explanation: 'New ratio = ' + (nA / g3) + ' : ' + (nB / g3) + '.', steps: ['Shares = ' + a + 'x ' + b + 'x where x = ' + k, 'Friend 1 = ' + W1 + ', Friend 2 = ' + W2, 'After removing ' + rem + ' each: ' + nA + ' and ' + nB, 'New ratio = ' + (nA / g3) + ' : ' + (nB / g3)] }); },
]);
G['Ratio & Proportion'] = (r, i, c) => { return TRP[i % TRP.length](r, i, c); };

const TAVG = [
    (r, i, c) => { const n = c.ri(r, 4, 6), base = c.ri(r, 10, 30); const nums = []; for (let j = 0; j < n; j++) nums.push(base + j * c.ri(r, 1, 5)); const sum = nums.reduce((a, b) => a + b, 0); const av = Math.round(sum / n);
      return c.buildMCQ({ r, stem: 'Find the average of the numbers: ' + nums.join(', ') + '.', right: String(av), wrong: [String(av + 2), String(Math.round(sum / (n + 1))), String(av - 3)], explanation: 'Average = ' + av + '.', steps: ['Sum = ' + nums.join(' + ') + ' = ' + sum, 'Count = ' + n, 'Average = ' + sum + ' / ' + n + ' = ' + av] }); },
    (r, i, c) => { const av = c.ri(r, 15, 50), n = c.ri(r, 4, 9); const S = av * n; const x = c.ri(r, 20, 80);
      return c.buildMCQ({ r, stem: 'The average of ' + n + ' numbers is ' + av + '. What is their sum?', right: String(S), wrong: [String(av * (n + 1)), String(S + n), String(av + n)], explanation: 'Sum = ' + S + '.', steps: ['Sum = Average x Count', '   = ' + av + ' x ' + n + ' = ' + S] }); },
    (r, i, c) => { const av = c.ri(r, 20, 40), n = c.ri(r, 4, 8), inc = c.ri(r, 2, 8);
      return c.buildMCQ({ r, stem: 'The average age of ' + n + ' students is ' + av + ' years. If a new student joins and the average increases by ' + inc + ' years, what is the age of the new student?', right: String(av + inc * (n + 1)), wrong: [String(av + inc), String(av + inc * n), String(2 * av)], explanation: 'New student is ' + (av + inc * (n + 1)) + ' years old.', steps: ['Old total = ' + av + ' x ' + n + ' = ' + (av * n), 'New total = (' + (av + inc) + ') x ' + (n + 1) + ' = ' + ((av + inc) * (n + 1)), 'New student = ' + ((av + inc) * (n + 1)) + ' - ' + (av * n), '   = ' + (av + inc * (n + 1)) + ' years'] }); },
    (r, i, c) => { const a = c.ri(r, 10, 30), b = c.ri(r, 31, 60), m = c.ri(r, 2, 6), n = c.ri(r, 2, 6); const av = Math.round((m * a + n * b) / (m + n));
      return c.buildMCQ({ r, stem: 'The average weight of ' + m + ' boys is ' + a + ' kg and that of ' + n + ' girls is ' + b + ' kg. Find the average weight of the whole group (in kg, rounded).', right: String(av), wrong: [String(Math.round((a + b) / 2)), String(av + 2), String(av - 2)], explanation: 'Group average = ' + av + ' kg.', steps: ['Total weight = ' + m + ' x ' + a + ' + ' + n + ' x ' + b, '   = ' + (m * a) + ' + ' + (n * b) + ' = ' + (m * a + n * b) + ' kg', 'Total people = ' + m + ' + ' + n + ' = ' + (m + n), 'Average = ' + (m * a + n * b) + ' / ' + (m + n) + ' = ' + av + ' kg'] }); },
    (r, i, c) => { const av5 = c.ri(r, 20, 40), x = c.ri(r, 15, 60);
      return c.buildMCQ({ r, stem: 'The average of 5 numbers is ' + av5 + '. If one number ' + x + ' is excluded, what is the average of the remaining 4 numbers?', right: String(Math.round((5 * av5 - x) / 4)), wrong: [String(av5), String(Math.round((5 * av5 - x) / 5)), String(Math.round((5 * av5 - x) / 4) + 2)], explanation: 'New average = ' + Math.round((5 * av5 - x) / 4) + '.', steps: ['Sum of 5 = ' + av5 + ' x 5 = ' + (5 * av5), 'Remove ' + x + ': Sum = ' + (5 * av5) + ' - ' + x + ' = ' + (5 * av5 - x), 'Average of 4 = ' + (5 * av5 - x) + ' / 4 = ' + Math.round((5 * av5 - x) / 4)] }); },
    (r, i, c) => { const T = c.ri(r, 20, 40), T2 = c.ri(r, 41, 60), n1 = c.ri(r, 3, 6), n2 = c.ri(r, 3, 6);
      return c.buildMCQ({ r, stem: 'In a class of ' + (n1 + n2) + ' students, the average height of ' + n1 + ' students is ' + T + ' cm and the remaining ' + n2 + ' students have average height ' + T2 + ' cm. What is the average height of the class (cm, rounded)?', right: String(Math.round((n1 * T + n2 * T2) / (n1 + n2))), wrong: [String(Math.round((T + T2) / 2)), String(Math.round((n1 * T + n2 * T2) / (n1 + n2)) + 1), String(T)], explanation: 'Class average = ' + Math.round((n1 * T + n2 * T2) / (n1 + n2)) + ' cm.', steps: ['Total height = ' + n1 + ' x ' + T + ' + ' + n2 + ' x ' + T2 + ' = ' + (n1 * T + n2 * T2) + ' cm', 'Average = ' + (n1 * T + n2 * T2) + ' / ' + (n1 + n2), '   = ' + Math.round((n1 * T + n2 * T2) / (n1 + n2)) + ' cm'] }); },
    (r, i, c) => { const av = c.ri(r, 30, 60), n = c.ri(r, 5, 10), inc = c.ri(r, 1, 5);
      return c.buildMCQ({ r, stem: 'The average of ' + n + ' numbers is ' + av + '. If each number is increased by ' + inc + ', what is the new average?', right: String(av + inc), wrong: [String(av), String(av + inc * n), String(av * inc)], explanation: 'New average = ' + (av + inc) + '.', steps: ['Old sum = ' + av + ' x ' + n + ' = ' + (av * n), 'Each + ' + inc + ': New sum = ' + (av * n) + ' + ' + (inc * n) + ' = ' + (av * n + inc * n), 'New average = ' + (av * n + inc * n) + ' / ' + n + ' = ' + (av + inc)] }); },
];
TAVG.push(...[
    (r, i, c) => { const inn = c.ri(r, 5, 9), av = c.ri(r, 30, 60); const runs = av * (inn - 1) + c.ri(r, 5, 60) + inn; const nav = Math.round((av * (inn - 1) + runs) / inn);
      return c.buildMCQ({ r, stem: 'A batsman\'s average after ' + (inn - 1) + ' innings is ' + av + ' runs. He scores ' + runs + ' runs in his ' + inn + 'th innings. What is his new average (rounded)?', right: String(nav), wrong: [String(av), String(nav + 1), String(Math.round(runs / inn))], explanation: 'New average = ' + nav + '.', steps: ['Runs after ' + (inn - 1) + ' innings = ' + av + ' x ' + (inn - 1) + ' = ' + (av * (inn - 1)), 'After ' + inn + ' innings: ' + (av * (inn - 1)) + ' + ' + runs + ' = ' + (av * (inn - 1) + runs), 'New average = ' + (av * (inn - 1) + runs) + ' / ' + inn + ' = ' + nav] }); },
    (r, i, c) => { const n = c.ri(r, 8, 15), av = c.ri(r, 25, 50); const wrong = c.ri(r, 10, 30), right = c.ri(r, 40, 80); const nav = Math.round((av * n - wrong + right) / n);
      return c.buildMCQ({ r, stem: 'The average of ' + n + ' results is ' + av + '. Later it was found that a result ' + wrong + ' was wrongly copied as ' + right + '. What is the correct average?', right: String(nav), wrong: [String(av), String(nav + 1), String(nav - 1)], explanation: 'Correct average = ' + nav + '.', steps: ['Wrong total = ' + av + ' x ' + n + ' = ' + (av * n), 'Correction = ' + wrong + ' - ' + right + ' = ' + (wrong - right), 'Correct total = ' + (av * n) + ' + (' + (wrong - right) + ') = ' + (av * n - wrong + right), 'Correct average = ' + (av * n - wrong + right) + ' / ' + n + ' = ' + nav] }); },
    (r, i, c) => { const n = c.ri(r, 4, 8), start = c.ri(r, 2, 10) * 2;
      return c.buildMCQ({ r, stem: 'What is the average of the first ' + n + ' even numbers starting from ' + start + '?', right: String(start + n - 1), wrong: [String(start + n), String(start + 2 * n), String(start)], explanation: 'Average = ' + (start + n - 1) + '.', steps: ['Numbers: ' + start + ', ' + (start + 2) + ', ..., ' + (start + 2 * (n - 1)), 'Count = ' + n, 'Sum = n x (first + last) / 2 = ' + n + ' x (' + start + ' + ' + (start + 2 * (n - 1)) + ') / 2', 'Average = Sum / n = (' + start + ' + ' + (start + 2 * (n - 1)) + ') / 2 = ' + (start + n - 1)] }); },
    (r, i, c) => { const n = c.ri(r, 5, 12); const S = n * n;
      return c.buildMCQ({ r, stem: 'What is the average of the first ' + n + ' odd natural numbers (1, 3, 5, ...)?', right: String(n), wrong: [String(n + 1), String(2 * n - 1), String(n * n)], explanation: 'Average = ' + n + '.', steps: ['First ' + n + ' odd numbers: 1, 3, ..., ' + (2 * n - 1), 'Sum of first n odd numbers = n^2 = ' + S, 'Average = ' + S + ' / ' + n + ' = ' + n] }); },
    (r, i, c) => { const n = c.ri(r, 5, 9), av = c.ri(r, 30, 60); const x = c.ri(r, 10, 90), y = c.ri(r, 10, 90); const nav = Math.round((av * n - x + y) / n);
      return c.buildMCQ({ r, stem: 'The average of ' + n + ' numbers is ' + av + '. A number ' + x + ' is replaced by a new number ' + y + '. What is the new average?', right: String(nav), wrong: [String(av), String(nav + 2), String(Math.round((av * n + y) / n))], explanation: 'New average = ' + nav + '.', steps: ['Old sum = ' + av + ' x ' + n + ' = ' + (av * n), 'New sum = ' + (av * n) + ' - ' + x + ' + ' + y + ' = ' + (av * n - x + y), 'New average = ' + (av * n - x + y) + ' / ' + n + ' = ' + nav] }); },
]);
G['Averages'] = (r, i, c) => { return TAVG[i % TAVG.length](r, i, c); };

const TTSD = [
    (r, i, c) => { const S = c.pk(r, [40, 45, 50, 60, 72, 90]), T = c.pk(r, [2, 3, 4, 5]); const D = S * T;
      return c.buildMCQ({ r, stem: 'A train covers a distance of ' + D + ' km in ' + T + ' hours. What is its speed in km/h?', right: String(S), wrong: [String(S + 10), String(Math.round(D / (T + 1))), String(S - 5)], explanation: 'Speed = ' + S + ' km/h.', steps: ['Speed = Distance / Time', '   = ' + D + ' / ' + T + ' = ' + S + ' km/h'] }); },
    (r, i, c) => { const S = c.pk(r, [40, 50, 60, 80]), T = c.pk(r, [2, 3, 4, 6]); const D = S * T;
      return c.buildMCQ({ r, stem: 'A bus travels at ' + S + ' km/h. How much distance (km) will it cover in ' + T + ' hours?', right: String(D), wrong: [String(S + T), String(D + S), String(Math.round(D / 2))], explanation: 'Distance = ' + D + ' km.', steps: ['Distance = Speed x Time', '   = ' + S + ' x ' + T + ' = ' + D + ' km'] }); },
    (r, i, c) => { const S = c.pk(r, [40, 45, 50, 60, 75]), D = c.ri(r, 4, 20) * S;
      return c.buildMCQ({ r, stem: 'A car covers ' + D + ' km at a speed of ' + S + ' km/h. How much time (hours) does the journey take?', right: String(D / S), wrong: [String(D / S + 1), String(Math.round(S * (D / S))), String(D / S - 1)], explanation: 'Time = ' + (D / S) + ' hours.', steps: ['Time = Distance / Speed', '   = ' + D + ' / ' + S + ' = ' + (D / S) + ' hours'] }); },
    (r, i, c) => { const a = c.ri(r, 4, 9) * 10, b = c.ri(r, 4, 9) * 10; const D = c.ri(r, 2, 9) * (a + b);
      return c.buildMCQ({ r, stem: 'Two trains start towards each other at the same time from stations ' + D + ' km apart with speeds ' + a + ' km/h and ' + b + ' km/h. After how many hours will they meet?', right: String(D / (a + b)), wrong: [String(D / (a + b) + 1), String(Math.round(D / Math.max(a, b))), String(D / (a + b) - 1)], explanation: 'They meet after ' + (D / (a + b)) + ' hours.', steps: ['Relative speed = ' + a + ' + ' + b + ' = ' + (a + b) + ' km/h', 'Time = Distance / Relative speed', '   = ' + D + ' / ' + (a + b) + ' = ' + (D / (a + b)) + ' hours'] }); },
    (r, i, c) => { const s = c.pk(r, [3, 4, 5, 6, 8, 10, 12]), t = c.pk(r, [2, 3, 4]); const st = s * 5 / 18; const L = Math.round(st * t);
      return c.buildMCQ({ r, stem: 'A train ' + L + ' m long is running at ' + s + ' km/h. In how many seconds will it cross a pole?', right: String(t), wrong: [String(t + 2), String(t + 5), String(2 * t)], explanation: 'Time = ' + t + ' seconds.', steps: ['Speed = ' + s + ' km/h = ' + s + ' x 5/18 = ' + st + ' m/s', 'Crossing a pole: Distance = train length = ' + L + ' m', 'Time = ' + L + ' / ' + st + ' = ' + t + ' seconds'] }); },
    (r, i, c) => { const s = c.pk(r, [36, 54, 72, 90]), t = c.pk(r, [8, 10, 12, 15, 20]); const st = s * 5 / 18; const L = Math.round(st * t / 10) * 10; const tm = Math.round(L / st);
      return c.buildMCQ({ r, stem: 'A ' + L + ' m long train crosses a pole in ' + tm + ' seconds. What is its speed in km/h?', right: String(s), wrong: [String(s + 9), String(s - 9), String(2 * s)], explanation: 'Speed = ' + s + ' km/h.', steps: ['Speed = ' + L + ' / ' + tm + ' = ' + st + ' m/s', 'km/h = ' + st + ' x 18/5', '   = ' + s + ' km/h'] }); },
    (r, i, c) => { const T2 = c.pk(r, [6, 12, 18, 24, 30]); const D = T2 / 2;
      return c.buildMCQ({ r, stem: 'Walking at 5 km/h, a student reaches school ' + T2 + ' minutes late. Walking at 6 km/h, he reaches on time. What is the distance to the school (km)?', right: String(D), wrong: [String(D + 1), String(D * 2), String(D - 0.5)], explanation: 'Distance = ' + D + ' km.', steps: ['Let distance = D km', 'Time at 5 km/h - Time at 6 km/h = ' + T2 + ' min = ' + (T2 / 60) + ' h', 'D/5 - D/6 = ' + (T2 / 60), 'D / 30 = ' + (T2 / 60), 'D = 30 x ' + (T2 / 60) + ' = ' + D + ' km'] }); },
];
TTSD.push(...[
    (r, i, c) => { const b = c.ri(r, 6, 14), s = c.ri(r, 2, 5);
      return c.buildMCQ({ r, stem: 'A boat\'s speed in still water is ' + b + ' km/h and the speed of the stream is ' + s + ' km/h. What is the speed of the boat downstream?', right: (b + s) + ' km/h', wrong: [(b - s) + ' km/h', b + ' km/h', (b * s) + ' km/h'], explanation: 'Downstream speed = ' + (b + s) + ' km/h.', steps: ['Downstream = boat + stream', '   = ' + b + ' + ' + s + ' = ' + (b + s) + ' km/h'] }); },
    (r, i, c) => { const b = c.ri(r, 6, 14), s = c.ri(r, 2, 5); const D = (b + s) * c.ri(r, 2, 4);
      return c.buildMCQ({ r, stem: 'A boat rows at ' + (b - s) + ' km/h upstream, while its downstream speed is ' + (b + s) + ' km/h (stream ' + s + ' km/h). Find speed in still water.', right: b + ' km/h', wrong: [(b + s) + ' km/h', (b - s) + ' km/h', (b + 2 * s) + ' km/h'], explanation: 'Still water speed = ' + b + ' km/h.', steps: ['u = ' + (b - s) + ', v = ' + (b + s), 'Still water speed = (u + v) / 2', '   = (' + (b - s) + ' + ' + (b + s) + ') / 2 = ' + b + ' km/h'] }); },
    (r, i, c) => { const a = c.pk(r, [30, 40, 60]), b2 = c.pk(r, [20, 30, 60]); const av = Math.round(2 * a * b2 / (a + b2));
      return c.buildMCQ({ r, stem: 'A man goes to a city at ' + a + ' km/h and returns at ' + b2 + ' km/h. What is his average speed for the whole journey (km/h, rounded)?', right: String(av), wrong: [String(Math.round((a + b2) / 2)), String(av + 2), String(a + b2)], explanation: 'Average speed = ' + av + ' km/h.', steps: ['Equal distances: average = 2ab / (a + b)', '   = 2 x ' + a + ' x ' + b2 + ' / (' + a + ' + ' + b2 + ')', '   = ' + (2 * a * b2) + ' / ' + (a + b2) + ' = ' + av + ' km/h'] }); },
    (r, i, c) => { const s = c.pk(r, [36, 54, 72]), L = c.pk(r, [100, 120, 150, 200]), P = c.pk(r, [100, 150, 200, 250]); const st = s * 5 / 18; const tm = Math.round((L + P) / st);
      return c.buildMCQ({ r, stem: 'A train ' + L + ' m long running at ' + s + ' km/h crosses a platform ' + P + ' m long in how many seconds (rounded)?', right: String(tm), wrong: [String(tm + 3), String(Math.round(L / st)), String(tm + 6)], explanation: 'Time = ' + tm + ' seconds.', steps: ['Speed = ' + s + ' x 5/18 = ' + st + ' m/s', 'Distance = train + platform = ' + L + ' + ' + P + ' = ' + (L + P) + ' m', 'Time = ' + (L + P) + ' / ' + st + ' = ' + tm + ' seconds'] }); },
    (r, i, c) => { const L1 = c.pk(r, [120, 150, 200]), L2 = c.pk(r, [130, 180, 250]); const rel = c.pk(r, [20, 25, 30]); const tm = Math.round((L1 + L2) / rel);
      return c.buildMCQ({ r, stem: 'Two trains of lengths ' + L1 + ' m and ' + L2 + ' m run in opposite directions at a relative speed of ' + rel + ' m/s. In how many seconds do they completely cross each other?', right: String(tm), wrong: [String(tm + 2), String(Math.round(L1 / rel)), String(tm + 5)], explanation: 'Time = ' + tm + ' seconds.', steps: ['Total length = ' + L1 + ' + ' + L2 + ' = ' + (L1 + L2) + ' m', 'Relative speed (opposite) = ' + rel + ' m/s', 'Time = ' + (L1 + L2) + ' / ' + rel + ' = ' + tm + ' seconds'] }); },
    (r, i, c) => { const ms = c.pk(r, [5, 10, 15, 20, 25]); const kmh = ms * 18 / 5;
      return c.buildMCQ({ r, stem: 'Convert a speed of ' + ms + ' m/s into km/h.', right: String(kmh), wrong: [String(ms * 5 / 18), String(kmh + 6), String(kmh - 4)], explanation: 'Speed = ' + kmh + ' km/h.', steps: ['1 m/s = 18/5 km/h', kmh + ' = ' + ms + ' x 18 / 5', '   = ' + kmh + ' km/h'] }); },
]);
G['Time, Speed & Distance'] = (r, i, c) => { return TTSD[i % TTSD.length](r, i, c); };

const TTW = [
    (r, i, c) => { const a = c.pk(r, [6, 8, 10, 12, 15, 20, 24]), b = c.pk(r, [12, 15, 20, 24, 30, 40]); const t = Math.round(a * b / (a + b));
      return c.buildMCQ({ r, stem: 'A can finish a work in ' + a + ' days and B can finish the same work in ' + b + ' days. Working together, in how many days will they finish the work (rounded)?', right: String(t), wrong: [String(t + 2), String(Math.round((a + b) / 2)), String(t + 1)], explanation: 'Together = ' + t + ' days (approx).', steps: ["A's 1 day work = 1/" + a + ", B's 1 day work = 1/" + b, 'Together 1 day = 1/' + a + ' + 1/' + b + ' = ' + (a + b) + '/' + (a * b), 'Time = ' + (a * b) + ' / ' + (a + b) + ' = ' + t + ' days'] }); },
    (r, i, c) => { const a = c.pk(r, [12, 15, 20, 24, 30]), t = c.pk(r, [6, 8, 10, 12]); const b = Math.round(a * t / (a - t));
      return c.buildMCQ({ r, stem: 'A and B together can do a work in ' + t + ' days. A alone can do it in ' + a + ' days. In how many days can B alone do the work?', right: String(b), wrong: [String(b + 4), String(a + t), String(b - 3)], explanation: 'B alone = ' + b + ' days.', steps: ['1/A + 1/B = 1/' + t, '1/B = 1/' + t + ' - 1/' + a + ' = ' + (a - t) + '/' + (a * t), 'B = ' + (a * t) + ' / ' + (a - t) + ' = ' + b + ' days'] }); },
    (r, i, c) => { const M1 = c.ri(r, 4, 12), D1 = c.ri(r, 6, 20), M2 = c.ri(r, 4, 15); const D2 = Math.round(M1 * D1 / M2);
      return c.buildMCQ({ r, stem: 'If ' + M1 + ' men can complete a piece of work in ' + D1 + ' days, how many days will ' + M2 + ' men take to complete the same work?', right: String(D2), wrong: [String(D2 + 3), String(M1 * D1 / M2 + 5), String(D1)], explanation: 'Days = ' + D2 + '.', steps: ['Total work = ' + M1 + ' x ' + D1 + ' = ' + (M1 * D1) + ' man-days', 'With ' + M2 + ' men: Days = ' + (M1 * D1) + ' / ' + M2, '   = ' + D2 + ' days'] }); },
    (r, i, c) => { const a = c.pk(r, [6, 8, 10, 12]), b = c.pk(r, [12, 15, 20, 24]); const t = Math.round(a * b / (b - a));
      return c.buildMCQ({ r, stem: 'A pipe can fill a tank in ' + a + ' hours, while another pipe can empty the full tank in ' + b + ' hours. If both pipes are opened together, in how many hours will the empty tank be filled?', right: String(t), wrong: [String(t + 2), String(a + b), String(t + 1)], explanation: 'Tank fills in ' + t + ' hours.', steps: ['Fill rate = 1/' + a + ', Empty rate = 1/' + b, 'Net rate = 1/' + a + ' - 1/' + b + ' = ' + (b - a) + '/' + (a * b), 'Time = ' + (a * b) + ' / ' + (b - a) + ' = ' + t + ' hours'] }); },
    (r, i, c) => { const a = c.pk(r, [12, 15, 20, 30]), b = c.pk(r, [15, 20, 24, 30]); const k = c.ri(r, 3, 7); const rem = 1 - k / a; const days = Math.round(rem * b);
      return c.buildMCQ({ r, stem: 'A can do a work in ' + a + ' days and B in ' + b + ' days. A works alone for ' + k + ' days and then leaves. In how many days will B finish the remaining work?', right: String(days), wrong: [String(days + 2), String(b), String(Math.round(days / 2))], explanation: 'B needs ' + days + ' more days.', steps: ["A's work in " + k + ' days = ' + k + '/' + a, 'Remaining = 1 - ' + k + '/' + a + ' = ' + rem, "B's time = " + rem + ' x ' + b + ' = ' + days + ' days'] }); },
    (r, i, c) => { const e = c.pk(r, [2, 3]); const b = c.pk(r, [12, 15, 18, 24, 30]); const a = Math.round(b / e); const t = Math.round(a * b / (a + b));
      return c.buildMCQ({ r, stem: 'A is ' + e + ' times as efficient as B and takes ' + a + ' days less than B to finish a piece of work. In how many days can they finish the work together?', right: String(t), wrong: [String(t + 2), String(b), String(a)], explanation: 'Together = ' + t + ' days.', steps: ['A = ' + a + ' days, B = ' + a + ' x ' + e + ' = ' + b + ' days', 'Check: ' + b + ' - ' + a + ' = ' + (b - a) + ' days less', 'Together = ' + a + ' x ' + b + ' / (' + a + ' + ' + b + ') = ' + t + ' days'] }); },
    (r, i, c) => { const n = c.ri(r, 6, 12), d = c.ri(r, 10, 30); const W = n * d; const n2 = n + c.ri(r, 2, 6);
      return c.buildMCQ({ r, stem: 'A work of ' + W + ' units is done by ' + n + ' workers in ' + d + ' days, each doing 1 unit per day. How many days will ' + n2 + ' workers take to finish the same work?', right: String(Math.round(W / n2)), wrong: [String(d), String(Math.round(W / n2) + 2), String(Math.round(W / n2) - 1)], explanation: 'Days = ' + Math.round(W / n2) + '.', steps: ['Total work = ' + W + ' units', 'With ' + n2 + ' workers: ' + W + ' / ' + n2, '   = ' + Math.round(W / n2) + ' days'] }); },
];
TTW.push(...[
    (r, i, c) => { const T = c.pk(r, [6, 8, 10, 12]), X = c.pk(r, [10, 15, 20, 24]); const C = Math.round(1 / (1 / T - 1 / X));
      return c.buildMCQ({ r, stem: 'A, B and C together finish a work in ' + T + ' days. A and B together finish it in ' + X + ' days. In how many days can C alone finish the work?', right: String(C), wrong: [String(C + 5), String(X), String(T)], explanation: 'C alone = ' + C + ' days.', steps: ['(A+B+C) 1 day = 1/' + T, '(A+B) 1 day = 1/' + X, "C's 1 day = 1/" + T + ' - 1/' + X + ' = 1/' + C, 'C alone = ' + C + ' days'] }); },
    (r, i, c) => { const a = c.pk(r, [10, 12, 15, 20]), b = c.pk(r, [15, 20, 24, 30]); const W = c.ri(r, 6, 15) * 100; const share = Math.round(W * b / (a + b));
      return c.buildMCQ({ r, stem: 'A can complete a work in ' + a + ' days and B in ' + b + ' days. They complete the work together and receive Rs.' + W + '. What is A\'s share?', right: 'Rs.' + share, wrong: ['Rs.' + (W - share), 'Rs.' + Math.round(W / 2), 'Rs.' + (share + 100)], explanation: "A's share = Rs." + share + '.', steps: ['Work ratio A : B = 1/' + a + ' : 1/' + b + ' = ' + b + ' : ' + a, "A's share = " + b + ' / ' + (a + b) + ' x ' + W, '   = Rs.' + share] }); },
    (r, i, c) => { const t = c.pk(r, [4, 6, 8, 10]), t2 = c.pk(r, [12, 15, 20, 24]); const L = Math.round(t * t2 / (t2 - t));
      return c.buildMCQ({ r, stem: 'A tank is filled in ' + t + ' hours but due to a leak it takes ' + t2 + ' hours to fill. In how many hours would the leak empty the full tank?', right: String(L), wrong: [String(L + 6), String(t2), String(L + 12)], explanation: 'Leak empties in ' + L + ' hours.', steps: ['Fill rate without leak = 1/' + t, 'Net rate with leak = 1/' + t2, "Leak's rate = 1/" + t + ' - 1/' + t2 + ' = 1/' + L, 'Leak empties full tank in ' + L + ' hours'] }); },
    (r, i, c) => { const e = c.pk(r, [2, 3, 4]); const t = c.pk(r, [8, 12, 15, 20]); const A = Math.round(t * (e + 1) / e);
      return c.buildMCQ({ r, stem: 'A is ' + e + ' times as efficient as B. Together they finish a work in ' + t + ' days. In how many days can A alone finish it?', right: String(A), wrong: [String(t * (e + 1)), String(A + 5), String(t)], explanation: 'A alone = ' + A + ' days.', steps: ['Efficiency A : B = ' + e + ' : 1', 'Total efficiency parts = ' + (e + 1), "A's rate = " + e + '/' + (e + 1) + ' of combined = ' + e + '/' + (e + 1) + ' / ' + t + ' per day', 'A alone = ' + t + ' x ' + (e + 1) + ' / ' + e + ' = ' + A + ' days'] }); },
    (r, i, c) => { const a = c.pk(r, [15, 20, 25, 30]); const k = c.pk(r, [2, 3, 4, 5]); const days = Math.round(a / k);
      return c.buildMCQ({ r, stem: 'A can complete a piece of work in ' + a + ' days. What fraction of the work will he complete in ' + days + ' days?', right: '1/' + k, wrong: ['1/' + (k + 1), '1/' + (k - 1), k + '/' + a], explanation: 'In ' + days + ' days he does 1/' + k + ' of the work.', steps: ['Full work in ' + a + ' days', '1 day work = 1/' + a, days + ' days work = ' + days + ' / ' + a + ' = 1/' + k] }); },
]);
G['Time & Work'] = (r, i, c) => { return TTW[i % TTW.length](r, i, c); };

const TSI = [
    (r, i, c) => { const P = c.ri(r, 4, 20) * 500, R = c.pk(r, [4, 5, 6, 8, 10, 12]), T = c.pk(r, [2, 3, 4, 5]); const SI = P * R * T / 100;
      return c.buildMCQ({ r, stem: 'Find the simple interest on Rs.' + P + ' at ' + R + '% per annum for ' + T + ' years.', right: 'Rs.' + SI, wrong: ['Rs.' + (SI + 100), 'Rs.' + (SI - 50), 'Rs.' + (SI * 2)], explanation: 'SI = Rs.' + SI + '.', steps: ['SI = P x R x T / 100', '   = ' + P + ' x ' + R + ' x ' + T + ' / 100', '   = Rs.' + SI] }); },
    (r, i, c) => { const P = c.ri(r, 4, 15) * 500, R = c.pk(r, [5, 8, 10, 12]), T = c.pk(r, [2, 3, 4]); const SI = P * R * T / 100; const A = P + SI;
      return c.buildMCQ({ r, stem: 'A sum of Rs.' + P + ' is lent at ' + R + '% simple interest per annum for ' + T + ' years. What is the total amount to be repaid?', right: 'Rs.' + A, wrong: ['Rs.' + (A + 100), 'Rs.' + SI, 'Rs.' + (A - 50)], explanation: 'Amount = Rs.' + A + '.', steps: ['SI = ' + P + ' x ' + R + ' x ' + T + ' / 100 = Rs.' + SI, 'Amount = P + SI = ' + P + ' + ' + SI, '   = Rs.' + A] }); },
    (r, i, c) => { const P = c.ri(r, 4, 10) * 1000, T = c.pk(r, [2, 4, 5, 8]); const SI = c.ri(r, 4, 15) * 100; const R = Math.round(100 * SI / (P * T));
      return c.buildMCQ({ r, stem: 'A sum of Rs.' + P + ' yields a simple interest of Rs.' + SI + ' in ' + T + ' years. Find the rate of interest per annum.', right: R + '%', wrong: [(R + 2) + '%', (R - 1) + '%', (R + 5) + '%'], explanation: 'Rate = ' + R + '% per annum.', steps: ['SI = P x R x T / 100', R + ' = 100 x ' + SI + ' / (' + P + ' x ' + T + ')', '   = ' + R + '%'] }); },
    (r, i, c) => { const P = c.ri(r, 5, 12) * 1000, R = c.pk(r, [5, 6, 8, 10]); const SI = c.ri(r, 5, 12) * 100; const T = Math.round(100 * SI / (P * R));
      return c.buildMCQ({ r, stem: 'In how many years will Rs.' + P + ' earn a simple interest of Rs.' + SI + ' at ' + R + '% per annum?', right: T + ' years', wrong: [(T + 1) + ' years', (T + 2) + ' years', (T - 1) + ' years'], explanation: 'Time = ' + T + ' years.', steps: ['T = 100 x SI / (P x R)', '   = 100 x ' + SI + ' / (' + P + ' x ' + R + ')', '   = ' + T + ' years'] }); },
    (r, i, c) => { const R = c.pk(r, [5, 8, 10, 12, 15]), T = c.pk(r, [2, 3, 4, 5]); const SI = c.ri(r, 6, 18) * 100; const P = Math.round(100 * SI / (R * T));
      return c.buildMCQ({ r, stem: 'What sum of money will yield Rs.' + SI + ' as simple interest in ' + T + ' years at ' + R + '% per annum?', right: 'Rs.' + P, wrong: ['Rs.' + (P + 500), 'Rs.' + (P - 200), 'Rs.' + (P * 2)], explanation: 'Principal = Rs.' + P + '.', steps: ['P = 100 x SI / (R x T)', '   = 100 x ' + SI + ' / (' + R + ' x ' + T + ')', '   = Rs.' + P] }); },
    (r, i, c) => { const P = c.pk(r, [4000, 5000, 8000, 10000, 12500]), R = c.pk(r, [10, 20]); const A = P * (1 + R / 100) * (1 + R / 100); const CI = A - P;
      return c.buildMCQ({ r, stem: 'Find the compound interest on Rs.' + P + ' at ' + R + '% per annum for 2 years, compounded annually.', right: 'Rs.' + CI, wrong: ['Rs.' + (CI + 100), 'Rs.' + Math.round(P * R * 2 / 100), 'Rs.' + (CI - 80)], explanation: 'CI = Rs.' + CI + '.', steps: ['Amount = P(1 + R/100)^2', '   = ' + P + ' x ' + (1 + R / 100) + ' x ' + (1 + R / 100), '   = Rs.' + A, 'CI = ' + A + ' - ' + P + ' = Rs.' + CI] }); },
];
TSI.push(...[
    (r, i, c) => { const P = c.pk(r, [2000, 4000, 5000, 8000]), R = c.pk(r, [10, 20]); const A = P * Math.pow(1 + R / 100, 3); const CI = Math.round(A - P);
      return c.buildMCQ({ r, stem: 'Find the compound interest on Rs.' + P + ' at ' + R + '% per annum for 3 years (nearest rupee).', right: 'Rs.' + CI, wrong: ['Rs.' + (CI + 120), 'Rs.' + Math.round(P * R * 3 / 100), 'Rs.' + (CI - 100)], explanation: 'CI = Rs.' + CI + '.', steps: ['A = ' + P + ' x (1 + ' + (R / 100) + ')^3', '   = ' + P + ' x ' + (Math.pow(1 + R / 100, 3)).toFixed(3), '   = Rs.' + Math.round(A), 'CI = ' + Math.round(A) + ' - ' + P + ' = Rs.' + CI] }); },
    (r, i, c) => { const P = c.pk(r, [5000, 8000, 10000, 12000, 20000]), R = c.pk(r, [10, 20]); const diff = Math.round(P * Math.pow(R / 100, 2));
      return c.buildMCQ({ r, stem: 'The difference between compound interest and simple interest on Rs.' + P + ' at ' + R + '% per annum for 2 years is:', right: 'Rs.' + diff, wrong: ['Rs.' + (diff + 20), 'Rs.' + Math.round(P * R / 100), 'Rs.' + (diff * 2)], explanation: 'Difference = Rs.' + diff + '.', steps: ['Difference (2 yr) = P x (R/100)^2', '   = ' + P + ' x (' + (R / 100) + ')^2', '   = ' + P + ' x ' + (R * R / 10000) + ' = Rs.' + diff] }); },
    (r, i, c) => { const R = c.pk(r, [4, 5, 10, 20, 25]); const T = Math.round(100 / R);
      return c.buildMCQ({ r, stem: 'At ' + R + '% per annum simple interest, in how many years will a sum double itself?', right: T + ' years', wrong: [(T + 2) + ' years', (2 * T) + ' years', (T - 1) + ' years'], explanation: 'Time = ' + T + ' years.', steps: ['To double: SI = P', 'P = P x ' + R + ' x T / 100', 'T = 100 / ' + R + ' = ' + T + ' years'] }); },
    (r, i, c) => { const T = c.pk(r, [6, 8, 10, 12, 15]); const T3 = 2 * T;
      return c.buildMCQ({ r, stem: 'A sum of money doubles itself in ' + T + ' years at simple interest. In how many years will it become three times itself?', right: T3 + ' years', wrong: [(3 * T) + ' years', (T + 5) + ' years', (T - 2) + ' years'], explanation: 'It becomes 3 times in ' + T3 + ' years.', steps: ['Doubles: SI earned = P in ' + T + ' years', 'Thrice: SI needed = 2P', 'Time = ' + T + ' x 2 = ' + T3 + ' years'] }); },
    (r, i, c) => { const P = c.pk(r, [10000, 14400, 16900, 19600]), R = c.pk(r, [10, 20]); const f = Math.pow(1 + R / 100, 2); const A = Math.round(P * f); const T = 2;
      return c.buildMCQ({ r, stem: 'A sum amounts to Rs.' + A + ' in ' + T + ' years at ' + R + '% per annum compound interest. Find the principal.', right: 'Rs.' + P, wrong: ['Rs.' + (P + 1000), 'Rs.' + Math.round(A / 1.5), 'Rs.' + (P - 800)], explanation: 'Principal = Rs.' + P + '.', steps: ['A = P(1 + R/100)^2', A + ' = P x (' + (1 + R / 100) + ')^2', A + ' = P x ' + f, 'P = ' + A + ' / ' + f + ' = Rs.' + P] }); },
    (r, i, c) => { const P = c.pk(r, [10000, 20000, 40000]), R = c.pk(r, [10, 20]); const A = P * (1 + R / 200) * (1 + R / 200); const CI = Math.round(A - P);
      return c.buildMCQ({ r, stem: 'Find the compound interest on Rs.' + P + ' at ' + R + '% per annum for 1 year, compounded half-yearly.', right: 'Rs.' + CI, wrong: ['Rs.' + Math.round(P * R / 100), 'Rs.' + (CI + 150), 'Rs.' + (CI - 120)], explanation: 'CI = Rs.' + CI + '.', steps: ['Half-yearly rate = ' + R + '/2 = ' + (R / 2) + '%, periods = 2', 'A = ' + P + ' x (1 + ' + (R / 200) + ')^2', '   = Rs.' + Math.round(A), 'CI = ' + Math.round(A) + ' - ' + P + ' = Rs.' + CI] }); },
]);
G['Simple & Compound Interest'] = (r, i, c) => { return TSI[i % TSI.length](r, i, c); };

const TNS = [
    (r, i, c) => { const k = c.ri(r, 12, 40); const n = k * k;
      return c.buildMCQ({ r, stem: 'What is the square root of ' + n + '?', right: String(k), wrong: [String(k + 1), String(k - 1), String(2 * k)], explanation: 'Square root = ' + k + '.', steps: [k + ' x ' + k + ' = ' + n, 'So square root of ' + n + ' = ' + k] }); },
    (r, i, c) => { const n = c.ri(r, 100, 999);
      return c.buildMCQ({ r, stem: 'What is the sum of the digits of ' + n + '?', right: String(String(n).split('').reduce((a, b) => a + Number(b), 0)), wrong: [String(String(n).split('').reduce((a, b) => a + Number(b), 0) + 1), String(String(n).split('').length), String(String(n).split('').reduce((a, b) => a + Number(b), 0) + 2)], explanation: 'Sum = ' + String(n).split('').reduce((a, b) => a + Number(b), 0) + '.', steps: ['Digits of ' + n + ': ' + String(n).split('').join(' + '), '   = ' + String(n).split('').reduce((a, b) => a + Number(b), 0)] }); },
    (r, i, c) => { const d = c.pk(r, [2, 3, 4, 5, 6, 8, 9, 11]); const n = d * c.ri(r, 20, 90);
      return c.buildMCQ({ r, stem: 'Is ' + n + ' divisible by ' + d + '? What is ' + n + ' / ' + d + '?', right: String(n / d), wrong: [String(n / d + 1), String(n / d - 1), String(Math.round(n / d) + 2)], explanation: n + ' / ' + d + ' = ' + (n / d) + '.', steps: [n + ' / ' + d + ' = ' + (n / d), 'Remainder = 0, so ' + n + ' is divisible by ' + d] }); },
    (r, i, c) => { const n = c.ri(r, 20, 99);
      return c.buildMCQ({ r, stem: 'What is the remainder when ' + n + ' is divided by 9?', right: String(n % 9), wrong: [String((n % 9) + 1), String(9 - (n % 9) || 9), String((n % 9) + 2)], explanation: 'Remainder = ' + (n % 9) + '.', steps: ['Digit sum of ' + n + ' = ' + String(n).split('').reduce((a, b) => a + Number(b), 0), String(n).split('').reduce((a, b) => a + Number(b), 0) + ' mod 9 = ' + (n % 9), 'Remainder = ' + (n % 9)] }); },
    (r, i, c) => { const k = c.ri(r, 2, 9); const n = 2 * k + 1;
      return c.buildMCQ({ r, stem: 'What is the ' + k + 'th term of the sequence of odd numbers 1, 3, 5, 7, ...?', right: String(2 * k - 1), wrong: [String(2 * k + 1), String(2 * k), String(2 * k - 2)], explanation: 'The ' + k + 'th odd number = ' + (2 * k - 1) + '.', steps: ['Odd numbers: 1, 3, 5, ...', 'nth odd number = 2n - 1', 'For n = ' + k + ': 2 x ' + k + ' - 1 = ' + (2 * k - 1)] }); },
    (r, i, c) => { const a = c.ri(r, 12, 40), b = c.ri(r, 12, 40); const u = Math.min(a, b), v = Math.max(a, b);
      return c.buildMCQ({ r, stem: 'What is the remainder when ' + v + ' is divided by ' + u + '?', right: String(v % u), wrong: [String((v % u) + 1), String(u - (v % u)), String((v % u) + 2)], explanation: 'Remainder = ' + (v % u) + '.', steps: [v + ' = ' + u + ' x ' + Math.floor(v / u) + ' + ' + (v % u), 'Remainder = ' + (v % u)] }); },
];
TNS.push(...[
    (r, i, c) => { const a = c.ri(r, 111, 999), d = c.pk(r, [3, 4, 5, 6, 7]); const q = Math.floor(a / d); const rem = a - q * d;
      return c.buildMCQ({ r, stem: 'Find the remainder when ' + a + ' is divided by ' + d + '.', right: String(rem), wrong: [String(rem + 1), String(d - rem || d), String(rem + 2)], explanation: 'Remainder = ' + rem + '.', steps: [a + ' / ' + d + ': quotient = ' + q, d + ' x ' + q + ' = ' + (q * d), 'Remainder = ' + a + ' - ' + (q * d) + ' = ' + rem] }); },
    (r, i, c) => { const n = c.ri(r, 3, 12); const sum = n * (n + 1) / 2;
      return c.buildMCQ({ r, stem: 'What is the sum of the first ' + n + ' natural numbers (1 + 2 + ... + ' + n + ')?', right: String(sum), wrong: [String(sum + n), String(n * n), String(sum - 1)], explanation: 'Sum = ' + sum + '.', steps: ['Sum = n(n + 1) / 2', '   = ' + n + ' x ' + (n + 1) + ' / 2', '   = ' + sum] }); },
    (r, i, c) => { const a = c.ri(r, 2, 9), k = c.ri(r, 2, 5); const p = Math.pow(a, k);
      return c.buildMCQ({ r, stem: 'What is the value of ' + a + '^' + k + '?', right: String(p), wrong: [String(p * a), String(a * k), String(p - a)], explanation: a + '^' + k + ' = ' + p + '.', steps: [a + '^' + k + ' = ' + Array(k).fill(a).join(' x '), '   = ' + p] }); },
    (r, i, c) => { const k = c.ri(r, 3, 9); const n = k * k;
      return c.buildMCQ({ r, stem: 'How many perfect squares lie between 1 and ' + (n + 5) + ' (exclusive of ' + (n + 5) + ')?', right: String(k), wrong: [String(k + 1), String(k - 1), String(2 * k)], explanation: 'There are ' + k + ' perfect squares.', steps: ['Squares: 1, 4, 9, ..., ' + k * k, 'All <= ' + k * k + ' < ' + (n + 5), 'Count = ' + k + ' (1^2 to ' + k + '^2)'] }); },
    (r, i, c) => { const n = c.ri(r, 4, 12); const f = [1, 1]; for (let j = 2; j <= n; j++) f.push(f[j - 1] + f[j - 2]); const val = f[n];
      return c.buildMCQ({ r, stem: 'In the Fibonacci sequence 1, 1, 2, 3, 5, 8, ..., what is the ' + (n + 1) + 'th term?', right: String(val), wrong: [String(f[n - 1]), String(val + f[n - 1]), String(val + 1)], explanation: 'The ' + (n + 1) + 'th term = ' + val + '.', steps: ['Sequence: ' + f.slice(0, n + 1).join(', '), 'Next = ' + f[n - 1] + ' + ' + f[n] + ' = ' + val] }); },
    (r, i, c) => { const n = c.ri(r, 101, 999); const ds = String(n).split('').map(Number); const prod = ds.reduce((a, b) => a * b, 1);
      return c.buildMCQ({ r, stem: 'What is the product of the digits of ' + n + '?', right: String(prod), wrong: [String(prod + 1), String(String(n).split('').reduce((a, b) => a + Number(b), 0)), String(prod * 2)], explanation: 'Product = ' + prod + '.', steps: ['Digits: ' + ds.join(' x '), '   = ' + prod] }); },
]);
G['Number System'] = (r, i, c) => { return TNS[i % TNS.length](r, i, c); };

const TLH = [
    (r, i, c) => { const a = c.ri(r, 8, 30), b = c.ri(r, 8, 36); const gcd = (u, v) => v ? gcd(v, u % v) : u; const h = gcd(a, b);
      return c.buildMCQ({ r, stem: 'Find the HCF of ' + a + ' and ' + b + '.', right: String(h), wrong: [String(h + 1), String(h * 2), String(h + 2)], explanation: 'HCF = ' + h + '.', steps: [a + ' = ' + h + ' x ' + (a / h) + ', ' + b + ' = ' + h + ' x ' + (b / h), 'Common factor (highest) = ' + h] }); },
    (r, i, c) => { const a = c.ri(r, 6, 24), b = c.ri(r, 6, 30); const gcd = (u, v) => v ? gcd(v, u % v) : u; const h = gcd(a, b); const l = a * b / h;
      return c.buildMCQ({ r, stem: 'Find the LCM of ' + a + ' and ' + b + '.', right: String(l), wrong: [String(l + a), String(2 * l), String(a * b)], explanation: 'LCM = ' + l + '.', steps: ['HCF(' + a + ', ' + b + ') = ' + h, 'LCM = a x b / HCF = ' + a + ' x ' + b + ' / ' + h, '   = ' + l] }); },
    (r, i, c) => { const h = c.ri(r, 3, 12); let a = h * c.ri(r, 2, 9), b = h * c.ri(r, 2, 9); if (a === b) b = a + h;
      return c.buildMCQ({ r, stem: 'The HCF of two numbers is ' + h + ' and their sum is ' + (a + b) + '. If one number is ' + a + ', find the other.', right: String(b), wrong: [String(a), String(b + h), String(a + h)], explanation: 'Other number = ' + b + '.', steps: ['Sum = ' + (a + b) + ', one number = ' + a, 'Other = ' + (a + b) + ' - ' + a + ' = ' + b, 'Check HCF(' + a + ', ' + b + ') = ' + h] }); },
    (r, i, c) => { const h = c.pk(r, [4, 6, 8, 12]); const a = h * c.ri(r, 3, 8), b = h * c.ri(r, 3, 8); const l = a * b / h;
      return c.buildMCQ({ r, stem: 'The HCF of two numbers is ' + h + ' and their LCM is ' + l + '. If one number is ' + a + ', find the other.', right: String(b), wrong: [String(l / a), String(b + h), String(a)], explanation: 'Other number = ' + b + '.', steps: ['HCF x LCM = a x b', h + ' x ' + l + ' = ' + a + ' x b', 'b = ' + (h * l) + ' / ' + a + ' = ' + b] }); },
    (r, i, c) => { const x = c.pk(r, [6, 8, 9, 12, 15, 18]), y = x + 6, z = x + 12; const gcd = (u, v) => v ? gcd(v, u % v) : u; const L2 = x * y / gcd(x, y); const lcm3 = L2 * z / gcd(L2, z);
      return c.buildMCQ({ r, stem: 'Three bells toll at intervals of ' + x + ', ' + y + ' and ' + z + ' seconds respectively. If they toll together now, after how many seconds will they toll together again?', right: String(lcm3), wrong: [String(lcm3 * 2), String(z), String(lcm3 + x)], explanation: 'They toll together after ' + lcm3 + ' seconds.', steps: ['Find LCM of ' + x + ', ' + y + ', ' + z, 'LCM(' + x + ', ' + y + ') = ' + L2, 'LCM = ' + L2 + ' with ' + z + ' = ' + lcm3, 'So they toll together after ' + lcm3 + ' seconds'] }); },
];
TLH.push(...[
    (r, i, c) => { const d = c.ri(r, 6, 15), rr = c.ri(r, 1, 5); const k1 = c.ri(r, 2, 5), k2 = k1 + 1; const a = d * k1 + rr, b = d * k2 + rr;
      return c.buildMCQ({ r, stem: 'Find the greatest number which divides ' + a + ' and ' + b + ', leaving remainders ' + rr + ' and ' + rr + ' respectively.', right: String(d), wrong: [String(d * 2), String(d + 1), String(rr * 2)], explanation: 'Greatest number = ' + d + '.', steps: ['Required number = HCF(' + a + ' - ' + rr + ', ' + b + ' - ' + rr + ')', '   = HCF(' + (a - rr) + ', ' + (b - rr) + ')', '   = HCF(' + (d * k1) + ', ' + (d * k2) + ') = ' + d] }); },
    (r, i, c) => { const l = c.pk(r, [12, 15, 18, 21, 24]); const rem = 100 % l; const N = rem === 0 ? 100 : 100 + (l - rem);
      return c.buildMCQ({ r, stem: 'What is the smallest 3-digit number exactly divisible by ' + l + '?', right: String(N), wrong: [String(N + l), String(100), String(N + 1)], explanation: 'Smallest 3-digit multiple = ' + N + '.', steps: ['Smallest 3-digit number = 100', '100 / ' + l + ' gives remainder ' + rem, 'Add ' + (l - rem) + ': 100 + ' + (l - rem) + ' = ' + N, 'Check: ' + N + ' / ' + l + ' = ' + (N / l)] }); },
    (r, i, c) => { const a = c.ri(r, 15, 40), b = c.ri(r, 15, 45), c2 = c.ri(r, 15, 50); const gcd = (u, v) => v ? gcd(v, u % v) : u; const h = gcd(gcd(a, b), c2);
      return c.buildMCQ({ r, stem: 'Find the HCF of ' + a + ', ' + b + ' and ' + c2 + '.', right: String(h), wrong: [String(h + 1), String(h + 2), String(h * 2)], explanation: 'HCF = ' + h + '.', steps: ['HCF(' + a + ', ' + b + ') = ' + gcd(a, b), 'HCF(' + gcd(a, b) + ', ' + c2 + ') = ' + h] }); },
    (r, i, c) => { const a = c.ri(r, 4, 15), b = c.ri(r, 4, 18), c2 = c.ri(r, 4, 20); const gcd = (u, v) => v ? gcd(v, u % v) : u; const h1 = gcd(a, b); const l = a * b / h1; const L = l * c2 / gcd(l, c2);
      return c.buildMCQ({ r, stem: 'Find the LCM of ' + a + ', ' + b + ' and ' + c2 + '.', right: String(L), wrong: [String(L * 2), String(a * b * c2), String(L + a)], explanation: 'LCM = ' + L + '.', steps: ['LCM(' + a + ', ' + b + ') = ' + l, 'LCM(' + l + ', ' + c2 + ') = ' + L] }); },
    (r, i, c) => { const l = c.pk(r, [8, 12, 15, 16, 18, 20]); const q = c.ri(r, 40, 90); const rem = q % l; const next = q + (l - rem);
      return c.buildMCQ({ r, stem: 'What is the smallest number greater than ' + q + ' that is exactly divisible by ' + l + '?', right: String(next), wrong: [String(next + l), String(q), String(next + 1)], explanation: 'Answer = ' + next + '.', steps: [q + ' / ' + l + ' gives remainder ' + rem, 'Add ' + (l - rem) + ' to make it divisible: ' + q + ' + ' + (l - rem) + ' = ' + next, 'Check: ' + next + ' / ' + l + ' = ' + (next / l)] }); },
    (r, i, c) => { const h = c.pk(r, [6, 8, 10, 12, 15]); const k1 = c.ri(r, 2, 6), k2 = c.ri(r, 2, 6); const a = h * k1, b = h * k2;
      return c.buildMCQ({ r, stem: 'Two numbers ' + a + ' and ' + b + ' both leave remainder 0 when divided by a number. What is the largest such number?', right: String(h), wrong: [String(h * 2), String(h + 1), String(a + b)], explanation: 'Largest number = HCF = ' + h + '.', steps: ['Numbers: ' + a + ' = ' + h + ' x ' + k1 + ', ' + b + ' = ' + h + ' x ' + k2, 'Largest divisor of both = HCF(' + a + ', ' + b + ') = ' + h] }); },
    (r, i, c) => { const l = c.pk(r, [10, 12, 14, 15, 18]); const N = l * c.ri(r, 3, 8);
      return c.buildMCQ({ r, stem: 'A number ' + N + ' is divisible by ' + l + '. Which of these is also divisible by ' + l + '?', right: String(2 * N), wrong: [String(N + 1), String(N + l - 1), String(2 * N + 1)], explanation: '2 x ' + N + ' = ' + (2 * N) + ' is divisible by ' + l + '.', steps: [N + ' is divisible by ' + l, '2 x ' + N + ' = ' + (2 * N) + ' is also divisible by ' + l, 'Check: ' + (2 * N) + ' / ' + l + ' = ' + (2 * N / l)] }); },
]);
G['LCM & HCF'] = (r, i, c) => { return TLH[i % TLH.length](r, i, c); };

const TPR = [
    (r, i, c) => { const red = c.ri(r, 3, 12), blue = c.ri(r, 3, 12); const tot = red + blue; const g = (u, v) => v ? g(v, u % v) : u; const gg = g(red, tot);
      return c.buildMCQ({ r, stem: 'A bag contains ' + red + ' red and ' + blue + ' blue balls. One ball is drawn at random. What is the probability that it is red?', right: (red / gg) + '/' + (tot / gg), wrong: [(blue / g(blue, tot)) + '/' + (tot / g(blue, tot)), red + '/' + blue, '1/' + tot], explanation: 'P(red) = ' + (red / gg) + '/' + (tot / gg) + '.', steps: ['Total balls = ' + red + ' + ' + blue + ' = ' + tot, 'Favourable = ' + red, 'P(red) = ' + red + '/' + tot + ' = ' + (red / gg) + '/' + (tot / gg)] }); },
    (r, i, c) => { const target = c.pk(r, [3, 4, 5, 6, 7, 8, 9, 10, 11]); const cnts = { 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 5, 9: 4, 10: 3, 11: 2, 12: 1 }; const cnt = cnts[target]; const g = (u, v) => v ? g(v, u % v) : u; const gg = g(cnt, 36);
      return c.buildMCQ({ r, stem: 'Two dice are thrown together. What is the probability that the sum of the numbers is ' + target + '?', right: (cnt / gg) + '/' + (36 / gg), wrong: ['1/12', '1/18', '1/9'], explanation: 'P = ' + (cnt / gg) + '/' + (36 / gg) + '.', steps: ['Total outcomes = 6 x 6 = 36', 'Favourable outcomes for sum ' + target + ' = ' + cnt, 'P = ' + cnt + '/36 = ' + (cnt / gg) + '/' + (36 / gg)] }); },
    (r, i, c) => { const red = c.ri(r, 2, 9), green = c.ri(r, 2, 9), yel = c.ri(r, 2, 9); const tot = red + green + yel; const g = (u, v) => v ? g(v, u % v) : u; const ng = tot - green; const gg = g(ng, tot);
      return c.buildMCQ({ r, stem: 'A box has ' + red + ' red, ' + green + ' green and ' + yel + ' yellow marbles. One marble is picked at random. Find the probability that it is NOT green.', right: (ng / gg) + '/' + (tot / gg), wrong: [(green / g(green, tot)) + '/' + (tot / g(green, tot)), '1/' + tot, '1/2'], explanation: 'P(not green) = ' + (ng / gg) + '/' + (tot / gg) + '.', steps: ['Total = ' + red + ' + ' + green + ' + ' + yel + ' = ' + tot, 'Not green = ' + tot + ' - ' + green + ' = ' + ng, 'P = ' + ng + '/' + tot + ' = ' + (ng / gg) + '/' + (tot / gg)] }); },
    (r, i, c) => { const n = c.ri(r, 5, 25); const odd = Math.ceil(n / 2); const g = (u, v) => v ? g(v, u % v) : u; const gg = g(odd, n);
      return c.buildMCQ({ r, stem: 'A number is chosen at random from 1 to ' + n + '. What is the probability that it is odd?', right: (odd / gg) + '/' + (n / gg), wrong: ['1/2', '1/' + n, '2/' + n], explanation: 'P(odd) = ' + (odd / gg) + '/' + (n / gg) + '.', steps: ['Numbers 1 to ' + n + ': total = ' + n, 'Odd numbers = ' + odd + ' (1, 3, ...)', 'P = ' + odd + '/' + n + ' = ' + (odd / gg) + '/' + (n / gg)] }); },
    (r, i, c) => { const ranks = ['ace', 'king', 'queen', 'jack', '10', '9', '7', '5']; const rank = ranks[Math.floor(r() * ranks.length)];
      return c.buildMCQ({ r, stem: 'A card is drawn from a well-shuffled deck of 52 cards. What is the probability that it is a ' + rank + '?', right: '1/13', wrong: ['1/4', '4/13', '1/52'], explanation: 'P(' + rank + ') = 1/13.', steps: ['Total cards = 52', 'Cards of rank "' + rank + '" = 4 (one per suit)', 'P = 4/52 = 1/13'] }); },
    (r, i, c) => { const suits = ['spade', 'heart', 'diamond', 'club']; const suit = suits[Math.floor(r() * suits.length)];
      return c.buildMCQ({ r, stem: 'A card is drawn from a deck of 52 cards. What is the probability that it is a ' + suit + '?', right: '1/4', wrong: ['1/13', '1/2', '13/39'], explanation: 'P(' + suit + ') = 1/4.', steps: ['Total cards = 52', suit.charAt(0).toUpperCase() + suit.slice(1) + 's = 13', 'P = 13/52 = 1/4'] }); },
    (r, i, c) => { const kind = c.pk(r, ['two heads', 'two tails']);
      return c.buildMCQ({ r, stem: 'Two fair coins are tossed together. What is the probability of getting ' + kind + '?', right: '1/4', wrong: ['1/2', '1/3', '3/4'], explanation: 'P = 1/4.', steps: ['Sample space = {HH, HT, TH, TT}  (4 outcomes)', 'Favourable (' + kind + ') = 1', 'P = 1/4'] }); },
    (r, i, c) => {
      return c.buildMCQ({ r, stem: 'A day is chosen at random from a week. What is the probability that it is a Sunday?', right: '1/7', wrong: ['1/6', '2/7', '1/5'], explanation: 'P = 1/7.', steps: ['A week has 7 days', 'Sundays in a week = 1', 'P = 1/7'] }); },
];

G['Probability'] = (r, i, c) => { return TPR[i % TPR.length](r, i, c); };

const TPC = [
    (r, i, c) => { const n = c.ri(r, 4, 12);
      return c.buildMCQ({ r, stem: 'In how many different ways can ' + n + ' distinct books be arranged on a shelf?', right: String(fact(n)), wrong: [String(fact(n - 1)), String(n * n), String(fact(n) / 2)], explanation: 'Ways = ' + fact(n) + '.', steps: ['Arrangements of ' + n + ' distinct books = ' + n + '!', fact(n) + ' = ' + Array.from({ length: n }, (_, j) => j + 1).join(' x '), '   = ' + fact(n)] }); },
    (r, i, c) => { const w = c.pk(r, [[5, 2], [6, 3], [7, 2], [8, 3], [9, 2], [10, 2], [6, 2], [8, 2], [12, 3]]); const tot = fact(w[0]); const den = fact(w[1]);
      return c.buildMCQ({ r, stem: 'In how many ways can the letters of a word with ' + w[0] + ' letters, where ' + w[1] + ' letters are identical (repeated), be arranged?', right: String(tot / den), wrong: [String(fact(w[0])), String(fact(w[0]) / 4), String(tot / den / 2)], explanation: 'Ways = ' + tot + ' / ' + den + ' = ' + (tot / den) + '.', steps: ['Total letters = ' + w[0] + ', repeated = ' + w[1], 'Ways = ' + w[0] + '! / ' + w[1] + '! = ' + tot + ' / ' + den, '   = ' + (tot / den)] }); },
    (r, i, c) => { const n = c.ri(r, 5, 12), rr = c.pk(r, [2, 3]); const P = fact(n) / fact(n - rr);
      return c.buildMCQ({ r, stem: 'How many ' + rr + '-digit numbers can be formed using the digits 1 to ' + n + ' without repetition?', right: String(P), wrong: [String(P * rr), String(fact(n)), String(P / 2)], explanation: 'Ways = ' + P + '.', steps: ['P(' + n + ', ' + rr + ') = ' + n + '! / (' + n + ' - ' + rr + ')!', '   = ' + n + ' x ' + (n - 1) + (rr === 3 ? ' x ' + (n - 2) : ''), '   = ' + P] }); },
    (r, i, c) => { const n = c.ri(r, 5, 12), rr = c.pk(r, [2, 3]); const C = fact(n) / (fact(rr) * fact(n - rr));
      return c.buildMCQ({ r, stem: 'From a group of ' + n + ' students, in how many ways can a team of ' + rr + ' students be selected?', right: String(C), wrong: [String(C * 2), String(fact(n) / fact(n - rr)), String(C + n)], explanation: 'Ways = C(' + n + ', ' + rr + ') = ' + C + '.', steps: ['C(' + n + ', ' + rr + ') = ' + n + '! / (' + rr + '! x ' + (n - rr) + '!)', '   = ' + fact(n) + ' / (' + fact(rr) + ' x ' + fact(n - rr) + ')', '   = ' + C] }); },
    (r, i, c) => { const m = c.ri(r, 3, 9), n = c.ri(r, 3, 9);
      return c.buildMCQ({ r, stem: 'A restaurant offers ' + m + ' types of starters and ' + n + ' types of main courses. In how many ways can a person choose one starter and one main course?', right: String(m * n), wrong: [String(m + n), String(m * n + 1), String(m + n + 1)], explanation: 'Ways = ' + (m * n) + '.', steps: ['Starter: ' + m + ' choices', 'Main course: ' + n + ' choices', 'Total = ' + m + ' x ' + n + ' = ' + (m * n) + ' (multiplication principle)'] }); },
    (r, i, c) => { const n = c.ri(r, 5, 12);
      return c.buildMCQ({ r, stem: 'In how many ways can ' + n + ' people be seated around a circular table? (rotations considered same)', right: String(fact(n - 1)), wrong: [String(fact(n)), String(fact(n) / 2), String(fact(n - 1) * 2)], explanation: 'Ways = ' + fact(n - 1) + '.', steps: ['Circular arrangements of ' + n + ' people = (' + n + ' - 1)!', '   = ' + (n - 1) + '! = ' + fact(n - 1)] }); },
    (r, i, c) => { const n = c.ri(r, 6, 15); const H = n * (n - 1) / 2;
      return c.buildMCQ({ r, stem: 'There are ' + n + ' people in a room. If each person shakes hands with every other person exactly once, how many handshakes take place?', right: String(H), wrong: [String(n * (n - 1)), String(n), String(H + n)], explanation: 'Handshakes = ' + H + '.', steps: ['Each handshake = choosing 2 people from ' + n, 'C(' + n + ', 2) = ' + n + ' x ' + (n - 1) + ' / 2', '   = ' + H] }); },
    (r, i, c) => { const words = [['LEADER', 6, 2, 'E'], ['MANAGER', 7, 2, 'A'], ['SYSTEM', 6, 2, 'S'], ['PROGRAM', 7, 2, 'R'], ['REPEAT', 6, 2, 'E']]; const w = words[Math.floor(r() * words.length)];
      return c.buildMCQ({ r, stem: 'In how many ways can the letters of the word "' + w[0] + '" be arranged?', right: String(fact(w[1]) / fact(w[2])), wrong: [String(fact(w[1])), String(fact(w[1]) / 4), String(fact(w[1]) / (fact(w[2]) * 2))], explanation: 'Ways = ' + (fact(w[1]) / fact(w[2])) + '.', steps: ['"' + w[0] + '" has ' + w[1] + ' letters, letter "' + w[3] + '" repeats ' + w[2] + ' times', 'Ways = ' + w[1] + '! / ' + w[2] + '! = ' + fact(w[1]) + ' / ' + fact(w[2]), '   = ' + (fact(w[1]) / fact(w[2]))] }); },
];
const fact = (n) => { let f = 1; for (let j = 2; j <= n; j++) f *= j; return f; };
G['Permutation & Combination'] = (r, i, c) => { return TPC[i % TPC.length](r, i, c); };

const TAL = [
    (r, i, c) => { const x = c.ri(r, 2, 15), a = c.ri(r, 2, 9), b = c.ri(r, 2, 30);
      return c.buildMCQ({ r, stem: 'Solve for x: ' + a + 'x + ' + b + ' = ' + (a * x + b) + '.', right: String(x), wrong: [String(x + 1), String(x - 1), String(a * x)], explanation: 'x = ' + x + '.', steps: [a + 'x + ' + b + ' = ' + (a * x + b), a + 'x = ' + (a * x + b) + ' - ' + b + ' = ' + (a * x), 'x = ' + (a * x) + ' / ' + a + ' = ' + x] }); },
    (r, i, c) => { const x = c.ri(r, 2, 12), a = c.ri(r, 2, 9), b = c.ri(r, 2, 9), k = a * x + b;
      return c.buildMCQ({ r, stem: 'If ' + a + 'x + ' + b + ' = ' + k + ', find the value of x.', right: String(x), wrong: [String(x + 2), String(k - b), String(x - 2)], explanation: 'x = ' + x + '.', steps: [a + 'x = ' + k + ' - ' + b + ' = ' + (k - b), 'x = ' + (k - b) + ' / ' + a + ' = ' + x] }); },
    (r, i, c) => { const x = c.ri(r, 1, 9), y = c.ri(r, 1, 9); const s = x + y, d = Math.abs(x - y);
      return c.buildMCQ({ r, stem: 'The sum of two numbers is ' + s + ' and their difference is ' + d + '. Find the larger number.', right: String(Math.max(x, y)), wrong: [String(Math.min(x, y)), String(s), String(Math.max(x, y) + 1)], explanation: 'Larger number = ' + Math.max(x, y) + '.', steps: ['x + y = ' + s + ', x - y = ' + d, 'Adding: 2x = ' + (s + d) + '  =>  x = ' + ((s + d) / 2), 'Larger number = ' + Math.max(x, y)] }); },
    (r, i, c) => { const a = c.ri(r, 2, 8), b = c.ri(r, 2, 8); const val = c.ri(r, 3, 12);
      return c.buildMCQ({ r, stem: 'If x = ' + val + ', find the value of x^2 + ' + (2 * b) + 'x + ' + (b * b) + '.', right: String((val + b) * (val + b)), wrong: [String((val + b) * (val + b) + b), String(val * val + 2 * b), String((val + b) * (val + b) - 1)], explanation: 'Value = ' + ((val + b) * (val + b)) + '.', steps: ['x^2 + ' + (2 * b) + 'x + ' + (b * b) + ' = (x + ' + b + ')^2', 'x = ' + val + '  =>  (' + val + ' + ' + b + ')^2', '   = ' + (val + b) + '^2 = ' + ((val + b) * (val + b))] }); },
    (r, i, c) => { const a = c.ri(r, 2, 6), k = c.ri(r, 2, 9); const val = a * k * k;
      return c.buildMCQ({ r, stem: 'If y varies directly as x^2 and y = ' + val + ' when x = ' + k + ', find y when x = ' + (2 * k) + '.', right: String(4 * val), wrong: [String(2 * val), String(val), String(8 * val)], explanation: 'y = ' + (4 * val) + '.', steps: ['y = k x^2  =>  k = ' + val + ' / ' + k + '^2 = ' + a, 'x = ' + (2 * k) + ': y = ' + a + ' x ' + (2 * k) + '^2', '   = ' + a + ' x ' + (4 * k * k) + ' = ' + (4 * val)] }); },
    (r, i, c) => { const a = c.ri(r, 2, 8), b = c.ri(r, 2, 8); const val = c.ri(r, 2, 9); const ans = a * val * val + b;
      return c.buildMCQ({ r, stem: 'If f(x) = ' + a + 'x^2 + ' + b + ', find f(' + val + ').', right: String(ans), wrong: [String(ans + a), String(a * val * val), String(ans - 1)], explanation: 'f(' + val + ') = ' + ans + '.', steps: ['f(' + val + ') = ' + a + ' x ' + val + '^2 + ' + b, '   = ' + a + ' x ' + (val * val) + ' + ' + b, '   = ' + (a * val * val) + ' + ' + b + ' = ' + ans] }); },
];
G['Algebra'] = (r, i, c) => { return TAL[i % TAL.length](r, i, c); };

const TSM = [
    (r, i, c) => { const a = c.ri(r, 12, 40), b = c.ri(r, 12, 40), d = c.ri(r, 12, 40); const m = Math.min(a, b);
      return c.buildMCQ({ r, stem: 'Simplify: ' + a + ' + ' + b + ' x ' + d + ' - ' + m + '.', right: String(a + b * d - m), wrong: [String((a + b) * d - m), String(a + b * (d - m)), String(a + b * d)], explanation: 'Result = ' + (a + b * d - m) + '.', steps: ['BODMAS: multiply first', b + ' x ' + d + ' = ' + (b * d), a + ' + ' + (b * d) + ' - ' + m + ' = ' + (a + b * d - m)] }); },
    (r, i, c) => { const a = c.ri(r, 2, 9), k = c.ri(r, 2, 9), b = c.ri(r, 2, 9); const val = a + b;
      return c.buildMCQ({ r, stem: 'Simplify: ' + a + ' x ' + k + ' + ' + b + ' x ' + k + '.', right: String(val * k), wrong: [String(val * k + k), String(a * k + b), String((a + b + k) * k)], explanation: 'Result = ' + (val * k) + '.', steps: ['Take ' + k + ' common: ' + k + ' x (' + a + ' + ' + b + ')', '= ' + k + ' x ' + val + ' = ' + (val * k)] }); },
    (r, i, c) => { const n = c.ri(r, 6, 15);
      return c.buildMCQ({ r, stem: 'Simplify: ' + n + ' + ' + n + ' x 2 + ' + n + ' x 3.', right: String(6 * n), wrong: [String(5 * n), String(7 * n), String(n * n)], explanation: 'Result = ' + (6 * n) + '.', steps: [n + ' x (1 + 2 + 3) = ' + n + ' x 6', '   = ' + (6 * n)] }); },
    (r, i, c) => { const rt = c.pk(r, [16, 25, 36, 49, 64, 81, 100, 144]); const add2 = c.ri(r, 2, 9);
      return c.buildMCQ({ r, stem: 'Simplify: sqrt(' + rt + ') + ' + add2 + '.', right: String(Math.sqrt(rt) + add2), wrong: [String(Math.sqrt(rt) + add2 + 1), String(rt + add2), String(Math.sqrt(rt) * add2)], explanation: 'Result = ' + (Math.sqrt(rt) + add2) + '.', steps: ['sqrt(' + rt + ') = ' + Math.sqrt(rt), Math.sqrt(rt) + ' + ' + add2 + ' = ' + (Math.sqrt(rt) + add2)] }); },
    (r, i, c) => { const a = c.ri(r, 2, 9), b = c.ri(r, 2, 9), k = c.ri(r, 2, 6);
      return c.buildMCQ({ r, stem: 'Simplify: (' + a + ' + ' + b + ') x ' + k + ' - ' + (a * k) + '.', right: String(b * k), wrong: [String((a + b) * k), String(b * k + k), String(a * k)], explanation: 'Result = ' + (b * k) + '.', steps: ['(' + a + ' + ' + b + ') x ' + k + ' = ' + ((a + b) * k), ((a + b) * k) + ' - ' + (a * k) + ' = ' + (b * k)] }); },
    (r, i, c) => { const a = c.ri(r, 11, 39), b = c.ri(r, 11, 39);
      return c.buildMCQ({ r, stem: 'Simplify: ' + a + ' x ' + (b + 1) + ' - ' + a + ' x ' + b + '.', right: String(a), wrong: [String(a * b), String(a + b), String(2 * a)], explanation: 'Result = ' + a + '.', steps: ['Take ' + a + ' common: ' + a + ' x (' + (b + 1) + ' - ' + b + ')', '= ' + a + ' x 1 = ' + a] }); },
];
G['Simplification'] = (r, i, c) => { return TSM[i % TSM.length](r, i, c); };

const TDI = [
    (r, i, c) => { const d = {}; const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']; days.forEach(dy => { d[dy] = c.ri(r, 40, 120) * 10; }); const tot = days.reduce((s, dy) => s + d[dy], 0);
      return c.buildMCQ({ r, stem: 'A shop\'s daily sales (units): ' + days.map(dy => dy + ' = ' + d[dy]).join(', ') + '. What is the total sales for the 5 days?', right: String(tot), wrong: [String(tot + 10), String(Math.round(tot / 5)), String(tot - 20)], explanation: 'Total = ' + tot + ' units.', steps: ['Total = ' + days.map(dy => d[dy]).join(' + '), '   = ' + tot + ' units'] }); },
    (r, i, c) => { const d = {}; const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']; days.forEach(dy => { d[dy] = c.ri(r, 40, 120) * 10; }); const tot = days.reduce((s, dy) => s + d[dy], 0); const av = Math.round(tot / 5);
      return c.buildMCQ({ r, stem: 'Sales (units): ' + days.map(dy => dy + ' = ' + d[dy]).join(', ') + '. What is the average daily sales?', right: String(av), wrong: [String(av + 5), String(tot), String(av - 4)], explanation: 'Average = ' + av + ' units.', steps: ['Total = ' + tot, 'Average = ' + tot + ' / 5 = ' + av] }); },
    (r, i, c) => { const a = c.ri(r, 20, 60), b = c.ri(r, 20, 60), cc = c.ri(r, 20, 60); const tot = a + b + cc; const pct = Math.round(a * 100 / tot);
      return c.buildMCQ({ r, stem: 'In a survey, ' + a + ' people liked tea, ' + b + ' liked coffee and ' + cc + ' liked juice. What percent of total respondents liked tea (rounded)?', right: pct + '%', wrong: [(pct + 2) + '%', (pct - 3) + '%', Math.round(tot * 100 / a) + '%'], explanation: pct + '% liked tea.', steps: ['Total = ' + a + ' + ' + b + ' + ' + cc + ' = ' + tot, 'Tea % = ' + a + ' / ' + tot + ' x 100 = ' + pct + '%'] }); },
    (r, i, c) => { const q1 = c.ri(r, 10, 40) * 5, q2 = c.ri(r, 10, 40) * 5, q3 = c.ri(r, 10, 40) * 5, q4 = c.ri(r, 10, 40) * 5; const tot = q1 + q2 + q3 + q4;
      return c.buildMCQ({ r, stem: 'A company\'s quarterly profits (Rs. lakhs): Q1 = ' + q1 + ', Q2 = ' + q2 + ', Q3 = ' + q3 + ', Q4 = ' + q4 + '. Find the annual profit.', right: String(tot), wrong: [String(tot + 5), String(Math.round(tot / 4)), String(tot - 10)], explanation: 'Annual profit = Rs.' + tot + ' lakhs.', steps: [q1 + ' + ' + q2 + ' + ' + q3 + ' + ' + q4 + ' = ' + tot] }); },
    (r, i, c) => { const m1 = c.ri(r, 100, 240), m2 = c.ri(r, 100, 240); const diff = Math.abs(m1 - m2);
      return c.buildMCQ({ r, stem: 'Student A scored ' + m1 + '/250 and Student B scored ' + m2 + '/250. What is the difference in their percentages (rounded)?', right: Math.round(diff * 100 / 250) + '%', wrong: [(Math.round(diff * 100 / 250) + 1) + '%', diff + '%', Math.round(m1 * 100 / 250) + '%'], explanation: 'Difference = ' + Math.round(diff * 100 / 250) + '%.', steps: ['A% = ' + m1 + ' / 250 x 100 = ' + Math.round(m1 * 100 / 250) + '%', 'B% = ' + Math.round(m2 * 100 / 250) + '%', 'Difference = ' + Math.round(diff * 100 / 250) + '%'] }); },
    (r, i, c) => { const p = c.ri(r, 2, 6), q = c.ri(r, 2, 6), s = c.ri(r, 2, 6); const parts = p + q + s; const tot = parts * c.ri(r, 30, 80); const food = Math.round(tot * q / parts);
      return c.buildMCQ({ r, stem: 'A pie chart has Rent = ' + p + ' parts, Food = ' + q + ' parts, Others = ' + s + ' parts. If total expenditure is Rs.' + tot + ', how much is spent on food?', right: 'Rs.' + food, wrong: ['Rs.' + Math.round(tot * p / parts), 'Rs.' + Math.round(tot / parts), 'Rs.' + (food + 40)], explanation: 'Food = Rs.' + food + '.', steps: ['Food parts = ' + q + ' out of ' + parts, 'Food = ' + tot + ' x ' + q + ' / ' + parts, '   = Rs.' + food] }); },
];
G['Data Interpretation'] = (r, i, c) => { return TDI[i % TDI.length](r, i, c); };

const TMN = [
    (r, i, c) => { const l = c.ri(r, 5, 20), b = c.ri(r, 5, 20);
      return c.buildMCQ({ r, stem: 'Find the area of a rectangle with length ' + l + ' cm and breadth ' + b + ' cm.', right: (l * b) + ' cm^2', wrong: [(2 * (l + b)) + ' cm^2', (l + b) + ' cm^2', (l * b + 4) + ' cm^2'], explanation: 'Area = ' + (l * b) + ' cm^2.', steps: ['Area = length x breadth', '   = ' + l + ' x ' + b + ' = ' + (l * b) + ' cm^2'] }); },
    (r, i, c) => { const l = c.ri(r, 5, 20), b = c.ri(r, 5, 20);
      return c.buildMCQ({ r, stem: 'Find the perimeter of a rectangle with length ' + l + ' m and breadth ' + b + ' m.', right: (2 * (l + b)) + ' m', wrong: [(l * b) + ' m', (l + b) + ' m', (2 * l + b) + ' m'], explanation: 'Perimeter = ' + (2 * (l + b)) + ' m.', steps: ['Perimeter = 2 x (length + breadth)', '   = 2 x (' + l + ' + ' + b + ')', '   = ' + (2 * (l + b)) + ' m'] }); },
    (r, i, c) => { const s = c.ri(r, 4, 18);
      return c.buildMCQ({ r, stem: 'Find the area of a square with side ' + s + ' cm.', right: (s * s) + ' cm^2', wrong: [(4 * s) + ' cm^2', (2 * s) + ' cm^2', (s * s + s) + ' cm^2'], explanation: 'Area = ' + (s * s) + ' cm^2.', steps: ['Area = side^2 = ' + s + '^2', '   = ' + (s * s) + ' cm^2'] }); },
    (r, i, c) => { const b = c.ri(r, 6, 20), h = c.ri(r, 4, 16);
      return c.buildMCQ({ r, stem: 'Find the area of a triangle with base ' + b + ' cm and height ' + h + ' cm.', right: (b * h / 2) + ' cm^2', wrong: [(b * h) + ' cm^2', (b + h) + ' cm^2', (b * h / 2 + 3) + ' cm^2'], explanation: 'Area = ' + (b * h / 2) + ' cm^2.', steps: ['Area = 1/2 x base x height', '   = 1/2 x ' + b + ' x ' + h, '   = ' + (b * h / 2) + ' cm^2'] }); },
    (r, i, c) => { const rad = c.pk(r, [7, 14, 21, 28, 35, 42]); const A = Math.round(22 / 7 * rad * rad);
      return c.buildMCQ({ r, stem: 'Find the area of a circle with radius ' + rad + ' cm. (use pi = 22/7)', right: A + ' cm^2', wrong: [(A + 22) + ' cm^2', (2 * rad) + ' cm^2', Math.round(2 * 22 / 7 * rad) + ' cm^2'], explanation: 'Area = ' + A + ' cm^2.', steps: ['Area = pi x r^2 = 22/7 x ' + rad + '^2', '   = 22/7 x ' + (rad * rad), '   = ' + A + ' cm^2'] }); },
    (r, i, c) => { const rad = c.pk(r, [7, 14, 21, 28, 35, 42]); const C = Math.round(2 * 22 / 7 * rad);
      return c.buildMCQ({ r, stem: 'Find the circumference of a circle with radius ' + rad + ' cm. (use pi = 22/7)', right: C + ' cm', wrong: [(C + 2) + ' cm', Math.round(22 / 7 * rad * rad) + ' cm', rad + ' cm'], explanation: 'Circumference = ' + C + ' cm.', steps: ['Circumference = 2 x pi x r', '   = 2 x 22/7 x ' + rad, '   = ' + C + ' cm'] }); },
];
G['Mensuration'] = (r, i, c) => { return TMN[i % TMN.length](r, i, c); };

module.exports = { G };