// _aptGen4_verbal.js â€” Fully-authored distinct item banks (no template repeats).
// Each topic: BANK_E[50], BANK_M[50], BANK_H[50] = 150 genuinely different questions.
// Item: [stem, right, w1, w2, w3, explanation]. seeder passes i (0..149, continuous across difficulties).
const G = {};
// Notebook-style steps are derived from explanation + answer by buildMCQ's expandSteps,
// so each bank item keeps a terse explanation; the seeder renders steps.
function bankGen(bankE, bankM, bankH, concept) {
  return (r, i, c) => {
    const bank = i < 50 ? bankE : i < 100 ? bankM : bankH;
    const it = bank[i % 50];
    return c.buildMCQ({ r, stem: it[0], right: it[1], wrong: [it[2], it[3], it[4]], explanation: it[5] + (concept ? ' Concept: ' + concept : ''), steps: ['Read the question and identify what is asked', 'Apply: ' + it[5], 'The other options violate this, so "' + it[1] + '" is correct'] });
  };
}
// ---- Antonyms bank: word|opposite|w1|w2|w3|gloss ----
const ANT_P = [
'Accept|Reject|Receive|Admit|Take|to agree to take',
'Ancient|Modern|Old|Antique|Aged|belonging to the very past',
'Arrive|Depart|Reach|Enter|Land|to come to a place',
'Artificial|Natural|Man-made|Plastic|Planted|made by humans',
'Barren|Fertile|Dry|Empty|Arid|land that cannot grow crops',
'Bold|Timid|Daring|Brave|Fearless|confident and daring',
'Bright|Dull|Luminous|Shining|Glowing|giving out much light',
'Cruel|Merciful|Brutal|Savage|Harsh|causing pain without pity',
'Deep|Shallow|Profound|Bottomless|Sunk|going far down',
'Defeat|Victory|Loss|Failure|Drubbing|the act of losing a contest',
'Demand|Supply|Request|Claim|Order|need for goods or work asked',
'Deny|Admit|Refuse|Reject|Contradict|to declare untrue',
'Different|Similar|Unlike|Distinct|Varied|not the same',
'Doubt|Trust|Suspect|Query|Distrust|to feel uncertain about',
'Downward|Upward|Lower|Sunken|Earthward|toward a lower place',
'Encourage|Discourage|Inspire|Urge|Boost|to give hope or confidence',
'Expand|Contract|Enlarge|Extend|Dilate|to become larger',
'Failure|Success|Lapse|Flop|Debacle|lack of success',
'Flexible|Rigid|Supple|Pliant|Elastic|able to bend easily',
'Foreign|Native|Alien|Overseas|External|belonging to another country',
'Scarce|Abundant|Plentiful|Ample|Copious|in short supply',
'Guilty|Innocent|Culpable|Blameworthy|Convicted|responsible for a wrong',
'Harmony|Discord|Agreement|Balance|Unity|pleasing combination',
'Rigid|Flexible|Stiff|Firm|Hard-set|not bending',
'Include|Exclude|Involve|Contain|Embrace|to take in as part of',
'Inferior|Superior| Lesser|Lower|Subpar|lower in rank or quality',
'Innocent|Guilty|Blameless|Pure|Naive|not guilty of a crime',
'Inside|Outside|Interior|Within|Indoor|the inner part or side',
'Junior|Senior|Younger|Lower|Minor|lower in standing or age',
'Liberty|Bondage|Freedom|Independence|Autonomy|state of being free',
'Major|Minor|Chief|Primary|Leading|greater in importance',
'Maximum|Minimum|Peak|Utmost|Top|the greatest possible',
'Miniature|Giant|Tiny|Small|Petite|on a very small scale',
'Narrow|Wide|Slim|Tight|Tapered|small in width',
'Obey|Disobey|Follow|Comply|Submit|to do what one is told',
'Optional|Compulsory|Elective|Voluntary|Discretionary|not required',
'Permanent|Temporary|Lasting|Enduring|Abiding|continuing for a long time',
'Vacant|Occupied|Empty|Blank|Unfilled|without an occupant',
'Private|Public|Personal|Secret|Confidential|belonging to one person or group',
'Profit|Loss|Gain|Earnings|Surplus|money gained in business',
'Remember|Forget|Recall|Memorise|Retain|to keep in mind',
'Repair|Damage|Mend|Fix|Restore|to put back in working order',
'Tame|Wild|Domesticated|Gentle|Meek|not dangerous or afraid of people',
'Rural|Urban|Countryside|Pastoral|Agrarian|relating to the countryside',
'Scarcity|Abundance|Shortage|Deficit|Dearth|a state of being in short supply',
'Secure|Endanger|Fasten|Anchor|Bolt|to make safe',
'Simple|Complex|Plain|Easy|Basic|easy to understand or do',
'Sorrow|Joy|Grief|Sadness|Woe|a feeling of deep sadness',
'Strengthen|Weaken|Fortify|Reinforce|Toughen|to make stronger',
'Superior|Inferior|Higher|Senior|Better|higher in rank or quality',
'Temporary|Permanent|Brief|Passing|Transitory|lasting for a limited time',
'Thid|Thick|Wide|Dense|Chunky|incorrect-spelling-row',
'Tighten|Loosen|Fasten|Clamp|Cinch|to make tighter',
'Transparent|Opaque|Clear|Lucid|Sheer|allowing light to pass through',
'Trivial|Significant|Petty|Minor|Slight|of little value',
'Victory|Defeat|Triumph|Win|Conquest|success in a contest',
'Weak|Robust|Frail|Feeble|Fragile|lacking strength',
'Wealth|Poverty|Riches|Affluence|Fortune|an abundance of money',
'Wide|Narrow|Broad|Expansive|Roomy|having great width',
'Wither|Bloom|Shrivel|Dry|Fade|to dry up and shrink',
'Zenith|Nadir|Peak|Apex|Summit|the highest point',
];

// Every item has its own micro-passage; question types rotate: main idea, detail, inference, vocab, tone.
const RC_E = [
  ['Passage: "Bees communicate the location of food through the waggle dance. The angle of the dance shows the direction of the food relative to the sun." What does the waggle dance mainly communicate?', 'Where food is located', 'How fast bees fly', 'Why bees make honey', 'When bees sleep', 'The passage states the dance shows the location (direction) of food.'],
  ['Passage: "The printing press, invented by Gutenberg around 1440, made books cheap for the first time. Soon literacy rates across Europe began to rise." Why did literacy rise after 1440?', 'Books became affordable', 'Schools were banned', 'Paper was invented', 'Kings ordered reading', 'Cheap books (printing press) made reading material accessible, so literacy rose.'],
  ['Passage: "Mangrove trees survive in salty water by filtering out most of the salt through their roots." How do mangroves handle salt?', 'Their roots filter it out', 'They store it in leaves', 'They avoid salty water', 'They drink rain only', 'The passage directly says roots filter out most of the salt.'],
  ['Passage: "Riya practised free throws every evening for a month. By the end, her success rate doubled." What changed for Riya?', 'Her shooting success rate', 'Her height', 'Her team', 'Her diet', 'The passage says her success rate doubled after a month of practice.'],
  ['Passage: "Solar panels convert sunlight directly into electricity without any moving parts." A key feature of solar panels is that they:', 'Have no moving parts', 'Need petrol', 'Work only at night', 'Store wind energy', 'The passage highlights direct conversion without moving parts.'],
  ['Passage: "The library closes early on Fridays because the staff clean the shelves after 5 pm." Why does the library close early on Fridays?', 'Staff clean shelves after 5 pm', 'Readers never come', 'Books are printed then', 'Power is switched off', 'The passage gives the reason explicitly: post-5pm shelf cleaning.'],
  ['Passage: "Camels can lose up to 30% of their body weight in water and still survive." What is special about camels?', 'They tolerate big water loss', 'They never drink', 'They store water in fur', 'They hate deserts', 'The passage states camels survive losing 30% body weight as water.'],
  ['Passage: "Amit left his umbrella at home. By noon, the sky was grey and heavy with rain." What can be inferred about Amit at noon?', 'He may get wet', 'He bought a coat', 'He stayed home', 'He loves rain', 'Grey rain-heavy sky plus no umbrella implies he might get wet; other options are unstated.'],
  ['Passage: "The museum offers free entry to students on Wednesdays to encourage young visitors." Why does the museum allow free student entry?', 'To attract young visitors', 'To reduce staff', 'To sell paintings', 'To close earlier', 'The passage states the purpose: encouraging young visitors.'],
  ['Passage: "The new bridge cut travel time between the two towns from two hours to forty minutes." What was the travel time before the bridge?', 'Two hours', 'Forty minutes', 'One hour', 'Three hours', 'The passage says travel used to take two hours before the bridge.'],
  ['Passage: "Honey never spoils because its low moisture and high acidity stop bacteria from growing." Why does honey last so long?', 'Bacteria cannot grow in it', 'It is kept cold', 'It is mostly sugar', 'Bees seal each jar', 'Low moisture plus high acidity stop bacterial growth, per the passage.'],
  ['Passage: "Earthquakes cannot be predicted accurately, but buildings can be designed to sway safely." What is possible according to the passage?', 'Designing quake-safe buildings', 'Predicting exact quake dates', 'Stopping quakes forever', 'Emptying cities weekly', 'Prediction is not possible, but safe building design is, per the passage.'],
  ['Passage: "The chef tasted the soup and frowned. Without a word, he reached for the salt." What can be inferred?', 'The soup lacked salt', 'The soup was perfect', 'He hated cooking', 'The pot was empty', 'Frown plus reaching for salt implies the soup needed salt.'],
  ['Passage: "Bamboo can grow up to 90 cm in a single day, faster than almost any other plant." What is notable about bamboo?', 'Its very fast growth', 'Its sweet fruit', 'Its deep roots', 'Its blue flowers', 'The passage highlights bamboo growing up to 90 cm a day.'],
  ['Passage: "Tickets bought online cost 50 rupees less than tickets bought at the gate." How can a visitor save money?', 'Buying tickets online', 'Buying at the gate', 'Coming on Monday', 'Bringing a group', 'Online tickets are 50 rupees cheaper, per the passage.'],
  ['Passage: "When the alarm rang, the students stopped writing and put down their pens." What had most likely just ended?', 'An exam or test', 'A lunch break', 'A cricket match', 'A music class', 'Writing plus alarm plus stopping suggests an exam just ended.'],
  ['Passage: "Owls hunt at night because their eyes and ears are adapted to darkness." Why do owls hunt at night?', 'Their senses suit darkness', 'They fear daylight hunters', 'Prey is always asleep', 'They cannot fly by day', 'The passage says their eyes and ears are adapted to darkness.'],
  ['Passage: "The train to Delhi was delayed by heavy fog for three hours." What caused the delay?', 'Heavy fog', 'A broken engine', 'A strike', 'Water on the tracks', 'The passage names heavy fog as the cause.'],
  ['Passage: "Recycling one aluminium can saves enough energy to run a TV for three hours." What does the passage highlight?', 'Energy saved by recycling', 'The cost of new TVs', 'The lifespan of cans', 'How long TVs last', 'It compares one recycled can to three hours of TV energy.'],
  ['Passage: "Karan saved 500 rupees each month for a year to buy a bicycle." How much did Karan save in total?', '6000 rupees', '500 rupees', '5000 rupees', '1200 rupees', '500 x 12 months = 6000 rupees.'],
  ['Passage: "The old map showed a river where the stadium now stands." What does the passage compare?', 'A past and a present feature', 'Two stadiums', 'Two rivers', 'Two cities', 'It contrasts the old river location with the present stadium.'],
  ['Passage: "Antibiotics treat bacterial infections but do nothing against viruses." What is true about antibiotics?', 'They are useless against viruses', 'They cure all fevers', 'They kill viruses fast', 'They prevent colds', 'The passage states antibiotics do not work on viruses.'],
  ['Passage: "Priya waved from the platform as the train slowly pulled away." Where was Priya most likely standing?', 'On the station platform', 'Inside the train', 'On a bridge', 'At home', 'She waved from the platform as the train left, so she was on the platform.'],
  ['Passage: "The bakery opens at 6 am so that fresh bread is ready for early customers." Why does the bakery open early?', 'To serve fresh bread early', 'To clean the ovens', 'To train new staff', 'To close sooner', 'The passage gives the purpose: fresh bread for early customers.'],
];
// ---- pipe-bank parser ----
const parsePipe = (arr) => arr.map(s => { const p = s.split('|').map(x => x.trim()); return { w: p[0], a: p[1], w1: p[2], w2: p[3], w3: p[4], g: p[5] }; });
// ---- Synonyms & Antonyms: pipe-coded bank word|answer|w1|w2|w3|gloss (each item = distinct word) ----
const SYN_P = [
'Abandon|Forsake|Keep|Cherish|Retain|to leave completely',
'Brave|Valiant|Timid|Weak|Foolish|showing courage',
'Calm|Serene|Stormy|Loud|Rough|peaceful and untroubled',
'Deceive|Mislead|Guide|Reveal|Assist|to make someone believe what is not true',
'Eager|Avid|Apathetic|Reluctant|Idle|keen and enthusiastic',
'Famous|Renowned|Unknown|Obscure|Hidden|known by many people',
'Generous|Benevolent|Stingy|Greedy|Selfish|willing to give freely',
'Honest|Truthful|Crafty|Sly|False|free from deceit',
'Idle|Inactive|Busy|Alert|Swift|not working or in use',
'Joyful|Elated|Gloomy|Somber|Bitter|feeling great happiness',
'Kind|Compassionate|Cruel|Harsh|Brutal|caring about others',
'Lazy|Indolent|Diligent|Keen|Brisk|unwilling to work',
'Mighty|Potent|Feeble|Frail|Delicate|possessing great power',
'Neat|Tidy|Cluttered|Messy|Sloppy|clean and orderly',
'Obvious|Evident|Unclear|Doubtful|Hidden|easily seen or understood',
'Polite|Courteous|Rude|Crude|Blunt|showing good manners',
'Quiet|Silent|Noisy|Clamorous|Boisterous|making little or no sound',
'Rich|Affluent|Poor|Needy|Barren|having much wealth',
'Sad|Sorrowful|Cheerful|Gleeful|Buoyant|feeling unhappiness',
'Tired|Weary|Fresh|Vigorous|Rested|in need of rest',
'Useful|Beneficial|Useless|Harmful|Vain|serving a purpose well',
'Yield|Surrender|Relinquish|Cede|Forgo|to give up under pressure',
'Warn|Caution|Ignore|Invite|Praise|to advise of danger',
'Zealous|Ardent|Indifferent|Lukewarm|Cold|full of enthusiasm',
'Angry|Irate|Pleased|Calm|Mild|feeling strong displeasure',
'Beautiful|Comely|Unsightly|Drab|Plain|very pleasing to see',
'Careful|Prudent|Reckless|Hasty|Careless|giving close attention to avoid harm',
'Dangerous|Perilous|Secure|Benign|Tame|likely to cause harm',
'Easy|Facile|Arduous|Stiff|Onerous|needing little effort',
'Fat|Corpulent|Slim|Lean|Svelte|having much flesh',
'Gift|Present|Penalty|Debt|Loan|a thing given willingly',
'Happy|Content|Miserable|Sullen|Glum|feeling pleasure',
'Important|Crucial|Trivial|Minor|Petty|of great value or effect',
'Joke|Quip|Sermon|Lecture|Scolding|something said to amuse',
'Loyal|Faithful|Treacherous|Fickle|Apostate|firm in support',
'Move|Shift|Halt|Anchor|Fix|to change position',
'New|Novel|Stale|Antique|Aged|recently made',
'Old|Aged|Fresh|Infant|Budding|having lived long',
'Poor|Destitute|Wealthy|Opulent|Flushed|lacking money',
'Quick|Rapid|Sluggish|Lingering|Crawling|moving fast',
'Rare|Scarce|Plentiful|Common|Abundant|not found often',
'Strong|Sturdy|Frail|Weakly|Wobbly|having physical power',
'True|Accurate|False|Faked|Skewed|correct or factual',
'Wise|Sagacious|Foolish|Shallow|Vacant|showing good judgment',
'Young|Juvenile|Elderly|Withered|Faded|in an early stage of life',
'Begin|Commence|Conclude|Suspend|Cease|to start',
'Choose|Select|Reject|Discard|Refuse|to pick from options',
'Destroy|Demolish|Restore|Preserve|Salvage|to end the existence of',
'Explain|Elucidate|Obscure|Muddle|Confound|to make clear by giving details',
'Forgive|Pardon|Condemn|Penalise|Blame|to stop being angry at an offence',
'Help|Aid|Hinder|Obstruct|Thwart|to make easier for someone',
'Imitate|Mimic|Invent|Originate|Deviate|to copy behaviour or style',
'Join|Unite|Sever|Divide|Part|to link together',
'Kill|Slay|Revive|Heal|Cure|to cause death',
'Look|Gaze|Glance-away|Ignore|Overlook|to direct the eyes toward',
'Make|Fabricate|Dismantle|Unravel|Nullify|to form by putting parts together',
'Notice|Observe|Disregard|Neglect|Skim|to watch carefully',
'Open|Unlock|Shut|Latch|Bolt|to allow access or passage',
'Praise|Extol|Belittle|Ridicule|Mock|to express warm approval',
'Question|Query|Answer|Reply|Assert|to ask about something',
'Reduce|Diminish|Amplify|Expand|Extend|to make smaller or less',
'Show|Demonstrate|Conceal|Camouflage|Screen|to allow to be seen',
'Tell|Narrate|Withhold|Suppress|Censor|to communicate by words',
'Use|Utilise|Ignore|Waste|Squander|to employ for a purpose',
'Walk|Stroll|Sprint|Dash|Rush|to move on foot',
'Xerox|Photocopy|Original|Manuscript|Draft|to copy using a machine',
'Yell|Shriek|Whisper|Murmur|Mumble|to utter a loud sharp cry',
'Zoom|Whizz|Creep|Trudge|Lumber|to move very quickly',
'Abundant|Plentiful|Sparse|Scanty|Meagre|existing in large quantities',
'Bizarre|Grotesque|Ordinary|Commonplace|Vanilla|very strange',
'Candid|Forthright|Evasive|Guarded|Sly|truthful and straightforward',
'Diligent|Assiduous|Negligent|Lax|Desultory|working with care and effort',
'Eloquent|Articulate|Inarticulate|Tongue-tied|Halting|fluent and persuasive in speech',
'Frugal|Thrifty|Extravagant|Profligate|Wasteful|careful with money',
'Gracious|Cordial|Surly|Sullen|Churlish|kind and courteous',
'Humble|Modest|Arrogant|Haughty|Proud|not proud about oneself',
'Immense|Colossal|Microscopic|Puny|Slight|extremely large',
'Jubilant|Exultant|Despondent|Crestfallen|Downcast|showing great joy',
'Lucid|Intelligible|Obscure|Muddled|Foggy|clear and easy to understand',
'Meticulous|Painstaking|Slapdash|Cursory|Offhand|showing great attention to detail',
'Notorious|Ill-famed|Celebrated|Esteemed|Revered|famous for something bad',
'Obstinate|Stubborn|Yielding|Compliant|Tractable|refusing to change opinion',
'Placid|Tranquil|Agitated|Turbulent|Restless|calm and not easily upset',
'Quaint|Charming-old|Modern|Sleek|Futuristic|attractively unusual or old-fashioned',
'Resilient|Tenacious|Fragile|Brittle|Flimsy|able to recover quickly',
'Serene|Placid|Frenzied|Frantic|Harried|free from disturbance',
'Tenacious|Persistent|Yielding|Fickle|Irresolute|holding firmly to a course',
'Ubiquitous|Omnipresent|Scarce|Isolated|Sequestered|present everywhere',
'Vivid|Graphic|Dull|Faint|Hazy|producing strong clear images',
'Wary|Vigilant|Reckless|Careless|Unwary|feeling or showing caution',
'Yearn|Pine|Loathe|Scorn|Spurn|to long for something',
];

// ---- One Word Substitution bank: phrase|oneword|w1|w2|w3|gloss ----
const OWS_P = [
'One who loves books|Bibliophile|Bibliography|Librarian|Encyclopaedia|book + philos (loving)',
'A person who writes his life story|Autobiographer|Biographer|Novelist|Essayist|auto = self',
'One who is present everywhere|Omnipresent|Omnipotent|Omniscient|Omnivorous|omni = all',
'One who knows everything|Omniscient|Omnipresent|Omnipotent|Omnivorous|omni + scire (to know)',
'Murder of a king|Regicide|Homicide|Genocide|Fratricide|regi = king, cide = kill',
'Murder of a brother|Fratricide|Regicide|Patricide|Suicide|frater = brother',
'Murder of a father|Patricide|Matricide|Fratricide|Regicide|pater = father',
'Murder of a mother|Matricide|Patricide|Fratricide|Infanticide|mater = mother',
'Murder of a large group|Genocide|Homicide|Regicide|Suicide|genos = race',
'Killing of oneself|Suicide|Homicide|Patricide|Genocide|sui = self',
'A government by the people|Democracy|Monarchy|Aristocracy|Autocracy|demos = people, kratos = rule',
'A government by one person|Autocracy|Democracy|Theocracy|Oligarchy|autos = self',
'A government by priests|Theocracy|Democracy|Bureaucracy|Plutocracy|theos = god',
'A government by the rich|Plutocracy|Theocracy|Democracy|Aristocracy|ploutos = wealth',
'A government by officials|Bureaucracy|Democracy|Theocracy|Mobocracy|bureau = desk',
'A speech made without preparation|Extempore|Rhetoric|Monologue|Dialogue|ex tempore = out of the moment',
'A speech to oneself|Soliloquy|Dialogue|Prologue|Epilogue|solus = alone, loqui = speak',
'Words written on a tomb|Epitaph|Epigram|Elegy|Epilogue|epi + taphos (tomb)',
'A poem of mourning|Elegy|Ode|Sonnet|Ballad|from elegos',
'A short witty saying|Epigram|Epitaph|Elegy|Anthology|epi + gramma',
'A collection of poems|Anthology|Dictionary|Encyclopaedia|Lexicon|anthos = flower',
'A place where bees are kept|Apiary|Aviary|Aquarium|Granary|apis = bee',
'A place where birds are kept|Aviary|Apiary|Stable|Kennel|avis = bird',
'A place where money is coined|Mint|Tannery|Foundry|Refinery|from moneta',
'A place where grains are stored|Granary|Apiary|Arsenal|Dock|granum = grain',
'A place where weapons are stored|Arsenal|Granary|Godown|Depot|dar-as-sinaah (workshop)',
'A place where animals are slaughtered|Abattoir|Sanctuary|Aviary|Kennel|from abattre',
'A home for dogs|Kennel|Stable|Sty|Byre|from kenel',
'A home for horses|Stable|Kennel|Sty|Pen|from stabilis',
'A home for pigs|Sty|Byre|Kennel|Stable|from stigu',
'A home for a lion|Den|Sty|Stable|Pen|from denu',
'A home for a bee|Hive|Burrow|Den|Nest|from burgh',
'A person who eats too much|Glutton|Gourmet|Vegetarian|Epicure|from gluttire',
'A person who deals in cloth|Draper|Grocer|Chandler|Furrier|from drap',
'A person who sells candles|Chandler|Draper|Hawker|Vintner|from chandelle',
'A person who makes barrels|Cooper|Carpenter|Smith|Potter|from cupa (cask)',
'A person who works in metal|Smith|Cooper|Mason|Potter|from smitan',
'A person who makes pots|Potter|Smith|Cooper|Glazier|from pot',
'A person who fits glass|Glazier|Potter|Smith|Plumber|from glaz',
'A person who fits pipes|Plumber|Glazier|Electrician|Carpenter|plumbum = lead',
'A person who builds with stone|Mason|Bricklayer|Architect|Surveyor|from macio',
'A person who cuts hair|Barber|Stylist|Tailor|Vendor|barba = beard',
'A person who treats teeth|Dentist|Optician|Surgeon|Physician|dens = tooth',
'A person who treats the mind|Psychiatrist|Cardiologist|Neurologist|Physician|psyche = mind',
'A person who studies stars|Astronomer|Astrologer|Cosmonaut|Geologist|astron = star',
'A person who travels in space|Astronaut|Astronomer|Aeronaut|Aquanaut|astron + nautes',
'A person who travels to work daily|Commuter|Tourist|Emigrant|Vagrant|from commute',
'A person who leaves their country|Emigrant|Immigrant|Tourist|Resident|e- + migrare',
'A person who settles in a new country|Immigrant|Emigrant|Native|Guide|in- + migrare',
'A person forced to leave home|Exile|Emigrant|Tourist|Native|from exilium',
'A person who flees to safety|Refugee|Exile|Emigrant|Vagrant|from refuge',
'A person with no fixed home|Nomad|Settler|Refugee|Landlord|nomas = wandering',
'A person new to a job|Novice|Veteran|Expert|Master|novicius = new',
'A person with long experience|Veteran|Novice|Apprentice|Trainee|veteranus = old',
'A person learning a trade|Apprentice|Veteran|Master|Mentor|aprendre = to learn',
'A person who guides and advises|Mentor|Apprentice|Novice|Junior|from Mentor (guide character)',
'A person who speaks two languages|Bilingual|Monolingual|Polyglot|Illiterate|bi + lingua',
'A person who speaks many languages|Polyglot|Bilingual|Monolingual|Illiterate|poly + glotta',
'A person who cannot read or write|Illiterate|Literate|Erudite|Scholar|il- + littera',
'A person who is highly educated|Erudite|Illiterate|Novice|Layman|eruditus = instructed',
'A person who gives up worldly life|Ascetic|Aesthetic|Atheist|Anarchist|asketes = one who trains',
'A person who denies the existence of God|Atheist|Agnostic|Theist|Fanatic|a- + theos',
'A person who doubts whether God exists|Agnostic|Atheist|Theist|Fanatic|a- + gnosis',
'A person who wants to destroy all government|Anarchist|Monarchist|Patriot|Loyalist|an- + arkhos',
'A person who loves his country|Patriot|Traitor|Anarchist|Expatriate|patria = fatherland',
'A person who betrays his country|Traitor|Patriot|Loyalist|Partisan|tradere = to hand over',
'A person living outside his own country|Expatriate|Patriot|Repatriate|Native|ex + patria',
'A person who returns to his own country|Repatriate|Expatriate|Emigrant|Nomad|re- + patria',
'A medicine that counteracts poison|Antidote|Antibiotic|Anaesthetic|Sedative|anti + didonai',
'A drug that causes sleep|Sedative|Stimulant|Antidote|Vaccine|sedare = to calm',
'A substance that protects against disease|Vaccine|Sedative|Stimulant|Toxin|vacca = cow',
'A drug that deadens feeling|Anaesthetic|Antidote|Vaccine|Tonic|an- + aisthesis',
'A medicine that restores vigour|Tonic|Sedative|Poison|Toxin|tonikos = stretching',
'A poisonous substance|Toxin|Tonic|Vaccine|Nutrient|toxikon = poison for arrows',
'A sudden attack of illness|Seizure|Cure|Remedy|Recovery|from saisir',
'A return of illness after recovery|Relapse|Seizure|Recovery|Regimen|re- + lapsus',
'The gradual return to health|Convalescence|Relapse|Fatigue|Insomnia|con + valescere',
'Habitual sleeplessness|Insomnia|Somnambulism|Narcolepsy|Fatigue|in- + somnus',
'Walking in ones sleep|Somnambulism|Insomnia|Somniloquy|Narcolepsy|somnus + ambulare',
'Talking in ones sleep|Somniloquy|Somnambulism|Insomnia|Silence|somnus + loqui',
'A sudden attack of deep sleep|Narcolepsy|Insomnia|Somnambulism|Apnoea|nark + lepsis',
'The story of someones life written by another|Biography|Autobiography|Anthology|Novel|bios + graphein',
'The origin and history of a word|Etymology|Entomology|Philology|Syntax|etymon = true sense',
'The scientific study of insects|Entomology|Etymology|Ornithology|Zoology|entomon = insect',
'The scientific study of birds|Ornithology|Entomology|Etymology|Botany|ornis = bird',
'The study of the mind and behaviour|Psychology|Physiology|Philology|Sociology|psyche + logos',
'The study of fossils of ancient life|Palaeontology|Geology|Zoology|Anthropology|palaios + onta',
'The exploration and study of caves|Speleology|Geology|Zoology|Topology|spelaion = cave',
'The study or collection of coins|Numismatics|Philately|Archaeology|Ecology|nomisma = coin',
'The collection and study of stamps|Philately|Numismatics|Philology|Antiquarian|phil + ateleia',
'The study of languages and literature|Philology|Philately|Numismatics|Psychology|phil + logos',
'A word formed from initial letters|Acronym|Antonym|Synonym|Homonym|acr = tip',
'A word opposite in meaning to another|Antonym|Synonym|Acronym|Homonym|anti + onoma',
'A word identical in meaning to another|Synonym|Antonym|Homophone|Acronym|syn + onoma',
'A word that sounds like another but differs in meaning|Homophone|Synonym|Antonym|Acronym|homos + phone',
'A yearly record of events|Almanac|Atlas|Directory|Gazette|from almanakh',
'A book of maps|Atlas|Almanac|Dictionary|Encyclopaedia|from Atlas (titan)',
'A list of names and addresses|Directory|Atlas|Almanac|Register|dirigere = to direct',
'A government by the worst citizens|Kakistocracy|Aristocracy|Democracy|Theocracy|kakistos = worst',
'A government by women|Gynarchy|Monarchy|Oligarchy|Polyarchy|gyne = woman',
'Rule by the noble class|Aristocracy|Autocracy|Democracy|Theocracy|aristos = best (nobility)',
'A country ruled by a king or queen|Monarchy|Republic|Colony|Province|monos + arkhein',
'A state without a ruler in lawlessness|Anarchy|Monarchy|Democracy|Bureaucracy|an- + arkhein',
'Total end of an organisation|Disbandment|Extension|Expansion|Revival|dis- + band',
'Going back on ones word|Recantation|Declaration|Affirmation|Avowal|re- + cantare',
'That which cannot be corrected|Incorrigible|Corrigible|Legible|Readable|in- + corrigere',
'That which cannot be believed|Incredible|Credible|Legible|Audible|in- + credere',
'That which cannot be read|Illegible|Legible|Incredible|Eligible|il- + legere',
'That which cannot be heard|Inaudible|Audible|Legible|Visible|in- + audire',
'That which cannot be seen|Invisible|Visible|Audible|Tangible|in- + videre',
'That which cannot be conquered|Invincible|Vincible|Invisible|Victorious|in- + vincere',
'That which cannot be avoided|Inevitable|Avoidable|Inescapable|Irritable|in- + evitare',
'That which cannot be explained|Inexplicable|Explicable|Invincible|Illiterate|in- + explicare',
'That which cannot be practised|Impracticable|Practicable|Inevitable|Invisible|im- + practicare',
'That which cannot be moved|Immovable|Movable|Mobile|Mutable|im- + movere',
'That which cannot be erased|Indelible|Delible|Erasable|Legible|in- + delere',
'That which cannot be pardoned|Unpardonable|Pardonable|Legible|Plausible|un- + pardon',
'That which cannot be repaired|Irreparable|Reparable|Indelible|Incurable|ir- + reparare',
'A person who shows off his learning|Pedant|Scholar|Mentor|Erudite|pedante = teacher (mock sense)',
'A person who is extremely careful with money|Miser|Spender|Investor|Philanthropist|from miser',
'A person who donates generously|Philanthropist|Miser|Misogynist|Egoist|phil + anthropos',
'A person who hates mankind|Misanthrope|Philanthropist|Patriot|Optimist|misos + anthropos',
'A person who is new to a profession and learns from a senior|Protege|Patron|Mentor|Veteran|proteger = to protect',
'A person who supports another in a powerful position|Patron|Protege|Client|Tenant|patronus = protector',
'A person who abandons religion|Apostate|Convert|Devotee|Proselyte|apostates = a runaway',
'A person newly converted to a religion|Proselyte|Apostate|Heretic|Atheist|proselytos = newcomer',
'A person who holds beliefs opposite to the church|Heretic|Proselyte|Devotee|Canon|hairetikos = able to choose',
'A place where religious hermits live alone|Hermitage|Monastery|Convent|Church|from heremite',
'A building where monks live|Monastery|Hermitage|Cathedral|Chapel|monos = alone',
'A building where nuns live|Convent|Monastery|Hermitage|Rectory|from conventus',
'A very large and grand church|Cathedral|Chapel|Convent|Shrine|from cathedra (seat of a bishop)',
'A holy place dedicated to a saint|Shrine|Cathedral|Chapel|Mosque|from scrin',
'Words similar in sound but different in spelling and meaning|Homonyms|Antonyms|Acronyms|Pseudonyms|homo + onoma',
'A false name used by an author|Pseudonym|Homonym|Antonym|Acronym|pseudo + onoma',
'A name used instead of the real name to hide identity|Alias|Pseudonym|Nickname|Epithet|alias = otherwise',
'A descriptive phrase added to a persons name|Epithet|Alias|Pseudonym|Monogram|epitheton = added',
'A design made of joined initials|Monogram|Epithet|Alias|Pseudonym|mono + gramma',
'Words inscribed on a building or coin|Legend|Monogram|Epitaph|Epigram|legere = to read',
'The closing part of a speech|Peroration|Prologue|Interlude|Epilogue|per + oratio',
'An introductory part of a poem or play|Prologue|Epilogue|Peroration|Monologue|pro + logos',
'A short performance between acts|Interlude|Prologue|Epilogue|Intermission|inter + ludus',
'A break between parts of a play or match|Intermission|Interlude|Epilogue|Recession|inter + mittere',
'A payment for damage done|Indemnity|Insurance|Premium|Instalment|in- + demnis (without harm)',
'A regular payment made to an insurance company|Premium|Indemnity|Dividend|Subsidy|from praemium',
'A sum of money given to support a public cause|Subsidy|Premium|Dividend|Alimony|from subsidium',
'Money paid to a former spouse after divorce|Alimony|Subsidy|Premium|Wages|from alimonia (nourishment)',
'A fixed regular payment for work|Salary|Alimony|Donation|Bounty|from salarium',
'A payment made in one go as a reward|Lump sum|Instalment|Salary|Stipend|from lump',
'A small payment for a service|Gratuity|Salary|Stipend|Wage|gratus = pleasing',
'A fixed allowance paid to a student|Stipend|Gratuity|Premium|Alimony|stips = a gift',
'Money paid back for expenses|Reimbursement|Stipend|Dividend|Perquisite|re- + imburse',
'A benefit enjoyed beyond ones salary|Perquisite|Reimbursement|Liability|Expenditure|per + quaerere',
];
// ---- Idioms & Phrases bank: idiom|meaning|w1|w2|w3|mini-example ----
const IDM_P = [
'To bury the hatchet|To make peace and end a quarrel|To hide a weapon|To dig the ground|To start a fight|After years of rivalry the two firms buried the hatchet.',
'To smell a rat|To suspect something wrong|To find a bad smell|To see a rat|To catch a thief|I smelt a rat when he refused to show the receipt.',
'To hit the nail on the head|To do exactly the right thing|To strike a nail|To hurt oneself|To hammer hard|Your comment hit the nail on the head.',
'To let the cat out of the bag|To reveal a secret|To free an animal|To create confusion|To tell a lie|He let the cat out of the bag about the surprise party.',
'To burn the midnight oil|To work or study late into the night|To waste fuel|To sleep early|To light lamps|She burnt the midnight oil before the exam.',
'To be in hot water|To be in trouble|To bathe in warm water|To be angry|To feel cold|He is in hot water for missing the deadline.',
'To see eye to eye|To agree completely|To stare at each other|To meet someone|To quarrel|The two managers see eye to eye on the plan.',
'To break the ice|To start a conversation with strangers|To shatter glass|To end a friendship|To skate fast|A small joke broke the ice at the meeting.',
'To be all ears|To listen eagerly|To have big ears|To be deaf|To speak loudly|Tell me the whole story, I am all ears.',
'To keep an eye on|To watch carefully|To close the eyes|To sleep|To look angrily|Please keep an eye on my luggage.',
'A blessing in disguise|A hidden benefit from a bad event|A curse|A religious ceremony|A costume party|Losing that job was a blessing in disguise.',
'Once in a blue moon|Very rarely|Every month|At night|Frequently|He visits us once in a blue moon.',
'To bite the bullet|To face a painful situation bravely|To chew metal|To eat fast|To shoot someone|I bit the bullet and apologised.',
'A piece of cake|Something very easy|A dessert|A small share|A birthday treat|The test was a piece of cake for her.',
'To spill the beans|To disclose a secret|To waste food|To cook badly|To drop something|Do not spill the beans before the announcement.',
'To go the extra mile|To make additional effort|To jog farther|To travel abroad|To take rest|Our team always goes the extra mile for clients.',
'To cry over spilt milk|To regret what cannot be undone|To clean a mess|To waste milk|To weep loudly|It is no use crying over spilt milk.',
'To beat around the bush|To avoid the main topic|To search a garden|To hit a plant|To speak frankly|Stop beating around the bush and answer me.',
'To read between the lines|To grasp a hidden meaning|To read slowly|To skip lines|To read aloud|Reading between the lines, the notice hints at layoffs.',
'To be on cloud nine|To be extremely happy|To feel dizzy|To fly high|To be confused|She was on cloud nine after the selection.',
'To bite off more than one can chew|To take on more than one can handle|To eat fast|To speak rudely|To chew gum|Taking three jobs at once was biting off more than he could chew.',
'To add fuel to the fire|To make a bad situation worse|To cook food|To light a lamp|To reduce anger|His rude reply added fuel to the fire.',
'At the drop of a hat|Instantly and willingly|After much delay|Reluctantly|In the rain|She helps friends at the drop of a hat.',
'To steal ones thunder|To take credit for someone elses idea|To rob a person|To make loud noise|To break a device|He stole my thunder by announcing my plan first.',
'A white elephant|A costly but useless possession|A rare animal|A holy creature|A cheap gift|That old machine is a white elephant for the factory.',
'To pull someones leg|To tease or joke with someone|To injure a person|To drag someone|To flatter|Relax, I was just pulling your leg.',
'To be under the weather|To feel slightly unwell|To enjoy rain|To be wet|To be angry|He is under the weather today.',
'To take with a grain of salt|To not believe fully|To season food|To accept totally|To taste|Take his boasts with a grain of salt.',
'To move heaven and earth|To try everything possible|To shift mountains|To pray hard|To demolish a building|She moved heaven and earth to save the deal.',
'To turn a deaf ear|To ignore deliberately|To listen carefully|To become deaf|To answer|The committee turned a deaf ear to our plea.',
'To be in the same boat|To share the same situation|To sail together|To build a boat|To compete|We are in the same boat, so let us cooperate.',
'To jump on the bandwagon|To join a popular trend|To climb a cart|To leave a group|To play music|Every brand jumped on the online-sale bandwagon.',
'To get cold feet|To lose courage at the last moment|To feel chilly|To walk barefoot|To fall sick|He got cold feet before the interview.',
'To hit the sack|To go to bed|To pack a bag|To punch a sack|To wake up|I am tired; time to hit the sack.',
'To keep ones fingers crossed|To hope for the best|To gesture rudely|To point at someone|To crack knuckles|I am keeping my fingers crossed for the result.',
'To give someone the cold shoulder|To ignore someone deliberately|To offer a jacket|To greet warmly|To massage|After the quarrel she gave me the cold shoulder.',
'To play second fiddle|To take a subordinate role|To play a duet|To lead a team|To repair an instrument|He refused to play second fiddle to his junior.',
'To throw in the towel|To accept defeat|To wash up|To exercise|To celebrate|After three losses the boxer threw in the towel.',
'To have a finger in every pie|To meddle in every affair|To bake pies|To taste dishes|To eat everywhere|The minister has a finger in every pie.',
'To sit on the fence|To remain neutral|To climb a wall|To sit outside|To take sides|Do not sit on the fence; choose a side.',
'To blow ones own trumpet|To boast about oneself|To play music|To praise others|To announce news|He loves blowing his own trumpet.',
'To be a bed of roses|To be full of comfort|To be thorny|To be a garden|To be flowery|Life is not a bed of roses.',
'To carry coals to Newcastle|To do something needless by taking a thing where it already exists|To mine coal|To burn fuel|To transport goods cheaply|Selling wheat to a farm belt is carrying coals to Newcastle.',
'To make both ends meet|To live within ones income|To join two ropes|To reach a destination|To finish work|Part-time work helps them make both ends meet.',
'To be at daggers drawn|To be openly hostile|To be armed|To collect weapons|To draw pictures|The two partners are at daggers drawn over money.',
'To nip in the bud|To stop at an early stage|To pluck flowers|To smell buds|To plant seeds|The teacher nipped the mischief in the bud.',
'To put the cart before the horse|To do things in the wrong order|To reverse a vehicle|To feed animals|To race carts|Designing before research is putting the cart before the horse.',
'To take the bull by the horns|To face a difficulty boldly|To graze cattle|To escape danger|To wrestle|Take the bull by the horns and confront him.',
'To be a man of straw|A weak and worthless person|A farmer|A scarecrow maker|A rich man|Do not fear him; he is a man of straw.',
'To win laurels|To gain honour|To earn money|To pick leaves|To lose|She won laurels in the national Olympiad.',
'To be in a fix|To be in a difficult position|To be repaired|To be fixed firmly|To be settled|I am in a fix: two exams on the same day.',
'To fish in troubled waters|To profit from others difficulty|To swim well|To catch fish|To rescue people|Traders fished in troubled waters during the shortage.',
'To be a hot potato|A controversial issue|A tasty dish|A cooked vegetable|A warm welcome|The new tax is a political hot potato.',
'To bell the cat|To take the first risky step|To pet a cat|To buy a bell|To escape danger|Someone must bell the cat and complain to the principal.',
'To make a mountain out of a molehill|To exaggerate a small problem|To dig a hill|To clear land|To measure land|You are making a mountain out of a molehill.',
'To leave no stone unturned|To try every possible means|To collect stones|To dig the earth|To destroy evidence|She left no stone unturned to find her documents.',
'To rest on ones laurels|To be satisfied with past success|To sleep in a garden|To feel tired|To lose honour|Do not rest on your laurels; aim higher.',
'To play into the hands of|To act as an enemy wants|To shake hands|To cooperate|To clap|Striking now would play into the hands of our rivals.',
'To be beyond the pale|Outside acceptable limits|Inside a fence|Beyond reach|Very pale|His conduct at the banquet was beyond the pale.',
'To take to task|To rebuke or scold|To accept a duty|To assign work|To praise|The manager took him to task for the delay.',
'To stick to ones guns|To hold ones opinion firmly|To guard weapons|To fire a gun|To surrender|She stuck to her guns despite the criticism.',
'To be in the doldrums|To be depressed or stagnant|To be energetic|To sail fast|To celebrate|Sales have been in the doldrums since winter.',
'To go to the dogs|To decline in quality or fortune|To adopt a pet|To run fast|To improve|The club has gone to the dogs since his exit.',
'To keep the wolf from the door|To avoid starvation|To guard a house|To welcome guests|To hunt|The extra shift keeps the wolf from the door.',
'To feather ones nest|To enrich oneself using position|To build a home|To feed birds|To decorate|The officer feathered his nest with bribes.',
'To kill two birds with one stone|To achieve two results with one act|To hunt birds|To throw stones|To waste effort|Cycling to office kills two birds with one stone.',
'To burn ones fingers|To suffer from a rash action|To touch fire|To cook|To get warm|He burnt his fingers in the stock market.',
'To be a nine days wonder|A short-lived sensation|A weekly event|A nine-day festival|A long story|The scandal was a nine days wonder.',
'To show the white feather|To display cowardice|To surrender flag|To wave hello|To wear a badge|The soldier never showed the white feather.',
'To raise a storm|To cause a big uproar|To predict weather|To fly kites|To clean up|The tweet raised a storm on social media.',
'To be an axe to grind|To have a selfish motive|To sharpen tools|To cut wood|To repair|He has an axe to grind in this dispute.',
'To be at sixes and sevens|To be in confusion or disorder|To count numbers|To play dice|To be precise|The accounts are at sixes and sevens.',
'To fall flat|To fail to impress|To tumble down|To lie down|To succeed|The joke fell flat on the audience.',
'To be an eyesore|Something unpleasant to look at|A spectacle|A mirror|A signal|The unfinished flyover is an eyesore.',
'To play havoc with|To cause widespread damage|To play games|To organise|To repair|The storm played havoc with the crops.',
'To make headway|To make progress|To lose ground|To rest|To retreat|Talks are finally making headway.',
'To be at the eleventh hour|At the last possible moment|At midnight|Early morning|On the 11th|The deal was struck at the eleventh hour.',
'To come off with flying colours|To succeed brilliantly|To paint a flag|To fade away|To fail badly|She came off with flying colours in the mains.',
'To be in a pretty pass|To be in a difficult state|To be scenic|To be well-placed|To pass by|Labour relations have come to a pretty pass.',
'To gain ground|To become more popular|To lose land|To dig soil|To stagnate|The new diet is gaining ground among athletes.',
'To bear the palm|To be the winner|To plant trees|To carry a load|To give up|He bore the palm in the debate finals.',
'To be a storm in a teacup|A small matter blown up|A real cyclone|A heavy rain|A tea party|The outrage was just a storm in a teacup.',
'To have an itch for|To have a strong desire|To scratch skin|To dislike|To be idle|He has an itch for adventure sports.',
'To be a pillar of the community|A leading supportive member|A construction worker|An outsider|A critic|She is a pillar of the community.',
'To put ones foot down|To firmly object|To stumble|To walk fast|To resign|When the price crossed a lakh, father put his foot down.',
'To be in seventh heaven|To be in a state of great joy|To be gloomy|To be nervous|To be far away|He was in seventh heaven after the victory.',
'To smell of the lamp|To show signs of long labour|To be fragrant|To be dark|To be lazy|The essay smells of the lamp; so polished.',
'To pay off old scores|To take revenge|To clear loans|To settle bills|To forgive|The champion paid off old scores this season.',
'To be in the melting pot|Undergoing great change|To be hot|To be cooking|To be settled|The old system is in the melting pot.',
'To be at the zenith|At the highest point|At the bottom|In the middle|At the start|The empire was at its zenith under Akbar.',
'To pay lip service|To express support without action|To speak softly|To compliment|To donate|They only pay lip service to green norms.',
'To run the gauntlet|To face a series of attacks|To run a race|To wear gloves|To escape|The minister ran the gauntlet of sharp questions.',
'To be a damp squib|A disappointing failure|A firework that explodes|A wet cloth|A spark|The launch turned out a damp squib.',
'To turn the corner|To pass a critical point and improve|To take a turn|To get lost|To return|The firm has turned the corner after two loss years.',
'To have too many irons in the fire|To be busy with too many activities|To heat metal|To be careless|To burn fuel|He has too many irons in the fire to focus.',
'To be hard up|To be short of money|To be strict|To be unwell|To be rude|He is hard up till the salary arrives.',
'To be on the anvil|Being prepared or discussed|To be prepared|To be forged badly|To be finished|A new policy is on the anvil.',
'To be in hot pursuit|Chasing closely|To feel warm|To be angry|To be late|The police were in hot pursuit of the van.',
'To hold water|To be sound and valid|To leak|To pour|To drown|His explanation does not hold water.',
'To be all at sea|To be confused|To be swimming|To be sailing|To be sure|I was all at sea during the advanced lecture.',
'To carry the day|To win approval|To lose|To postpone|To shift goods|Her argument carried the day in the board meeting.',
'To have a bee in ones bonnet|To be obsessed with an idea|To keep bees|To be stung|To be angry|He has a bee in his bonnet about punctuality.',
'To make a clean breast of|To confess fully|To clean the chest|To fall ill|To hide facts|He made a clean breast of his mistake.',
'To be at a premium|Scarce and valued highly|To be cheap|To be free|To be ordinary|Parking space is at a premium downtown.',
'To take the wind out of ones sails|To deflate someones confidence|To sail fast|To fan someone|To row|Her sharp reply took the wind out of his sails.',
'To be in the same breath|Said together in comparison|To breathe hard|To whisper|To pause|Do not mention scandal and charity in the same breath.',
'To draw the longbow|To exaggerate in telling stories|To shoot arrows|To stretch a rope|To aim high|Old sailors love drawing the longbow.',
'To bear the brunt of|To suffer the main force of|To carry weight|To be brave|To relax|Small traders bore the brunt of the lockdown.',
'To come to grief|To meet with disaster|To mourn|To injure|To rejoice|The startup came to grief within a year.',
'To be in black and white|In writing|In photography|In darkness|Colourful|I want the offer in black and white.',
'To be a red-letter day|An important memorable day|A holiday|A dull day|A rainy day|The convocation was a red-letter day for him.',
'To see red|To become very angry|To notice colour|To be festive|To blush|Tardiness makes the coach see red.',
'To be a green horn|A naive newcomer|A farmer|An expert|A hunter|As a greenhorn he signed the bad contract.',
'To be in the red|In debt or loss|In profit|In danger|In bloom|The firm has been in the red for three quarters.',
'To be in the pink|In perfect health|In debt|In fashion|In trouble|Grandfather is in the pink of health.',
'To be tickled pink|To be highly amused|To be hurt|To be painted|To be cold|She was tickled pink by the parody.',
'To be born with a silver spoon|Born into wealth|To be a jeweller|To eat fast|To be lucky in love|He was born with a silver spoon in his mouth.',
'To be worth ones salt|To deserve ones pay|To be salty|To be worthless|To be hungry|Any analyst worth her salt would spot the error.',
'To spill the salt|To cause bad luck by accident|To cook|To preserve|To season well|He spilled salt at dinner and joked about luck.',
'To be the salt of the earth|A thoroughly good person|A miner|A sailor|A critic|Our janitor is the salt of the earth.',
'To take something with a pinch of salt|To doubt a claim|To season food|To believe fully|To taste|Take his forecasts with a pinch of salt.',
'To walk on air|To feel elated|To parachute|To feel heavy|To float a boat|After the offer she seemed to walk on air.',
'To be down to earth|To be practical and modest|To dig soil|To be dreamy|To fall down|Despite fame she remains down to earth.',
'To move the goalposts|To change the rules midway|To shift a net|To win a match|To train hard|The client keeps moving the goalposts.',
'To be a game changer|Something that alters the situation decisively|An umpire|A substitute|A defeat|The vaccine was a game changer.',
'To be behind the eight ball|To be in a difficult position|To play pool well|To be early|To be lucky|After the recall, the brand was behind the eight ball.',
'To be on the ball|Alert and competent|To play football|To be lazy|To be lost|Our intern is really on the ball.',
'To throw ones hat in the ring|To enter a contest|To lose a cap|To salute|To retire|She threw her hat in the ring for the post.',
'To pass the baton|To hand over responsibility|To drop a stick|To run slowly|To refuse|The founder passed the baton to the new CEO.',
'To be a dark horse|A little-known competitor who surprises|A racehorse|A villain|A stranger|Rahul is the dark horse of this election.',
'To show ones true colours|To reveal real character|To paint a flag|To change dress|To blush|In crisis he showed his true colours.',
'To be in the limelight|At the centre of attention|Under a lamp|In the garden|Backstage|The young singer is in the limelight.',
'To steal the limelight|To attract attention away from others|To rob a stage|To dim lights|To applaud|The child star stole the limelight.',
'To be a flash in the pan|A brief success soon over|A lasting triumph|A cooking pot|A wildfire|The viral song was a flash in the pan.',
'To be in the offing|Likely to happen soon|Far away|In the sea|Cancelled|A rate cut is in the offing.',
'To be at loggerheads|In strong disagreement|In a queue|In agreement|In a line|The two boards are at loggerheads over fees.',
'To bury ones head in the sand|To ignore an obvious problem|To dig|To sleep|To hide treasure|You cannot bury your head in the sand about debts.',
'To be on thin ice|In a risky situation|To skate well|To be frozen|To be safe|You are on thin ice with the auditor.',
'To have ones hands full|To be very busy|To hold boxes|To be idle|To steal|The nurse had her hands full all night.',
'To get the sack|To be dismissed from a job|To carry a bag|To be hired|To rest|He got the sack for leaking data.',
'To be in the pipeline|Being prepared or in process|To be blocked|In water|Discarded|Two sequels are in the pipeline.',
'To keep ones chin up|To stay brave|To look down|To bow|To sulk|Keep your chin up; results will improve.',
'To be a wet blanket|One who spoils others fun|A warm quilt|A firefighter|A guest of honour|Do not invite him; he is a wet blanket.',
'To be the cream of the crop|The very best part|A dairy item|A harvest tool|Leftovers|These ten are the cream of the crop.',
'To be half-baked|Poorly thought out|Undercooked only|Well-planned|Overdone|The proposal is half-baked; rework it.',
'To be a cog in the machine|An unimportant part of a large system|An engine part|A manager|A creator|He quit feeling like a cog in the machine.',
'To take the cake|To be the most remarkable (often bad)|To bake|To share food|To refuse|Of all excuses, this takes the cake.',
'To be the last straw|The final small burden that breaks patience|A scarecrow|A haystack|A bridge|The extra fee was the last straw.',
'To hold ones horses|To wait and be patient|To groom animals|To ride fast|To race|Hold your horses; the results are not out yet.',
'To burn the candle at both ends|To overwork oneself|To waste wax|To celebrate|To sleep early|Exam month burnt the candle at both ends.',
'To jump the gun|To act before the proper time|To fire a starter pistol|To win a race|To stumble|The headline jumped the gun on the verdict.',
];

// ---- RC_P: passage|question|right|w1|w2|w3 (150 authored micro-passage items) ----
const RC_P = [
'Bees tell other bees where food is by doing a waggle dance. The dance angle points to the food direction.|What does the waggle dance angle show?|The direction of the food|The size of the hive|The age of the bee|The colour of flowers|The angle encodes direction, as stated in the passage.',
'Mangroves survive in salty water because their roots filter out most of the salt.|How do mangroves handle salty water?|Their roots filter out salt|They store salt in leaves|They absorb rain only|They close their roots|The passage says roots filter most of the salt.',
'The printing press made books cheap, so more people learned to read.|Why did more people learn to read after the printing press?|Books became affordable|Schools were built|Ink was invented|Paper was banned|Cheap books are linked to more readers in the passage.',
'Riya practised free throws every evening, and her shooting success rate rose steadily.|What improved due to evening practice?|Her shooting success rate|Her running speed|Her exam scores|Her team size|The passage links evening practice to a rising success rate.',
'Solar panels convert sunlight into electricity and have no moving parts.|A key feature of solar panels is that they|Have no moving parts|Burn fuel quietly|Store wind energy|Need constant oiling|Stated directly in the passage.',
'The bridge was closed for repairs, so commuters used the ferry for two weeks.|Why did commuters use the ferry?|The bridge was closed for repairs|The ferry was faster|Tickets were free|The road was widened|Cause stated in the passage.',
'Desi ghee costs more than refined oil, yet many families buy it for its flavour.|Why do many families buy ghee despite the cost?|For its flavour|For its long shelf life|Because it is cheaper|Because oil is banned|Reason stated in the passage.',
'Ants follow scent trails left by other ants, which is why they march in a line.|Why do ants march in a line?|They follow scent trails|They hate crowds|They fear light|They count steps|Stated in the passage.',
'The museum offers free entry on Mondays, so it is most crowded then.|When is the museum most crowded?|Mondays|Fridays|Sundays|Wednesdays|Free entry on Mondays leads to crowds.',
'Ravi set three alarms because he overslept twice last week.|Why did Ravi set three alarms?|He overslept twice last week|He loves gadgets|His phone is new|His job changed|Reason stated in the passage.',
'Cactus plants store water in their thick stems to survive long dry spells.|How do cacti survive dry spells?|Water stored in thick stems|They shed all leaves daily|They absorb fog at night|They grow deep flowers|Stated in the passage.',
'The train arrived forty minutes late, so Meera missed the opening ceremony.|Why did Meera miss the ceremony?|The train was late|She forgot the date|The venue shifted|She felt ill|Cause stated in the passage.',
'Local honey is sold within days of harvest, so it tastes fresher than imported honey.|Why does local honey taste fresher?|It is sold soon after harvest|It costs more money|It uses added sugar|It is chilled longer|Freshness linked to quick sale in the passage.',
'Pigeons can recognise themselves in mirrors, a rare skill among birds.|What rare skill do pigeons have?|Mirror self-recognition|Singing in tune|Flying at night|Speaking words|Stated in the passage.',
'The library fines are small, yet returns rose sharply after reminders were added.|What caused the sharp rise in returns?|Added reminders|Bigger fines|Longer hours|New books|The passage attributes the rise to reminders, not fine size.',
'Ice floats on water because it is less dense than liquid water.|Why does ice float?|It is less dense than water|It is colder than water|It is lighter in colour|It contains air bubbles only|Density reason stated in the passage.',
'The chef tastes each sauce twice, once while cooking and once before serving.|When does the chef taste each sauce the second time?|Before serving|After customers leave|Before shopping|While chopping|Stated in the passage.',
'Camels have wide feet that spread their weight, so they walk easily on sand.|Why can camels walk easily on sand?|Wide feet spread their weight|They run quickly|They rest often|They carry less|Reason stated in the passage.',
'The shop raises umbrella prices during heavy rain, so sales drop despite demand.|What happens to umbrella sales in heavy rain?|They drop|They double|They stay fixed|They vanish|The passage says sales drop despite demand.',
'Bamboo can grow nearly a metre in a single day under good conditions.|How fast can bamboo grow in a day?|Nearly a metre|A few centimetres|Ten metres|One millimetre|Stated in the passage.',
'Neha keeps a diary in three languages to practise each one daily.|Why does Neha keep a diary in three languages?|To practise each daily|To hide secrets|To save money|To impress friends|Purpose stated in the passage.',
'The app blocks notifications after ten at night to protect users sleep.|Why does the app block late notifications?|To protect users sleep|To save battery|To update itself|To show more ads|Purpose stated in the passage.',
'Old coins from this region show a ship, hinting that trade crossed the sea.|What do the coins hint about trade?|It crossed the sea|It used aeroplanes|It was banned|It used coins only|The ship image hints at sea trade.',
'The doctor advised walking thirty minutes daily, and Arjun stuck to the routine.|What routine did Arjun follow?|Walking thirty minutes daily|Running five kilometres|Swimming weekly|Gym at night|Stated in the passage.',
'Rainwater harvesting tanks on the rooftop supply the garden through summer.|What supplies the garden in summer?|Rooftop harvesting tanks|Bore wells|Tanker trucks|City pipelines|Stated in the passage.',
'The film was shot in one take, which is why the actors rehearsed for months.|Why did actors rehearse for months?|The film was shot in one take|The script kept changing|The director was new|The sets were huge|Reason stated in the passage.',
'Spiders spin silk stronger than steel of the same thickness.|Spider silk compared with steel of equal thickness is|Stronger|Softer|Heavier|Cheaper|Stated in the passage.',
'The courier delivers in the morning, so shops stock shelves by noon.|When do shops stock shelves?|By noon|At midnight|On Sundays|After closing|Sequence stated in the passage.',
'Kite flyers in this town wait for spring winds before holding the festival.|When is the kite festival held?|In spring|In winter|In monsoon|In autumn|Stated in the passage.',
'The teacher used games in class, and attendance climbed within a month.|What happened after games were used?|Attendance climbed|Fees dropped|Uniforms changed|Exams ended|Effect stated in the passage.',
'Octopuses have three hearts, and two of them stop beating while it swims.|How many octopus hearts beat while swimming?|One|Two|Three|None|Two stop, so one keeps beating.',
'The bakery opens at five, so the smell of fresh bread fills the street early.|What fills the street early?|The smell of fresh bread|The sound of traffic|Morning rain|School bells|Stated in the passage.',
'The village pond dries each April, so weddings are planned before then.|When are weddings planned?|Before April|In July|In August|After October|Timing logic stated in the passage.',
'Lions rest up to twenty hours a day and hunt mostly at night.|When do lions hunt mostly?|At night|At noon|At dawn only|In the afternoon|Stated in the passage.',
'The metro added night buses, and late-shift workers stopped walking home.|What changed for late-shift workers?|They stopped walking home|They changed jobs|They bought cars|They moved cities|Effect stated in the passage.',
'Paper made from banana stems needs less water than paper from wood.|Which paper needs less water to make?|Banana-stem paper|Wood paper|Plastic sheets|Cloth rolls|Stated in the passage.',
'The coach benched the captain for one match to teach the team fairness.|Why was the captain benched?|To teach team fairness|He was injured|He was leaving|Fans complained|Purpose stated in the passage.',
'Sea turtles return to nest on the same beach where they hatched.|Where do sea turtles return to nest?|The beach where they hatched|The deepest ocean|Freshwater rivers|Coral caves|Stated in the passage.',
'The power cut hit at six, so dinner was cooked on a gas stove.|How was dinner cooked?|On a gas stove|In a microwave|On an electric hob|In a solar oven|Inference from the power cut.',
'The dictionary app works offline, so it is useful during travel.|Why is the app useful during travel?|It works offline|It is free|It is fast|It is small|Reason stated in the passage.',
'Farmers here rotate crops each season, which keeps the soil healthy.|Why is the soil kept healthy?|Crops are rotated each season|Chemicals are doubled|Fields rest for years|Rain is heavy|Reason stated in the passage.',
'The clock tower chimes every hour, and shops nearby set their time by it.|How do nearby shops set time?|By the tower chimes|By radio news|By phone alarms|By sunrise|Stated in the passage.',
'Handmade soap cures for six weeks before it is packed and sold.|How long does handmade soap cure?|Six weeks|Two days|One year|Ten hours|Stated in the passage.',
'The ferry stops running in fog, so islanders keep extra supplies ready.|Why do islanders keep extra supplies?|Fog stops the ferry|Prices rise daily|Shops close early|Roads flood|Cause stated in the passage.',
'Chess clubs report that players who study endings win more matches.|Which players win more matches?|Those who study endings|Those who move fastest|Those who play daily|Those who open loudly|Stated in the passage.',
'The tailor adds a centimetre extra to every seam for later adjustments.|Why is a centimetre added?|For later adjustments|To use more cloth|To follow fashion|To price higher|Purpose stated in the passage.',
'Windmills in this pass generate most power in June, when gusts peak.|When do the windmills generate most power?|June|January|March|October|Stated in the passage.',
'The school banned phones in corridors, and queue fights fell sharply.|What fell after the phone ban?|Queue fights|Fees|Bus fares|Class hours|Effect stated in the passage.',
'Honey never spoils because its low moisture stops bacteria from growing.|Why does honey never spoil?|Low moisture stops bacteria|It is always frozen|Bees add salt|It contains wax|Reason stated in the passage.',
'The artist paints only at dawn because the light is soft then.|Why does the artist paint at dawn?|The light is soft|The studio is quiet|Paints are cheap|Models arrive|Reason stated in the passage.',
'Elephants can hear low rumbles from several kilometres away through their feet.|How do elephants sense distant rumbles?|Through their feet|Through the trunk|By flapping ears|By lifting tails|Stated in the passage.',
'The river floods each August, so farmers plant on higher ground only.|Why do farmers plant on higher ground?|River floods each August|Soil is richer there|Seeds are cheaper|Labour is closer|Cause stated in the passage.',
'Stars twinkle because Earths atmosphere bends their light unevenly.|Why do stars twinkle?|Atmosphere bends their light|They burn unevenly|They change colour|They spin fast|Reason stated in the passage.',
'The bus runs late on Fridays, so Ravi catches the earlier one that day.|Why does Ravi catch an earlier bus on Friday?|The bus runs late on Fridays|He wakes up early|Traffic is light|Fares drop that day|Cause stated in the passage.',
'The spice loses its flavour after six months, so chefs buy it in small lots.|Why do chefs buy the spice in small lots?|It loses flavour after six months|It costs a lot|It is hard to find|It changes colour|Reason stated in the passage.',
'Snow reflects sunlight, so snowy days feel cooler than clear ones.|Why do snowy days feel cooler?|Snow reflects sunlight|Wind blows stronger|Clouds block heat|Air is thinner|Reason stated in the passage.',
'The market closes at sunset, so vendors pack up before dark.|When do vendors pack up?|Before dark|At sunrise|At noon|On holidays|Closing time logic stated in the passage.',
'Beavers build dams that create ponds, which protect them from predators.|What protects beavers from predators?|Ponds created by dams|Their loud calls|Their sharp teeth|Their fast running|Stated in the passage.',
'The phone heats up during long calls, so the user takes breaks between them.|Why does the user take breaks?|Phone heats up on long calls|Calls are costly|Signal drops|Battery drains|Cause stated in the passage.',
'Rain makes the path slippery, so hikers wear boots with deeper grips.|Why do hikers wear deep-grip boots?|Rain makes the path slippery|Boots look nice|Paths are short|Grass is tall|Reason stated in the passage.',
'The oven timer rings after twenty minutes, so Priya sets it before prep.|When does Priya set the timer?|Before prep|After eating|During cleaning|On Sunday|Timing stated in the passage.',
'Leaves turn yellow in autumn as trees save food for winter.|Why do leaves turn yellow?|Trees save food for winter|It rains more often|Wind strips colour|Birds eat leaves|Reason stated in the passage.',
'The pond freezes in January, so children skate on it then.|What do children do on the pond in January?|Skate|Swim|Fish|Boat|Freezing enables skating, as stated.',
'Dust on solar panels cuts output, so the crew washes them weekly.|Why are panels washed weekly?|Dust cuts output|Rain damages them|Birds sit on them|Paint fades|Reason stated in the passage.',
'The factory runs day and night, so workers rotate shifts every week.|Why do workers rotate shifts?|Factory runs day and night|Wages drop monthly|Machines break often|Lights fail|Cause stated in the passage.',
'Coral reefs bleach when water gets too warm, harming the fish that live there.|What harms reef fish when water warms?|Reef bleaching|Less salt|More sunlight|Heavier waves|Stated in the passage.',
'The shop packs groceries in cloth bags to cut plastic use.|Why does the shop use cloth bags?|To cut plastic use|To save money|To look modern|To hire staff|Purpose stated in the passage.',
'Frogs absorb water through their skin, so they need damp places to live.|Why do frogs need damp places?|They absorb water through skin|They fear sunlight|They eat dry food|They lay eggs underwater|Reason stated in the passage.',
'The alarm sounds if a door opens, so nothing is stolen overnight.|What prevents theft overnight?|The door-open alarm|Loud music|Bright lights|A guard dog|Stated in the passage.',
'The train slows on curves, so the journey takes longer on hilly routes.|Why does the journey take longer on hills?|Train slows on curves|Seats are fewer|Doors stick|Fares rise|Reason stated in the passage.',
'Wet roads double braking distance, so drivers slow down in rain.|Why do drivers slow down in rain?|Wet roads double braking|Rain blocks the roof|Tyres go flat|Lights dim|Reason stated in the passage.',
'Bats use echoes to find food at night, which is called echolocation.|What is the bat night-finding method called?|Echolocation|Photosynthesis|Migration|Hibernation|Stated in the passage.',
'The pyramid stones were dragged on wet sand to reduce friction, saving labour.|Why was sand wet before dragging stones?|To reduce friction|To clean the stones|To build a road|To mark a path|Reason stated in the passage.',
'The coach gave water breaks every fifteen minutes, so no player felt dizzy.|Why did the coach give frequent water breaks?|To prevent dizziness|To waste time|To rest himself|To check phones|Purpose stated in the passage.',
'The old bridge creaks in strong winds, so trucks avoid crossing then.|Why do trucks avoid the bridge in wind?|It creaks in strong winds|It gets too narrow|Fees increase|Lights fail|Reason stated in the passage.',
'Yogurt stays fresh longer in cold storage because chill slows bacterial growth.|Why does cold storage help yogurt?|Chill slows bacteria|It kills all germs|It adds flavour|It hardens texture|Reason stated in the passage.',
'The festival moves to the town hall if rain falls on the main day.|Where does the festival move if it rains?|Town hall|The riverbank|The school|The market|Stated in the passage.',
'Students who read aloud remember more, because hearing reinforces the text.|Why do aloud readers remember more?|Hearing reinforces the text|They read faster|Books are brighter|Rooms are quiet|Reason stated in the passage.',
'The rover took photos every hour, so scientists tracked dust storms on Mars.|What did hourly photos help scientists track?|Dust storms on Mars|Rover battery|Sunrise colour|Temperature only|Stated in the passage.',
'The hall has thick curtains to block outside noise during concerts.|Why are curtains thick in the hall?|To block outside noise|To show off style|To trap heat|To hide the stage|Purpose stated in the passage.',
'Cyclists wear bright jackets so drivers can spot them from far away.|Why do cyclists wear bright jackets?|To be spotted by drivers|To stay warm|To look cool|To carry tools|Reason stated in the passage.',
'The baker kneads dough twice to make the bread softer.|Why is dough kneaded twice?|For softer bread|To save flour|To use less water|To speed baking|Purpose stated in the passage.',
'Fish rise to the surface when oxygen drops in deeper water.|Why do fish rise to the surface?|Oxygen drops in deeper water|Light is brighter|Food floats there|It is warmer|Reason stated in the passage.',
'The bus adds extra trips during holidays, so queues stay short.|Why do queues stay short in holidays?|Extra trips are added|Buses are larger|Tickets are free|Stops are fewer|Reason stated in the passage.',
'A pencil floats in space because there is no gravity to pull it down.|Why does a pencil float in space?|No gravity|It is too light|Air pushes it|Magnetism|Reason stated in the passage.',
'The nurse checks vitals every four hours to catch problems early.|Why are vitals checked every four hours?|To catch problems early|To pass the time|To fill records|To test equipment|Purpose stated in the passage.',
'The village well dries in May, so families store water from April.|Why do families store water from April?|Well dries in May|It rains in April|Pipes burst|Tanks leak|Cause stated in the passage.',
'Recycled paper needs less energy than fresh paper, saving costs.|Why is recycled paper cheaper to make?|Less energy is needed|Trees are free|Ink is reused|Labour is cut|Reason stated in the passage.',
'The guard checks each bag because sharp items are not allowed.|Why are bags checked?|Sharp items are not allowed|To slow queues|To count visitors|To test scanners|Reason stated in the passage.',
'Seeds need warmth and water to sprout, so spring is the best planting time.|Why is spring best for planting?|Seeds need warmth and water|Soil is deeper|Days are longer|Birds are fewer|Reason stated in the passage.',
'The app locks after three wrong tries to protect the account.|Why does the app lock after three wrong tries?|To protect the account|To annoy users|To save data|To show ads|Purpose stated in the passage.',
'The coach chose a slower pace at the start so runners had energy left later.|Why was the start pace slow?|To save energy later|To fall behind|To watch others|To stretch more|Reason stated in the passage.',
'Milk curdles in heat unless it is kept cold, so shops use refrigerated shelves.|Why do shops use refrigerated shelves?|Milk curdles in heat|Milk tastes better|Shops save space|Lights stay dim|Reason stated in the passage.',
'The park opens at dawn, so joggers arrive before sunrise.|Why do joggers arrive before sunrise?|Park opens at dawn|It rains in afternoon|Air is fresher|Fees are lower|Reason stated in the passage.',
'Wool keeps warmth even when wet, so shepherds wear it in rain.|Why do shepherds wear wool in rain?|Wool stays warm when wet|Wool dries slowly|It looks bright|It repels insects|Reason stated in the passage.',
'The sign warns of soft ground, so trucks use the bypass road.|Why do trucks use the bypass?|Soft ground ahead|Tolls are lower|Road is shorter|View is nicer|Reason stated in the passage.',
'The kettle whistles when steam escapes, signalling the water has boiled.|What does the whistle signal?|Water has boiled|Kettle is full|Flame is low|Milk is added|Steam-driven whistle signals boiling.',
'The school plants trees along the fence to reduce dust entering classrooms.|Why are trees planted along the fence?|To reduce dust|For fruit|For shade only|To block light|Purpose stated in the passage.',
'The runner stretched before the race to avoid muscle pulls.|Why did the runner stretch before the race?|To avoid muscle pulls|To look calm|To warm the crowd|To slow down|Purpose stated in the passage.',
'Birds sit on power lines safely because they touch only one wire at a time.|Why are birds safe on a single wire?|They touch only one wire|They are too light|Wire is coated|Voltage is zero|Reason stated in the passage.',
'The shop wraps glass in bubble wrap to prevent cracks during transit.|Why is bubble wrap used?|To prevent cracks|To look neat|To add weight|To hide the item|Purpose stated in the passage.',
'Farmers light fields at night to keep wild animals away from crops.|Why are fields lit at night?|To keep animals away|To dry soil|To find tools|To grow plants|Purpose stated in the passage.',
'The clock loses two minutes each day, so it is reset every Sunday.|Why is the clock reset Sunday?|It loses two minutes daily|It stops often|It shows date|It glows dimly|Reason stated in the passage.',
'The tank overflows if the valve is left open, so taps are checked twice.|Why are taps checked twice?|Tank may overflow|Floors get dusty|Water tastes odd|Pipes freeze|Reason stated in the passage.',
'Spices are stored in airtight jars so they keep their aroma longer.|Why are spice jars airtight?|To keep aroma longer|To save space|To hide colour|To add weight|Reason stated in the passage.',
'The coach drew diagrams on the board so visual learners could follow.|Why were diagrams drawn?|For visual learners|To fill time|To practise art|To test markers|Purpose stated in the passage.',
'Clouds form when moist air rises and cools, turning vapour into droplets.|When do clouds form?|When moist air rises and cools|When wind stops|When it rains|When sun sets|Condition stated in the passage.',
'The farmer covers hay with a tarp to keep rain from ruining it.|Why is hay covered?|To keep rain from ruining it|To hide it|To warm it|To dry it|Purpose stated in the passage.',
'The class ends early on Wednesdays, so students attend clubs after.|What happens after early Wednesday class?|Clubs|Exams|Trips|Tests|Stated in the passage.',
'The road narrows near the bridge, so cars must slow down there.|Why do cars slow near the bridge?|Road narrows|It gets dark|Police wait|Fuel ends|Reason stated in the passage.',
'Salt is spread on icy roads to lower the freezing point and melt ice.|Why is salt spread on ice?|To lower freezing point|Taste better|Attract birds|Colour the road|Reason stated in the passage.',
'The label lists ingredients so buyers can spot allergens.|Why list ingredients on the label?|To help spot allergens|To fill space|To look fancy|To list prices|Purpose stated in the passage.',
'The bell rings at noon, signalling the lunch break to all staff.|What does the noon bell signal?|Lunch break|Meeting start|Work end|Shift change|Stated in the passage.',
'Sweating cools the body because evaporating water carries heat away.|How does sweating cool the body?|Evaporation carries heat|It adds moisture|It blocks sun|It stiffens skin|Reason stated in the passage.',
'The rope snapped under heavy load, so a thicker rope was used next time.|Why was a thicker rope used?|Old rope snapped under load|It looked better|It cost less|It was lighter|Reason stated in the passage.',
'The fridge door has a seal to keep cold air from escaping.|Why does the fridge door have a seal?|To keep cold air in|To block noise|To hold notes|To look sleek|Purpose stated in the passage.',
'The hiker carried extra maps in case the trail signs were missing.|Why carry extra maps?|Trail signs might be missing|To sell them|To fill a bag|To practise reading|Reason stated in the passage.',
'The team meets every Monday to plan the weeks tasks.|When does the team meet to plan?|Every Monday|Every Friday|On holidays|At month end|Stated in the passage.',
'The painting was hung at eye level so viewers could see details easily.|Why hang the painting at eye level?|To see details easily|To save wall space|To avoid light|To hide frame|Purpose stated in the passage.',
'The doctor asked for a blood test to rule out infection.|Why was a blood test ordered?|To rule out infection|To check height|To test eyes|To measure weight|Purpose stated in the passage.',
'The gate is painted to stop rust from forming on the metal.|Why is the gate painted?|To stop rust|To show off|To add weight|To darken it|Purpose stated in the passage.',
'The chef chops vegetables finely so they cook faster.|Why chop vegetables finely?|To cook faster|To save water|To look bright|To add crunch|Reason stated in the passage.',
'The tent has pegs to hold it down in strong wind.|Why are tent pegs used?|To hold it down in wind|To hang bags|To mark space|To dig holes|Purpose stated in the passage.',
'The sun rises in the east because Earth spins towards the east.|Why does the sun rise in the east?|Earth spins east|Sun moves west|Clouds shift|Stars rotate|Reason stated in the passage.',
'The library stamps each book so it can be tracked when borrowed.|Why are books stamped?|To track borrowing|To look official|To hide titles|To add value|Purpose stated in the passage.',
'The baker preheats the oven so bread bakes evenly.|Why preheat the oven?|To bake evenly|To save time|To clean it|To cool the kitchen|Reason stated in the passage.',
'The town planted neem trees to give shade along the road.|Why were neem trees planted?|To give shade|For wood|For flowers|For fruit|Purpose stated in the passage.',
'The bus fills up at the market stop, so commuters board earlier.|Why do commuters board before the market stop?|Bus fills up there|Fares change|Drivers swap|Seats break|Reason stated in the passage.',
'The scarf is worn to keep the neck warm in winter.|Why wear a scarf?|To keep neck warm|To look tall|To hide face|To match shoes|Purpose stated in the passage.',
'The guard locks the gate at ten, so visitors arrive before then.|When do visitors need to arrive?|Before ten|After midnight|On Sunday|At noon|Closing time stated.',
'The fielder stood close to catch the ball quickly on fast pitches.|Why stand close on fast pitches?|To catch quickly|To block sun|To rest more|To cheer louder|Reason stated in the passage.',
'The bell tower chimes each hour, helping people keep track of time.|What do the chimes help with?|Keeping track of time|Finding the tower|Waking birds|Cooling air|Purpose stated in the passage.',
'The team trained at dawn to avoid the afternoon heat.|Why train at dawn?|To avoid afternoon heat|To sleep later|To skip breakfast|To watch sunrise|Reason stated in the passage.',
'The cupboard was anchored to the wall so it would not tip over.|Why anchor the cupboard?|To prevent tipping|To hide wires|To save space|To hang clothes|Purpose stated in the passage.',
'The river flows fastest in the centre, so boats stay near the bank.|Why do boats stay near the bank?|River flows fastest in centre|Banks are shallow|Fish gather there|Poles stick out|Reason stated in the passage.',
'The chef sharpens knives daily so cutting is clean and quick.|Why sharpen knives daily?|For clean quick cutting|To save time|To look skilled|To use less force|Reason stated in the passage.',
'The school added ramps so wheelchair users could enter easily.|Why add ramps?|For wheelchair access|For style|For shade|For drainage|Purpose stated in the passage.',
'The rover drills into rocks to look for signs of ancient water.|Why drill into rocks?|To find ancient water signs|To dig tunnels|To test drills|To collect dust|Purpose stated in the passage.',
'The clock chimed twelve times at noon, marking the lunch hour.|What does noon chime mark?|Lunch hour|School end|Meeting start|Game over|Stated in the passage.',
'The farmer watered at dawn to reduce loss from evaporation.|Why water at dawn?|To reduce evaporation|To wake early|To use less water|To catch dew|Reason stated in the passage.',
'The bridge was widened so two buses could pass at once.|Why widen the bridge?|For two buses to pass|To add lamps|To paint it|To slow traffic|Purpose stated in the passage.',
'The shop added mirrors to make the room look larger.|Why add mirrors?|To make room look larger|For selfies|For light|For art|Purpose stated in the passage.',
'The hiker wore layers so clothing could be added or removed.|Why wear layers?|To add or remove clothing|To look neat|To save space|To match colours|Reason stated in the passage.',
'The coach repeated the rule until every player understood it.|Why repeat the rule?|Until everyone understood|To fill time|To test memory|To practise speech|Purpose stated in the passage.',
'The jar lid is loosened by running hot water over it, using expansion.|Why run hot water on a tight lid?|Metal expands|To clean it|To cool it|To test it|Reason stated in the passage.',
'The stage lights dim slowly so audiences eyes can adjust.|Why dim lights slowly?|Eyes need time to adjust|To save power|To hide actors|To test bulbs|Reason stated in the passage.',
'The baker scores bread dough so it rises evenly in the oven.|Why score dough?|To rise evenly|To look pretty|To add flavour|To cool it|Purpose stated in the passage.',
'The ship has a heavy keel to keep it upright in rough seas.|Why does a ship have a heavy keel?|To stay upright|To go faster|To carry cargo|To look grand|Purpose stated in the passage.',
'The fan blades are angled to push air forward, cooling the room.|Why are fan blades angled?|To push air forward|To look neat|To reduce noise|To save power|Reason stated in the passage.',
'The helmet strap is tightened so it stays on the head during a fall.|Why tighten the helmet strap?|To keep it on during a fall|To look sharp|To block noise|To match the bike|Reason stated in the passage.',
];
const rcItems = RC_P.slice(0, 150).map(l => { const p = l.split('|'); return ['Read the passage: "' + p[0] + '" â€” ' + p[1], p[2], p[3], p[4], p[5], p[6]]; });


const owsItems = OWS_P.slice(0, 150).map(l => { const p = l.split('|'); return ['Choose the one word that means: ' + p[0], p[1], p[2], p[3], p[4], 'One word: ' + p[1] + ' (' + p[5] + ')']; });
const idmItems = IDM_P.slice(0, 150).map(l => { const p = l.split('|'); return ['Choose the correct meaning of the idiom: "' + p[0] + '"', p[1], p[2], p[3], p[4], '"' + p[0] + '" means ' + p[1] + '. Example: ' + p[5]]; });
const band = (arr, n) => arr.slice(n * 50, n * 50 + 50);
G['One Word Substitution'] = bankGen(band(owsItems, 0), band(owsItems, 1), band(owsItems, 2), 'one-word substitution (root/etymology based)');
G['Idioms & Phrases'] = bankGen(band(idmItems, 0), band(idmItems, 1), band(idmItems, 2), 'idiomatic usage and figurative meaning');

module.exports = { G, bankGen };

const SYN_ALL = parsePipe(SYN_P), ANT_ALL = parsePipe(ANT_P);
const SA_MIX = SYN_ALL.slice(0, 50).concat(ANT_ALL.slice(0, 50)).concat(SYN_ALL.slice(50, 91).concat(ANT_ALL.slice(50, 60)).slice(0, 50));
G['Synonyms & Antonyms'] = (r, i, c) => {
  const it = SA_MIX[i % SA_MIX.length];
  const isSyn = SYN_ALL.some(x => x.w === it.w);
  const stem = (isSyn ? 'Choose the word closest in MEANING to: ' : 'Choose the word most OPPOSITE in meaning to: ') + it.w.toUpperCase();
  const expl = '"' + it.w + '" means "' + it.g + '". ' + (isSyn ? 'A word with the same sense is' : 'The direct opposite is') + ' "' + it.a + '".';
  return c.buildMCQ({ r, stem, right: it.a, wrong: [it.w1, it.w2, it.w3], explanation: expl, steps: ['Focus on the headword: ' + it.w + ' (' + it.g + ')', isSyn ? 'Look for the option with a matching sense' : 'Look for the option with a contrary sense', isSyn ? '"' + it.a + '" matches the sense, so it is the synonym' : '"' + it.a + '" is contrary, so it is the antonym'] });
};
G['Reading Comprehension'] = bankGen(band(rcItems, 0), band(rcItems, 1), band(rcItems, 2), 'reading comprehension and direct inference');
module.exports = { G, bankGen };
