/**
 * Canonical detector for SEEDED-PLACEHOLDER content.
 *
 * Background: `scripts/seedSQLProblemsExpanded.js` defines SQL problem METADATA
 * only (title/topic/difficulty/tags). It has no authored schema, dataset or
 * query, so it writes placeholder execution fixtures. Historically those
 * placeholders were indistinguishable from real content, which made a whole
 * bank of unrunnable problems look healthy.
 *
 * `scripts/backfillSQLProblemStructure.js` additionally injected ONE generic
 * `employees(id, name, department, salary)` schema + Alice/Bob/Charlie example
 * into every SQL problem that lacked one - including problems whose reference
 * solution queries `orders`, `users`, `sales`, ...
 *
 * Every module that seeds, audits or verifies SQL content must use THIS module
 * so the fingerprints can never drift apart again.
 */

// ---- SQL placeholder fixtures (written by seedSQLProblemsExpanded.js) -------
const PLACEHOLDER_SCHEMA_SETUP =
  "CREATE TABLE test_table (id INT, name VARCHAR(100), value INT);\nINSERT INTO test_table VALUES (1, 'Sample', 100);";
const PLACEHOLDER_REFERENCE_SQL = 'SELECT * FROM test_table;';
const PLACEHOLDER_SAMPLE_ROWS = [{ id: 1, name: 'Sample', value: 100 }];
const PLACEHOLDER_HIDDEN_INPUT = "INSERT INTO test_table VALUES (2, 'Test', 200);";
const PLACEHOLDER_HIDDEN_ROWS = [
  { id: 1, name: 'Sample', value: 100 },
  { id: 2, name: 'Test', value: 200 },
];

// ---- Generic employees fixture (written by backfillSQLProblemStructure.js) --
const GENERIC_SQL_TABLE = 'employees';
const GENERIC_SQL_COLUMNS = ['id', 'name', 'department', 'salary'];
const GENERIC_SQL_SCHEMA_TABLE = {
  tableName: GENERIC_SQL_TABLE,
  columns: [
    { name: 'id', type: 'INT' },
    { name: 'name', type: 'VARCHAR(100)' },
    { name: 'department', type: 'VARCHAR(100)' },
    { name: 'salary', type: 'DECIMAL(10,2)' },
  ],
  notes: 'id is the primary key for this table.',
};
const GENERIC_SQL_ROWS = [
  { id: 1, name: 'Alice', department: 'Engineering', salary: 120000 },
  { id: 2, name: 'Bob', department: 'Marketing', salary: 95000 },
  { id: 3, name: 'Charlie', department: 'Engineering', salary: 110000 },
];

const jest = (v) => JSON.stringify(v);

/** schemaSetupSQL is the `test_table` stub, i.e. real DDL was never authored. */
function isPlaceholderSchemaSetup(sql) {
  const s = String(sql || '');
  return /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?test_table\b/i.test(s) && /\bvalue\s+INT\b/i.test(s);
}

/** referenceSolutionSQL is the `SELECT * FROM test_table` stub. */
function isPlaceholderReferenceSQL(sql) {
  return /^\s*SELECT\s+\*\s+FROM\s+test_table\s*;?\s*$/i.test(String(sql || ''));
}

/** sampleTestCases[0].expectedOutputRows is the Sample/100 stub. */
function isPlaceholderSampleRows(rows) {
  return jest(rows || []) === jest(PLACEHOLDER_SAMPLE_ROWS);
}

/** hiddenTestCases contains the `INSERT INTO test_table VALUES (2, 'Test', 200)` stub. */
function isPlaceholderHiddenTestCases(cases) {
  return (cases || []).some((c) => String((c && c.inputStateSQL) || '').includes(PLACEHOLDER_HIDDEN_INPUT));
}

/** Description was generated by a seeder rather than authored. */
function isPlaceholderDescription(desc) {
  const d = String(desc || '');
  return /Spec not yet reviewed/i.test(d)
    || /Fixture not yet authored/i.test(d)
    || /\(Fixture not yet authored\)/i.test(d)
    || /^Solve the .+ (?:SQL )?problem\./i.test(d)
    || /^Write a (?:basic SQL SELECT query|SQL query to solve)/i.test(d);
}

/** schemaTables is the single generic `employees(id,name,department,salary)`. */
function isGenericEmployeesSchema(schemaTables) {
  const t = schemaTables || [];
  if (t.length !== 1) return false;
  if (t[0].tableName !== GENERIC_SQL_TABLE) return false;
  return (t[0].columns || []).map((c) => c.name).join(',') === GENERIC_SQL_COLUMNS.join(',');
}

/** examples[0].inputTables carries the hardcoded generic employees rows. */
function isGenericEmployeesExample(examples) {
  return (examples || []).some((e) =>
    ((e && e.inputTables) || []).some((t) =>
      t.tableName === GENERIC_SQL_TABLE
      && (t.rows || []).length === GENERIC_SQL_ROWS.length
      && (t.rows || []).every((r, i) => r && r.name === GENERIC_SQL_ROWS[i].name
        && r.department === GENERIC_SQL_ROWS[i].department)));
}

/** Tables a SQL statement reads from via FROM / JOIN. */
function referencedTables(sql) {
  const s = String(sql || '');
  // CTE / derived-table aliases declared as `name AS (` are not base tables:
  // exclude them so `FROM cte_name` is never mistaken for a missing table.
  const aliases = new Set();
  for (const m of s.matchAll(/\b([A-Za-z_][\w]*)\s+AS\s*\(/gi)) aliases.add(m[1].toLowerCase());
  const out = [];
  const re = /\b(?:FROM|JOIN)\s+[`"[]?([A-Za-z_][\w]*)[`"\]]?/gi;
  let m;
  while ((m = re.exec(s)) !== null) out.push(m[1].toLowerCase());
  return [...new Set(out)].filter((t) => t !== 'select' && t !== 'dual' && !aliases.has(t));
}

/** Tables a schemaSetupSQL statement creates. */
function createdTables(sql) {
  const out = [];
  const re = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`"[]?([A-Za-z_][\w]*)[`"\]]?/gi;
  let m;
  while ((m = re.exec(String(sql || ''))) !== null) out.push(m[1].toLowerCase());
  return [...new Set(out)];
}

/** Reference solutions that the fixture schema cannot possibly satisfy. */
function referenceTablesMissingFromSchema(schemaSetupSQL, referenceSolutionSQL) {
  const created = createdTables(schemaSetupSQL);
  return referencedTables(referenceSolutionSQL).filter((t) => !created.includes(t));
}

/**
 * The generic employees fixture is only safe when the problem's own reference
 * solution reads nothing but `employees` and uses no extra quoted identifier.
 */
function genericFixtureIsCompatible(referenceSolutionSQL) {
  const ref = String(referenceSolutionSQL || '');
  if (!ref.trim()) return false;
  const tables = referencedTables(ref);
  if (tables.length !== 1 || tables[0] !== GENERIC_SQL_TABLE) return false;
  const quoted = ref.match(/[`"[]([A-Za-z_][\w]*)[`"\]]/g) || [];
  for (const q of quoted) {
    const name = q.slice(1, -1).toLowerCase();
    if (!GENERIC_SQL_COLUMNS.includes(name) && name !== GENERIC_SQL_TABLE) return false;
  }
  return true;
}

module.exports = {
  PLACEHOLDER_SCHEMA_SETUP,
  PLACEHOLDER_REFERENCE_SQL,
  PLACEHOLDER_SAMPLE_ROWS,
  PLACEHOLDER_HIDDEN_INPUT,
  PLACEHOLDER_HIDDEN_ROWS,
  GENERIC_SQL_TABLE,
  GENERIC_SQL_COLUMNS,
  GENERIC_SQL_SCHEMA_TABLE,
  GENERIC_SQL_ROWS,
  isPlaceholderSchemaSetup,
  isPlaceholderReferenceSQL,
  isPlaceholderSampleRows,
  isPlaceholderHiddenTestCases,
  isPlaceholderDescription,
  isGenericEmployeesSchema,
  isGenericEmployeesExample,
  referencedTables,
  createdTables,
  referenceTablesMissingFromSchema,
  genericFixtureIsCompatible,
};
